### ISSUE TITLE
Handle correctly internal links for SEO purposes

### ISSUE THREAD

**Issue by Zeokat** [flarum/core#1173] opened 2017-05-02 12:41 UTC
## Bug report
- Version of Flarum: dev and v0.1.0-beta.6
- Website URL where the bug is visible: https://discuss.flarum.org/
- The webserver you are running: nginx
- PHP version: PHP 5 or PHP 7, error always appear.
- Hosted environment: local server and VPS
- Hosting provider: some

## Flarum info

```
zeokat@ubuntu:/var/www/html/flarum$ php flarum info
Flarum core 0.1.0-beta.6
PHP 7.0.15-0ubuntu0.16.04.4
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
EXT flarum-approval v0.1.0-beta.6
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.6
EXT flarum-flags v0.1.0-beta.6
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
Base URL: http://192.168.247.128/flarum
Installation path: /var/www/html/flarum
```

## Additional comments
Flarum adds `rel="nofollow"` attribute to all links posted, it's a serious issue that damage website SERPs and don't follow SEO best practices.

It was discussed many times into Flarums forum, for example [here](https://discuss.flarum.org/d/5661-need-help-deleting-rel-nofollow-from-internal-links/11) but the problem seems that can't be fixed easily at this development stage.

Flarum "views" every link posted into a discussion as external and that's a wrong concept when we speak about SEO. External and internal domains are related to the domain. For example into `https://discuss.flarum.org/` all urls that works under main domain `https://discuss.flarum.org/` must be internal links. This guarantees a proper link juice flow into the community.

At the moment, all forum software tested works in this way (MyBB, phpBB, NodeBB, etc...) and Flarum also should adopt this good SEO practice.

In some situations other subdomains and main domain (for example `https://flarum.org/` , `https://docs.flarum.org/`, etc) can be handled as internal links, but maybe this situations should be handled by an extension instead core.

## Log files

```
Put any relevant logs here.
```

**Comment by Luceos** [comment] 2017-05-02 13:52
Duplicate of https://github.com/flarum/core/issues/626

**Closed by Luceos** 2017-05-02 13:52 UTC
