### ISSUE TITLE
Unable to uninstall extensions

### ISSUE THREAD

**Issue by AlanTheGreat2018** [flarum/core#1526] opened 2018-08-03 17:33 UTC
## Bug Report

**Current Behavior**
When trying to uninstall extensions, I get `Oops! Something went wrong. Please reload the page and try again.` When looking at the debug output, it says:

```
POST http://dev.flarum/api/extensions/flarum-auth-github

null
```

**Steps to Reproduce**
1. Go to the Admin Page
2. Go to the Extensions Page
3. Click on the three dots on the bottom left corner of one of the extension icons
4. Click Uninstall
5. See error

**Expected Behavior**
The extension would uninstall, and the page would refresh.

**Environment**
- Flarum version: dev-master and beta7
- Website URL: http://dev.flarum
- Webserver: apache
- Hosting environment: Ubuntu 18.04 Desktop
- PHP version: 7.2.7 and 7.1
- Browser: Chrome and Firefox

```
Output of `php flarum info`:

```
Flarum core 0.1.0-beta.7
PHP 7.2.7-0ubuntu0.18.04.2
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-english v0.1.0-beta.7
EXT reflar-enso-theme dev-master (c56b7da679c95424a3d4961d28f36e266b842707)
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT extum-old-title 9999999-dev (3dcffeff45695202ca5cc316f49176759487fa23)
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://localhost
Installation path: /var/www/html
```

**Comment by TurboProgramming** [comment] 2018-08-05 15:51
I tried this and was only able to reproduce this if I got some extensions installed.

Other than that, the core itself worked properly.

**Comment by datitisev** [comment] 2018-08-05 16:31
The ability to uninstall extensions is not present in Flarum yet, only the UI.
This is known.

**Comment by TurboProgramming** [comment] 2018-08-05 16:40
Looks like I'm confused with disabling & removing an extension lol.

**Comment by franzliedke** [comment] 2018-08-19 21:30
Do we want to keep this open?

**Comment by luceos** [comment] 2018-08-20 05:28
@franzliedke I am in favour of closing. This is a (well known) issue and something not easily fixed. Once the extension installation procedure is fixed, this will be fixed as well.

**Closed** 2018-08-20 06:04 UTC
