### ISSUE TITLE
Search performance regression

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#1764] opened 2019-03-24 01:43 UTC
#1741 introduced a regression in search performance which needs to be looked at.

**Comment by luceos** [comment] 2019-03-24 18:20
For my information, how did you discover this?

**Comment by tobscure** [comment] 2019-03-24 20:41
I had a feeling there was a reason I didn't use `left join` when I wrote the search code, and I am aware of performance differences between `left` and normal `join`. So that tipped me off that I should performance-test this change.

To do so, I just ran the search SQL for the keyword "beta" with and without `left` against the discuss.flarum.org database. The effect is big enough that you can see it directly on discuss.flarum.org ([this page](https://discuss.flarum.org/?q=beta) takes way too long to load)

**Comment by luceos** [comment] 2019-03-26 09:25
Would it make sense to add a test that:

- creates a predefined set of discussions with a specific keyword
- measures response time of a search onto that keyword
- reports in when the response time is out of bounds

/cc @franzliedke 

The reason I ask is that we want to prevent to have detrimental performance consequences of PR's that look okayish at first.

**Comment by vingrad** [comment] 2019-08-18 16:14
I think, that it would be make sense to do elasticsearch integration.

**Comment by laTruffe79** [comment] 2019-09-28 20:00
> I think, that it would be make sense to do elasticsearch integration.

Or firebase database could be an alternative which avoid to host flarum on dedicated servers or vps

**Comment by franzliedke** [comment] 2019-09-28 20:03
@vingrad @laTruffe79 Debates on principles won't help us with this ticket, this is about a very concrete performance regression. So I will mark these messages as off-topic.

Please feel free to take this discussion to [our forums](https://discuss.flarum.org), though. Thanks for your interest in Flarum!

**Comment by flarumalshain** [comment] 2019-10-01 18:24
```
$subquery = Post::whereVisibleTo($search->getActor())
            ->select('posts.discussion_id')
            ->selectRaw('SUM(MATCH('.$grammar->wrap('posts.content').') AGAINST (?)) as score', [$bit])
            ->selectRaw('SUBSTRING_INDEX(GROUP_CONCAT('.$grammar->wrap('posts.id').' ORDER BY MATCH('.$grammar->wrap('posts.content').') AGAINST (?) DESC, '.$grammar->wrap('posts.number').'), \',\', 1) as most_relevant_post_id', [$bit])
            ->where('posts.type', 'comment')
            ->where('posts.number', '1')
            ->where('posts.content', 'LIKE', '%'.$bit.'%')
            //->whereRaw('MATCH('.$grammar->wrap('posts.content').') AGAINST (? IN BOOLEAN MODE)', [$bit])
            ->groupBy('posts.discussion_id');
```

In this case, the CPU uses more, but a search function that works more healthy and more beautiful.

(Since LeftJoin uses too much CPU, I recommend using Join Only.)

**Comment by franzliedke** [comment] 2019-10-01 22:19
@flarumalshain The `leftJoin` was added in #1741 to fix [a bug](https://github.com/flarum/core/commit/26c3bcdb74f78d6ad6b46f19ec410e0219059aee) - so we cannot "just" revert. But yes, that change introduced the performance problems.

**Comment by zerosonesfun** [comment] 2019-10-13 00:23
@franzliedke I wonder though what’s worse? An unusable search, or a search that is faster but it just doesn’t search titles or whatever the issue was before. In other words, sure there was a bug before but at least search was faster. Maybe if no one can figure this out by beta 11 it should be reverted so that search works. Then, focus on a fix for the original bug.

**Comment by franzliedke** [comment] 2019-10-26 13:43
@zerosonesfun Yep, that's what we decided in yesterday's meeting as well. We reverted the change now, and are planning to spend a bit more time on e.g. a better indexing solution in the next sprint.

**Comment by franzliedke** [comment] 2019-10-26 13:44
@flarum/core Should we close this ticket in favor of a new edition of #1738?

**Comment by luceos** [comment] 2019-10-27 06:12
@franzliedke, I think if the regression was fixed yes. We do need one for a search engine implementation, but there ought to be one if I'm not mistaken.

**Comment by matteocontrini** [comment] 2019-10-27 08:09
There's #509

**Comment by franzliedke** [comment] 2019-10-27 20:50
Good idea, added that one to the 0.1 milestone. ElasticSearch is probably out of scope, but the driver infrastructure and a fairly naive indexing implementation could be doable.

**Closed** 2019-10-27 20:50 UTC
Labels: critical, type/regression

**Comment by luceos** [comment] 2019-11-26 12:11
This was reverted https://github.com/flarum/core/commit/9f6ec804324d0d7dfa5f378482f855a7bbdc3151

**Comment by mesutde** [comment] 2019-12-23 10:26
I believe that if you add this code, it will be improved to like
->where('discussions.title', 'LIKE', '%'.$bit.'%')
I added but I got the error.


$subquery = Post::whereVisibleTo($search->getActor())
->select('posts.discussion_id')
->selectRaw('SUM(MATCH('.$grammar->wrap('posts.content').') AGAINST (?)) as score', [$bit])
->selectRaw('SUBSTRING_INDEX(GROUP_CONCAT('.$grammar->wrap('posts.id').' ORDER BY MATCH('.$grammar->wrap('posts.content').') AGAINST (?) DESC, '.$grammar->wrap('posts.number').'), \',\', 1) as most_relevant_post_id', [$bit])
->where('posts.type', 'comment')
->whereRaw('MATCH('.$grammar->wrap('posts.content').') AGAINST (? IN BOOLEAN MODE)', [$bit])
->groupBy('posts.discussion_id');

**Comment by mesutde** [comment] 2019-12-23 10:29
> ```
> $subquery = Post::whereVisibleTo($search->getActor())
>             ->select('posts.discussion_id')
>             ->selectRaw('SUM(MATCH('.$grammar->wrap('posts.content').') AGAINST (?)) as score', [$bit])
>             ->selectRaw('SUBSTRING_INDEX(GROUP_CONCAT('.$grammar->wrap('posts.id').' ORDER BY MATCH('.$grammar->wrap('posts.content').') AGAINST (?) DESC, '.$grammar->wrap('posts.number').'), \',\', 1) as most_relevant_post_id', [$bit])
>             ->where('posts.type', 'comment')
>             ->where('posts.number', '1')
>             ->where('posts.content', 'LIKE', '%'.$bit.'%')
>             //->whereRaw('MATCH('.$grammar->wrap('posts.content').') AGAINST (? IN BOOLEAN MODE)', [$bit])
>             ->groupBy('posts.discussion_id');
> ```
> 
> In this case, the CPU uses more, but a search function that works more healthy and more beautiful.
> 
> (Since LeftJoin uses too much CPU, I recommend using Join Only.)

I believe that if you add this code, it will be improved to like
->where('discussions.title', 'LIKE', '%'.$bit.'%')
I added but I got the error.

$subquery = Post::whereVisibleTo($search->getActor())
->select('posts.discussion_id')
->selectRaw('SUM(MATCH('.$grammar->wrap('posts.content').') AGAINST (?)) as score', [$bit])
->selectRaw('SUBSTRING_INDEX(GROUP_CONCAT('.$grammar->wrap('posts.id').' ORDER BY MATCH('.$grammar->wrap('posts.content').') AGAINST (?) DESC, '.$grammar->wrap('posts.number').'), ',', 1) as most_relevant_post_id', [$bit])
->where('posts.type', 'comment')
->whereRaw('MATCH('.$grammar->wrap('posts.content').') AGAINST (? IN BOOLEAN MODE)', [$bit])
->groupBy('posts.discussion_id');
