### ISSUE TITLE
Update confirmation message when deleting a user

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#1928] opened 2019-11-04 20:15 UTC
The current message says that the posts will be deleted, but they actually aren't (changed in beta8).

![immagine](https://user-images.githubusercontent.com/2164763/68154638-3a28ee80-ff48-11e9-91b5-c3a7df558eb0.png)

**Comment by zerosonesfun** [comment] 2019-12-08 19:01
I tested this with beta 11. The user is deleted and at least the post content on the frontend is deleted or hidden. A shell of a post (the title) still remains. This is what a deleted user’s post looks like. Username = deleted, and the content is gone.

<img src="https://i.ibb.co/4JKkQbn/screenshot-www-sitbreathe-be-2019-12-08-11-58-34.png" alt="screenshot-www-sitbreathe-be-2019-12-08-11-58-34" border="0" />

**Comment by datitisev** [comment] 2019-12-08 19:15
@zerosonesfun That's a different issue - and one most likely caused by an extension. Deleted post contente shows up just fine for me.
![image](https://user-images.githubusercontent.com/6401250/70394662-28ae8880-19c5-11ea-95d4-ab00578150f6.png)

**Comment by zerosonesfun** [comment] 2019-12-08 19:18
@datitisev Well shoot. Just when I thought I somewhat figured this out... I did see that the post content is still in the database, so I guess the frontend effect is probably an extension.

**Comment by askvortsov1** [comment] 2020-03-02 22:11
Fixed in https://github.com/flarum/lang-english/pull/157.

**Closed** 2020-03-06 20:42 UTC
Labels: type/bug
