### ISSUE TITLE
Suspended user should be not able to edit his avatar

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2441] opened 2020-11-06 13:43 UTC
## Bug Report

**Current Behavior**

If an user profile is suspended still be able to edit his avatar with abusive images; this should be not happen.

**Steps to Reproduce**
1. Suspend a user
2. Login as user and edit your avatar, you will be still able to change avatar with abusive pictures

**Expected Behavior**

Disabled user should not have any ability to edit his account.

**Environment**
- Flarum version: Beta 13

**Comment by clarkwinkelmann** [comment] 2020-11-06 17:39
Duplicate of flarum/issue-archive#214

**Closed** 2020-11-06 17:40 UTC
