### ISSUE TITLE
[Tags] Refreshing on page returns 500 Internal Server Error

### ISSUE THREAD

**Issue by datitisev** [flarum/core#969] opened 2016-05-30 14:24 UTC
The tags work just fine when changing routes & pages via Javascript, i.e. clicking the tab name on the sidebar.
However, whenever you refresh the page in a tag route,aka `/t/*`, it returns 500 Internal Server Error.

@webeindustry has confirmed that it isn't the fault of server-side cache

We believe it may be a cause of Toby changing the names of client views and all that stuff he has been doing lately, for it worked before.

**Comment by tobscure** [comment] 2016-05-31 04:16
Yep probably, I'll take a look.

**Comment by franzliedke** [comment] 2016-06-12 08:24
I just pushed [a small change](https://github.com/flarum/core/commit/1a2174d61411117ed71736ab78ef10d01819d3f4) that logs all exceptions that occur when delivering HTML from the server (forum & admin app).

That should help @webeindustry point us to where the problem occurs (as I cannot reproduce this locally either).

*I will need to add some logging for exceptions to the API stack, too, but that was a little more complicated, so I didn't have the time right now.*

**Comment by tobscure** [comment] 2016-06-12 08:37
Thanks Franz.

I believe this was fixed in 4bd05ee561741640504bbc3246f2a3e08935f050, but discuss.flarum.org has not been updated to the latest code yet, hence why you can't reproduce it locally but can on discuss.flarum.org.

**Closed by tobscure** 2016-06-12 08:37 UTC
Labels: Bug
