### ISSUE TITLE
[Mentions] link for users in preview mode incorrect

### ISSUE THREAD

**Issue by Luceos** [flarum/core#788] opened 2016-02-10 12:20 UTC
On the current live forums I noticed that when editing an existing post, the preview of that post shows links to users with a `/d/` in the url instead of a `/u/`. Couldn't find any matching issue, so I hope this is not duplicate.

**Comment by franzliedke** [comment] 2016-02-10 14:34
Hmm, I tried to look into this, but didn't quite understand what was going on. Need some help from @tobscure ...

**Comment by tobscure** [comment] 2016-03-16 10:06
Duplicate of #367

**Closed by tobscure** 2016-03-16 10:06 UTC
Labels: Bug, Core Extension
