### ISSUE TITLE
`php flarum cache:clear` fails silently if there are permissions errors

### ISSUE THREAD

**Issue by waltdestler** [flarum/core#2013] opened 2020-02-20 02:04 UTC
## Bug Report

**Current Behavior**
`php flarum cache:clear` fails silently if it runs into permissions problems when deleting cache files.

(On my server, Flarum saves cache files using the `www-data` user, which `php flarum cache:clear` can't delete when I run it under my regular SSH user, but it fails silently, leaving my Flarum in a totally broken state with no obvious explanation. Running `sudo php flarum cache:clear` fixes it, but I only figured that out after hours of trial-and-error.)

**Steps to Reproduce**
1. Run `php flarum cache:clear` under a user that does not have permission to delete the Flarum cache files.

**Expected Behavior**
`php flarum cache:clear` should display any errors it encounters when trying to delete cache files instead of failing silently.

**Environment**
- Flarum version: Beta 11
- Webserver: apache
- Hosting environment: Ubuntu 16.04.3 VPS
- PHP version: 7.2.13

**Comment by askvortsov1** [comment] 2021-04-14 04:48
Duplicate of https://github.com/flarum/core/issues/2723, which has been fixed.

**Closed by askvortsov1** 2021-04-14 04:48 UTC
Labels: type/bug
