### ISSUE TITLE
Issue on flarum core files

### ISSUE THREAD

**Issue by badev-ajay** [flarum/core#1718] opened 2018-12-26 07:51 UTC
Argument 1 passed to Flarum\Formatter\Event\Rendering::__construct() must be an instance of s9e\TextFormatter\Renderer, instance of __PHP_Incomplete_Class given, called in /var/www/html/vendor/flarum/core/src/Formatter/Formatter.php

## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Go to http://www.webtechbuzz.com
2. Click on any link

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42803285/50437713-f8372100-0910-11e9-88e5-8e25376fcda2.png)

**Environment**
- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

```
Output of "php flarum info", run this in terminal in your Flarum directory.
ubuntu@ip-172-31-36-211:/var/www/html$ php flarum info
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.10-0ubuntu0.18.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
+------------------------------+-----------------+--------+
| Flarum Extensions            |                 |        |
+------------------------------+-----------------+--------+
| ID                           | Version         | Commit |
+------------------------------+-----------------+--------+
| flarum-approval              | v0.1.0-beta.8   |        |
| flarum-bbcode                | v0.1.0-beta.8   |        |
| flarum-emoji                 | v0.1.0-beta.8   |        |
| flarum-lang-english          | v0.1.0-beta.8   |        |
| flarum-flags                 | v0.1.0-beta.8.1 |        |
| flarum-likes                 | v0.1.0-beta.8.1 |        |
| flarum-lock                  | v0.1.0-beta.8   |        |
| flarum-markdown              | v0.1.0-beta.8   |        |
| flarum-mentions              | v0.1.0-beta.8.1 |        |
| flarum-statistics            | v0.1.0-beta.8   |        |
| flarum-sticky                | v0.1.0-beta.8   |        |
| flarum-subscriptions         | v0.1.0-beta.8   |        |
| flarum-suspend               | v0.1.0-beta.8   |        |
| flarum-tags                  | v0.1.0-beta.8.2 |        |
| flarum-pusher                | v0.1.0-beta.8.1 |        |
| terabin-sitemap              | v1.0.2-beta.2   |        |
| clarkwinkelmann-emojionearea | 0.1.2           |        |
| flagrow-ads                  | 0.2.0-beta.1    |        |
+------------------------------+-----------------+--------+
Base URL: http://www.webtechbuzz.com
Installation path: /var/www/html
Debug mode: ON
Don't forget to turn off debug mode! It should never be turned on in a production system.

```

**Possible Solution**

**Additional Context**

**Comment by tobscure** [comment] 2018-12-27 04:41
What happens if you run `php flarum cache:clear` and reload the page?

**Comment by badev-ajay** [comment] 2018-12-27 05:34
ubuntu@ip-172-31-36-211:/var/www/html$ php flarum cache:clear
Clearing the cache...
ubuntu@ip-172-31-36-211:/var/www/html$ Same issue

**Comment by luceos** [comment] 2018-12-27 08:47
Post your composer.json please.

**Comment by badev-ajay** [comment] 2018-12-28 14:06
Hi team I have reinstalled again

**Comment by luceos** [comment] 2018-12-28 20:06
@badev-ajay and? Without additional information we cannot help you.

**Comment by franzliedke** [comment] 2018-12-29 23:38
I am closing this ticket due to a lack of information.

When you open a ticket, please follow our [Contributing Guidelines](https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md). Most importantly, please provide as much information as possible so that we can together find out the root cause.

We can reopen this when we have detailed instructions on how to reproduce this. We cannot help debugging problems like this here, if it hasn't been proven that Flarum's core is the problem.

**Closed by franzliedke** 2018-12-29 23:38 UTC

**Comment by badev-ajay** [comment] 2019-01-11 11:17
Hi Team I am again same issue after reinstall 
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.10-0ubuntu0.18.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
+----------------------+-----------------+--------+
| Flarum Extensions    |                 |        |
+----------------------+-----------------+--------+
| ID                   | Version         | Commit |
+----------------------+-----------------+--------+
| flarum-approval      | v0.1.0-beta.8   |        |
| flarum-bbcode        | v0.1.0-beta.8   |        |
| flarum-emoji         | v0.1.0-beta.8   |        |
| flarum-lang-english  | v0.1.0-beta.8   |        |
| flarum-flags         | v0.1.0-beta.8.1 |        |
| flarum-likes         | v0.1.0-beta.8.1 |        |
| flarum-lock          | v0.1.0-beta.8   |        |
| flarum-markdown      | v0.1.0-beta.8   |        |
| flarum-mentions      | v0.1.0-beta.8.1 |        |
| flarum-statistics    | v0.1.0-beta.8   |        |
| flarum-sticky        | v0.1.0-beta.8   |        |
| flarum-subscriptions | v0.1.0-beta.8   |        |
| flarum-suspend       | v0.1.0-beta.8   |        |
| flarum-tags          | v0.1.0-beta.8.2 |        |
| flarum-pusher        | v0.1.0-beta.8.1 |        |
| fof-pages            | 0.1.1           |        |
| sijad-links          | 0.1.0-beta.6    |        |
+----------------------+-----------------+--------+
Base URL: http://www.webtechbuzz.com
Installation path: /var/www/html
Debug mode: off

**Comment by luceos** [comment] 2019-01-11 13:21
Try deleting the following:

```bash
$ rm -rf storage/cache/textformatter/*
```
