### ISSUE TITLE
Page count incorrect when scrolling to bottom

### ISSUE THREAD

**Issue by katosdev** [flarum/core#1897] opened 2019-09-28 20:42 UTC
## Bug Report

**Current Behavior**
When scrolling past the last post to the editor, the page count changes to an incorrect value. This has been reproduced across a range of devices and browsers by myself and @Ralkage 

**Steps to Reproduce**
1. Go to any thread. 
2. Browse to the last post and note the post count (eg 399/399)
3. Scroll down to the editor
4. See error - the post count will change (e.g. 349/399) 

**Video of bug**
https://streamable.com/avmrw <--

**Comment by PeopleInside** [comment] 2019-10-02 21:39
Confirmed.

**Comment by PeopleInside** [comment] 2019-10-21 14:07
Hi, this seems to be fixed in the demo but I cannot see the fix here.

**Comment by rob006** [comment] 2019-10-22 09:32
This is not fixed on community. You can easily reproduce this by creating a long draft, so only your new post will be visible on screen - navigation will show you "1 of X posts" even if you're at the end of the discussion.

![02e8d92b](https://user-images.githubusercontent.com/5972388/67273876-9d823d80-f4bf-11e9-9382-0cf905ba1807.png)

**Comment by katosdev** [comment] 2019-10-27 13:21
In the interest of maintaining updates on this issue, please see below further discussion:
https://discuss.flarum.org/d/21747-page-count-incorrect-when-scrolling-to-bottom-1897

**Comment by rob006** [comment] 2020-01-25 15:16
bump

**Comment by PeopleInside** [comment] 2020-04-24 16:34
up :)

**Comment by katosdev** [comment] 2020-05-02 14:11
@flarum/core Are we able to push this for B14? :)

**Comment by rob006** [comment] 2020-07-31 17:33
bump

**Comment by askvortsov1** [comment] 2020-10-02 05:01
This can be done by modifying the `updateScrubber` method of `PostStreamState` by returning `count` if we're past the end of the end of the stream; that is, no posts are in the viewport, and we are at the end (IE, `PostStreamState.viewingEnd()` is true)

**Closed** 2020-10-15 21:35 UTC
Labels: Good first issue, Hacktoberfest
