### ISSUE TITLE
Guest users can't load more posts on profiles

### ISSUE THREAD

**Issue by katosdev** [flarum/core#2071] opened 2020-03-15 14:55 UTC
## Bug Report

**Current Behavior**
When browsing forums as a guest, the "Load More" button for posts is not shown on user profiles, however if you log in and scroll to the bottom of posts on a profile, the option is shown. 

Occurs on discuss.flarum.org

**Comment by datitisev** [comment] 2020-03-15 15:33
Looks like it's a back-end PHP bug.

The `loadMore` button shows if 20 (`loadLimit`) or more posts are returned. Both screenshots below should return 20 posts, even if they aren't all the same posts. https://github.com/flarum/core/blob/a2d1245e903566ebb2167be708977f525f47b252/js/src/forum/components/PostsUserPage.js#L153

When logged in:
![image](https://user-images.githubusercontent.com/6401250/76704617-9cd98600-66b0-11ea-82df-51d2ebe230c1.png)

When not logged in:
![image](https://user-images.githubusercontent.com/6401250/76704621-a5ca5780-66b0-11ea-8f8a-8473673abe05.png)

**Comment by askvortsov1** [comment] 2020-03-15 21:06
On mobile, I'm experiencing this issue even if I'm logged in. It'll show some posts/discussions, but won't load more as I scroll OR display a load more button

**Comment by datitisev** [comment] 2020-03-15 21:20
Looks to be an issue caused by permissions then, which is what I assumed (guest just being the easiest way to test it).

**Comment by Littlegolden** [comment] 2020-04-01 07:29
Not noly on mobile, but also on PC I have got this problem...

**Comment by datitisev** [comment] 2020-06-30 16:13
Still an issue.

**Comment by davwheat** [comment] 2020-08-13 12:43
@datitisev 

It happens when a user has deleted (or byobu) posts. When this happens, the backend filters them out, but this ends up happening after the query is complete, meaning you end up with a post count which is less than the limit (20).

I *might* have fixed this by creating a new `hidden` filter on the API on my fork of the repo, but I'm sure you can remember how little PHP I am familiar with. https://github.com/flarum/core/compare/master...davwheat:patch-1

I haven't checked if this would also work with byobu posts, but that's not core functionality :P

**Comment by datitisev** [comment] 2020-08-13 12:52
@davwheat I mean, we probably don't want to use a filter to solve this. The root issue would still exist, and any ext filtering out posts/discussions would probably result in the same problem.

**Comment by davwheat** [comment] 2020-08-13 12:59
What other way could work? Maybe showing the "load more" button all the time and if there are no more posts, then displaying a message?

**Comment by datitisev** [comment] 2020-08-13 15:53
No, the fact that there aren't 20 posts returned by the API when there are 20 visible to the user & that match the filter should be fixed.

**Comment by askvortsov1** [comment] 2020-08-16 21:34
This should be fixed when we merge https://github.com/flarum/core/pull/2104, as it'll then start using a common filter/search system alongside Discussions and Users

**Comment by w-4** [comment] 2020-09-08 10:51
one line fix if you don't want to wait for https://github.com/flarum/core/pull/2104:
inside ListPostsController:
![image](https://user-images.githubusercontent.com/36057469/92467397-bee53880-f1fb-11ea-9e3d-a9ff93cc6da1.png)

**Comment by askvortsov1** [comment] 2020-09-08 14:30
> one line fix if you don't want to wait for #2104:

That's a good point! Have you had a chance to test that this works locally? If so, a PR would very much be appreciated!

**Comment by w-4** [comment] 2020-09-08 17:53
Ok will do. Tested that the API request now returns 20 posts.

**Closed** 2020-09-18 03:59 UTC
