### ISSUE TITLE
Multiple mentions will only email first user tagged

### ISSUE THREAD

**Issue by IronSinew** [flarum/core#3151] opened 2021-11-04 21:28 UTC
## Bug Report

**Current Behavior**
When tagging multiple users at the beginning of a post (haven't confirmed if varied tag context/positioning changes behavior) the email notification seems to only be sent to ~~the first~~ one user tagged.

**Steps to Reproduce**
1. Create a thread
2. Compose a reply with multiple users tagged at the beginning of the message
3. Observe mail is only sent to ~~the first~~ one user tagged

**Expected Behavior**
I would expect that all users would be notified simultaneously.

**Screenshots**
![image](https://user-images.githubusercontent.com/1117036/140422359-03c93854-fb70-43ea-b200-cf7098ca11c9.png)

Mail gun only shows sending the first email, previous record was the registration email the day before.
![image](https://user-images.githubusercontent.com/1117036/140423124-a3d62680-9317-4f6c-9bcb-29d7ce6aafe0.png)

**Environment**
- Flarum version: 1.1.0
- Website URL: http://example.com
- Webserver: Caddy / PHP Docker Container
- Hosting environment: VPS
- PHP version: 8.0.26
- Browser: Chrome 95
```
Output of "php flarum info", run this in terminal in your Flarum directory.
php flarum info
Flarum core 1.1.0
PHP version: 7.4.18
MySQL version: 8.0.26
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, bcmath, gd, pcntl, pdo_mysql, sodium, zip, Zend OPcache
+----------------------+---------+--------+
| Flarum Extensions    |         |        |
+----------------------+---------+--------+
| ID                   | Version | Commit |
+----------------------+---------+--------+
| flarum-flags         | v1.1.0  |        |
| flarum-tags          | v1.1.0  |        |
| flarum-suspend       | v1.1.0  |        |
| flarum-subscriptions | v1.1.0  |        |
| flarum-sticky        | v1.1.0  |        |
| flarum-statistics    | v1.1.0  |        |
| flarum-nicknames     | v1.1.0  |        |
| flarum-mentions      | v1.1.0  |        |
| flarum-markdown      | v1.1.0  |        |
| flarum-lock          | v1.1.0  |        |
| flarum-likes         | v1.1.0  |        |
| flarum-lang-english  | v1.1.0  |        |
| flarum-bbcode        | v1.1.0  |        |
| flarum-approval      | v1.1.0  |        |
+----------------------+---------+--------+
Base URL: https://rainshadowwa.com
Installation path: /var/www/app
Queue driver: sync
Mail driver: smtp
Debug mode: off
```

**Possible Solution**
N/A

**Additional Context**
N/A

**Comment by matteocontrini** [comment] 2021-11-05 18:22
I've just reproduced the issue on my forum (1.0). I wrote two mentions in the message, and only the *second* one received a notification. The first one did not receive anything, not even in the notifications panel, although all notifications are enabled in the settings.

**Comment by IronSinew** [comment] 2021-11-05 18:28
> I've just reproduced the issue on my forum (1.0). I wrote two mentions in the message, and only the _second_ one received a notification. The first one did not receive anything, not even in the notifications panel, although all notifications are enabled in the settings.

I didn't do extensive testing on this, so I presume it was only the first. I edited my initial submission to declare only a single user is mailed since it seems to be inconsistent in relation to tag order.

I initially wondered if it had to do with the primary id ordering or something of that nature, but the one user that was notified in my scenario was neither the newest nor oldest user tagged.

**Comment by SychO9** [comment] 2021-11-05 19:48
Does this only concern emails or notifications in general (alerts & emails). And are you 100% certain that the other users that didn't receive emails have email notifications turned on for user mentions ?

**Comment by matteocontrini** [comment] 2021-11-05 19:50
> Does this only concern emails or notifications in general (alerts & emails). And are you 100% certain that the other users that didn't receive emails have email notifications turned on for user mentions ?

In my case: no notification in general, and all types of notifications were enabled, both web and email. (I could provide screenshots but they wouldn't be very useful, probably...)

**Comment by IronSinew** [comment] 2021-11-05 20:32
After poking around the `flarum.users` table, it seems as though the only user that was notified is one that the preferences isn't set to null. I presume that there is no default user preferences, so maybe that's why some users aren't notified?

**Comment by SychO9** [comment] 2021-11-05 20:45
> I presume that there is no default user preferences, so maybe that's why some users aren't notified?

The default for mentions is alerts ON, emails OFF, so there are no issues in your case, just normal behavior, your users can turn on email notifications if they want in their notification preferences.

As for @matteocontrini's case, I can't reproduce the issue locally, I'd check with multiple users, there might very well be a reason why a user isn't getting notified, could also be an extension modifying the process.

I'll close this for now, please feel free to post a new issue if additional info is available.

**Closed by SychO9** 2021-11-05 20:45 UTC
Labels: needs-verification
