### ISSUE TITLE
Arabic search return no results

### ISSUE THREAD

**Issue by samymassoud** [flarum/core#443] opened 2015-09-07 08:03 UTC
No results come back from Arabic search, even if the keywords exist.
I think it's some thing related to `urldecode`

**Comment by askvortsov1** [comment] 2020-06-01 01:12
Duplicate of https://github.com/flarum/core/issues/2003, but I'm going to close this one since the other one has more discussion.

**Closed by askvortsov1** 2020-06-01 01:12 UTC
Labels: type/bug
