### ISSUE TITLE
Console binary flarum no longer works

### ISSUE THREAD

**Issue by luceos** [flarum/core#1370] opened 2018-02-15 09:01 UTC
When you create a clean install of the current dev-master of flarum/flarum using all packages on `dev-master as 0.1`, the flarum binary no longer works. It tries to resolve the database connection even though no config.php exists.

Please understand the web wizard is intact!

```
 ~/packages/flarum-b8  php flarum help install
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\Database\Connectors\ConnectionFactory::make() must be of the type array, null given, called in /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Database/DatabaseServiceProvider.php on line 28 and defined in /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/database/Connectors/ConnectionFactory.php:43
Stack trace:
#0 /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Database/DatabaseServiceProvider.php(28): Illuminate\Database\Connectors\ConnectionFactory->make(NULL)
#1 /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php(749): Flarum\Database\DatabaseServiceProvider->Flarum\Database\{closure}(Object(Flarum\Foundation\Application), Array)
#2 /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php(586): Illuminate\Containe in /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/database/Connectors/ConnectionFactory.php on line 43

Fatal error: Uncaught TypeError: Argument 1 passed to Illuminate\Database\Connectors\ConnectionFactory::make() must be of the type array, null given, called in /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Database/DatabaseServiceProvider.php on line 28 and defined in /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/database/Connectors/ConnectionFactory.php on line 43

TypeError: Argument 1 passed to Illuminate\Database\Connectors\ConnectionFactory::make() must be of the type array, null given, called in /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Database/DatabaseServiceProvider.php on line 28 in /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/database/Connectors/ConnectionFactory.php on line 43

Call Stack:
    0.0004     355680   1. {main}() /Users/danielklabbers/packages/flarum-b8/flarum:0
    0.0571    2087752   2. Flarum\Console\Server->listen() /Users/danielklabbers/packages/flarum-b8/flarum:20
    0.0571    2087752   3. Flarum\Console\Server->getConsoleApplication() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Console/Server.php:45
    0.0937    3205784   4. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Console/Server.php:76
    0.0937    3205784   5. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Foundation/Application.php:515
    0.0937    3205784   6. Flarum\Foundation\Application->resolve() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:586
    0.0937    3205784   7. Flarum\Foundation\Application->build() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:631
    0.0941    3216744   8. Flarum\Foundation\Application->resolveDependencies() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:780
    0.0948    3261664   9. Flarum\Foundation\Application->resolveClass() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:813
    0.0948    3261664  10. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:885
    0.0948    3261664  11. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Foundation/Application.php:515
    0.0948    3261664  12. Flarum\Foundation\Application->resolve() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:586
    0.0949    3261664  13. Flarum\Foundation\Application->build() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:631
    0.0949    3262960  14. Flarum\Foundation\Application->resolveDependencies() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:780
    0.0952    3264816  15. Flarum\Foundation\Application->resolveClass() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:813
    0.0952    3264816  16. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:885
    0.0952    3264816  17. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Foundation/Application.php:515
    0.0952    3264816  18. Flarum\Foundation\Application->resolve() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:586
    0.0952    3264816  19. Flarum\Foundation\Application->build() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:631
    0.0952    3264816  20. Flarum\Settings\SettingsServiceProvider->Flarum\Settings\{closure}() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:749
    0.0960    3278616  21. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Settings/SettingsServiceProvider.php:26
    0.0960    3278616  22. Flarum\Foundation\Application->make() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Foundation/Application.php:515
    0.0960    3278616  23. Flarum\Foundation\Application->resolve() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:586
    0.0960    3278616  24. Flarum\Foundation\Application->build() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:631
    0.0960    3278616  25. Flarum\Database\DatabaseServiceProvider->Flarum\Database\{closure}() /Users/danielklabbers/packages/flarum-b8/vendor/illuminate/container/Container.php:749
    0.0966    3312984  26. Illuminate\Database\Connectors\ConnectionFactory->make() /Users/danielklabbers/packages/flarum-b8/vendor/flarum/core/src/Database/DatabaseServiceProvider.php:28
```

**Comment by franzliedke** [comment] 2018-02-15 14:09
I remember having worked on fixing this, it has to do with the `SettingsRepositoryInterface` always being bound to a (cache-decorated) `DatabaseSettingsRepository`. I am thinking the correct way to fix this would be to bind a different instance during installation - one that does not touch the database.

Now to find out where exactly the settings repository is being resolved here...

**Comment by ZapTechAdmin** [comment] 2018-03-08 22:16
Has there been any updates on this? Just tried installing dev-master and I can't get it to work. With debug mode on, this is the error I get:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'discussions.id' in 'where clause' (SQL: (select `fl208_discussions`.* from `fl208_discussions` where not exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id) and (`fl208_discussions`.`is_private` = 0 or (`fl208_discussions`.`is_approved` = 0 and (`start_user_id` = 0 or (exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id))))) and (`fl208_discussions`.`hide_time` is null or `start_user_id` = 0 or (exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id))) and (`comments_count` > 0 or `start_user_id` = 0 or (exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id))) and not exists (select 1 from `fl208_users_discussions` where discussions.id = discussion_id and `user_id` = 0 and `subscription` = ignore) and not exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id) order by `last_time` desc limit 21) union (select `fl208_discussions`.* from `fl208_discussions` where not exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id) and (`fl208_discussions`.`is_private` = 0 or (`fl208_discussions`.`is_approved` = 0 and (`start_user_id` = 0 or (exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id))))) and (`fl208_discussions`.`hide_time` is null or `start_user_id` = 0 or (exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = discussion_id))) and (`comments_count` > 0 or `start_user_id` = 0 or (exists (select 1 from `fl208_discussions_tags` where 0 = 1 and discussions.id = ```

It looks like the installer never even wrote the data to the database.... is there a way that I can import a database, and make it work?

**Comment by datitisev** [comment] 2018-05-14 21:14
I think this has been fixed...?

![image](https://user-images.githubusercontent.com/6401250/40023814-3fa9a400-579a-11e8-8bbd-5d53fd31b738.png)

**Comment by franzliedke** [comment] 2018-05-14 21:15
Hotfixed, yes. But not yet the root cause.

**Comment by tobscure** [comment] 2018-07-19 00:05
@franzliedke was the "root cause" fixed in 
https://github.com/flarum/core/commit/6315e9ec31387dbe1442199c215fb8b119b843c5 ? Can this be closed?

**Comment by franzliedke** [comment] 2018-07-19 10:40
Yes, that branch contains the fix, but it needs to be cleaned up and merged.

**Closed** 2018-08-24 08:51 UTC
Labels: type/bug
