### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by viruxe** [flarum/core#694] opened 2015-12-27 10:33 UTC
OK so I've registeres myself on your forum trough the Facebook register option and when I try to change my profile description it asks me for my password. I don't remember setting any but I try to reset it anyway and every I open the link provided in the email and submit the new password I get  500 error.

**Comment by franzliedke** [comment] 2015-12-27 14:04
This is a duplicate of #674, but thanks for reporting it! :)

**Closed by franzliedke** 2015-12-27 14:04 UTC
