### ISSUE TITLE
Table Prefix when Installing is too Long

### ISSUE THREAD

**Issue by PartialDevAdmin** [flarum/core#1410] opened 2018-04-22 00:10 UTC
## Explanation

When trying to install Flarum, I encountered the following eror:
`Something went wrong: validation.alpha_dash validation.max.string`

## How it was Resolved

I resolved this issue by changing the length of my SQL Table Prefix.

## What Needs Improved

Either the error message declaration is incorrect, or there is no error message. Possibly one could be added?

## Technical details

- Version of Flarum: 0.1.0-beta7.1
- Website URL where the bug is visible: N/A Local Development Server
- Current Websever: apache

## PHP Info
```
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 7.0.28-0ubuntu0.16.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, interbase, intl, json, ldap, exif, mcrypt, mysqli, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, recode, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://dev.flarum2
Installation path: /var/www/flarum2
```

**Comment by franzliedke** [comment] 2018-04-23 06:55
Thanks for the report. I am closing this as a duplicate of #1212.

**Closed by franzliedke** 2018-04-23 06:55 UTC
