### ISSUE TITLE
Exposes database passwords without logging to a file

### ISSUE THREAD

**Issue by awknode** [flarum/core#2486] opened 2020-12-04 19:10 UTC
## Bug Report

**Current Behavior**
The PDO processes way too much error information. It strictly says that you guys process it the way you do so you don't show out our credentials, but it's false. You're exposing our database name and password, and even networking path/container name.

**Steps to Reproduce**
1. Go to 'make the database fail'
2. Click on 'just make the database fail and load the forum, you'll see credentials'

**Expected Behavior**
We should be writing to an error log file which I've done here:

https://github.com/flarum/core/blob/master/src/Http/Server.php#L48

Modify the server.php in the Http core for this kind of code so it can log to a file and not print out the username, database name, password, etc. I had to shell into docker and get help on this but we were able to find it in 30 minutes and I wrote the code in 2 minutes!

```
    private function safelyBootAndGetHandler()
    {
        try {
            return $this->site->bootApp()->getRequestHandler();
        } catch (Throwable $e) {
            error_log($this->formatBootException($e), 3, "/var/tmp/my-errors.log");
            echo("Database is currently not available. See logs for more details.");
            exit(1);
        }
    }
```
it works, please utilize.

**Comment by askvortsov1** [comment] 2020-12-04 19:17
Thank you very much! I'm going to close this issue as a duplicate of https://github.com/flarum/core/issues/2290, but I would definitely like to follow up there.

**Closed by askvortsov1** 2020-12-04 19:17 UTC
