### ISSUE TITLE
Sendgrid SMTP Issues

### ISSUE THREAD

**Issue by Xandarius** [flarum/core#1301] opened 2017-12-05 14:13 UTC
> Issues on Github are meant for bug reporting. Please post feature requests on the [discussion forum](https://discuss.flarum.org/t/features).
---
> Try to complete the below form as far as you are able and are willing to share. Add a screenshot of the issue if you can.

## Explanation

Using sendgrid to email does not work and results in a [RouteNotFound](https://pastebin.com/GRH1se2e) and a [MethodNotFound](https://pastebin.com/Fv4tqYqh) exception potentially. Password reset is slow likely due to these issues and accounts error out but are logged to the database thus preventing the email from being sent because the email is already registered but no email was sent. In addition luceos reported getting a 500 error after attempting to use reset password.

## Technical details

- Version of Flarum:  0.1.0-beta.7
- Website URL where the bug is visible: https://forums.convergence.ga
- The webserver you are running: apache
- PHP version: 5.6.30-0+deb8u1
- Hosted environment: shared vps instance
- Hosting provider: https://cloud.google.com/

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 5.6.30-0+deb8u1
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, pcntl, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, PDO, curl, gd, json, mcrypt, mysql, mysqli, pdo_mysql, readline, mhash, Zend OPcache
EXT flarum-akismet v0.1.0-beta.6
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flagrow-bazaar 0.2.4
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: https://forums.convergence.ga
Installation path: /var/www/forums
```

## Log files

See [RouteNotFound](https://pastebin.com/GRH1se2e) and a [MethodNotFound](https://pastebin.com/Fv4tqYqh) 

```
[2017-12-05 02:54:41] production.DEBUG: exception 'Flarum\Http\Exception\RouteNotFoundException' in /var/www/forums/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:62
Stack trace:
#0 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\DispatchRoute->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#1 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\DispatchRoute), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#2 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#3 /var/www/forums/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#4 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\SetLocale->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#5 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\SetLocale), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#6 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#7 /var/www/forums/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(36): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#8 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\AuthenticateWithSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#9 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\AuthenticateWithSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#10 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#11 /var/www/forums/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(39): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#12 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\RememberFromCookie->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#13 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\RememberFromCookie), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#14 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#15 /var/www/forums/vendor/flarum/core/src/Http/Middleware/StartSession.php(48): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#16 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\StartSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#17 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\StartSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#18 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#19 /var/www/forums/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(31): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#20 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\ParseJsonBody->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#21 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\ParseJsonBody), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#22 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#23 /var/www/forums/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(61): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#24 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\HandleErrors->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#25 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\HandleErrors), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#26 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#27 /var/www/forums/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(111): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#28 /var/www/forums/vendor/flarum/core/src/Http/AbstractServer.php(55): Zend\Stratigility\MiddlewarePipe->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Stratigility\NoopFinalHandler))
#29 /var/www/forums/vendor/zendframework/zend-diactoros/src/Server.php(157): Flarum\Http\AbstractServer->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Stratigility\NoopFinalHandler))
#30 /var/www/forums/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler))
#31 /var/www/forums/index.php(16): Flarum\Http\AbstractServer->listen()
#32 {main}

[2017-12-05 13:32:37] production.DEBUG: exception 'Flarum\Http\Exception\MethodNotAllowedException' in /var/www/forums/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:64
Stack trace:
#0 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\DispatchRoute->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#1 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\DispatchRoute), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#2 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#3 /var/www/forums/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#4 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\SetLocale->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#5 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\SetLocale), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#6 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#7 /var/www/forums/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(36): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#8 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\AuthenticateWithSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#9 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\AuthenticateWithSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#10 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#11 /var/www/forums/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(39): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#12 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\RememberFromCookie->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#13 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\RememberFromCookie), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#14 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#15 /var/www/forums/vendor/flarum/core/src/Http/Middleware/StartSession.php(48): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#16 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\StartSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#17 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\StartSession), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#18 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#19 /var/www/forums/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(31): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#20 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\ParseJsonBody->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#21 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\ParseJsonBody), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#22 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#23 /var/www/forums/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(61): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#24 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\Http\Middleware\HandleErrors->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#25 /var/www/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\Stratigility\Dispatch->dispatchCallableMiddleware(Object(Flarum\Http\Middleware\HandleErrors), Object(Zend\Stratigility\Next), Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#26 /var/www/forums/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#27 /var/www/forums/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(111): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#28 /var/www/forums/vendor/flarum/core/src/Http/AbstractServer.php(55): Zend\Stratigility\MiddlewarePipe->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Stratigility\NoopFinalHandler))
#29 /var/www/forums/vendor/zendframework/zend-diactoros/src/Server.php(157): Flarum\Http\AbstractServer->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Zend\Stratigility\NoopFinalHandler))
#30 /var/www/forums/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler))
#31 /var/www/forums/index.php(16): Flarum\Http\AbstractServer->listen()
#32 {main}
```

**Comment by tkduman** [comment] 2017-12-13 08:17
Hi! I'm using sendgrid too but it works just fine. Here's my configuration.

![](https://i.imgur.com/7u6Td8M.png)

I hope it helps. (Username is literally **apikey** not your username)

**Comment by Xandarius** [comment] 2017-12-13 12:01
That's not the issue as I have done exactly that. There seems to be some other issue which Luceos and I could not hash out. On another note I use my own MX records and server for email now so i am no longer using sendgrid, though fixing the issue related to sendgrid still remains unknown.

**Comment by luceos** [comment] 2017-12-13 13:59
@Xandarius your google instance seems to be misconfigured in handling patch or put or something. I'm not too sure. I think the issue is not so much sendgrid, but more about handling http methods.. Unless you didn't change a thing and it now works without sendgrid.

**Comment by Xandarius** [comment] 2017-12-13 14:40
All I did when I switched is just used gmail again but linked my domain
with it to use noreply@mydomain.com Works too

**Comment by franzliedke** [comment] 2017-12-13 21:19
Unless we find a way to reliably reproduce this, I'm afraid we'll have to close this issue. :confused:

**Comment by tobscure** [comment] 2017-12-13 22:37
I'm sceptical that the errors in the log file and Sendgrid are even related...

**Comment by luceos** [comment] 2017-12-13 22:42
@tobscure same fears I hate.

Following @franzliedke 

Please provide "steps to reproduce".

**Closed by luceos** 2017-12-13 22:42 UTC
Labels: Bug, Needs Verification
