### ISSUE TITLE
Whoops! There was an error when i loggout

### ISSUE THREAD

**Issue by EliBing** [flarum/core#751] opened 2016-01-18 11:54 UTC
Nginx + php 7

Flarum\Http\Exception\TokenMismatchException thrown with message ""
```
Stacktrace:
#29 Flarum\Http\Exception\TokenMismatchException in /workspace/FORUM/vendor/flarum/core/src/Forum/Controller/LogOutController.php:75
#28 Flarum\Forum\Controller\LogOutController:handle in /workspace/FORUM/vendor/flarum/core/src/Http/GenerateRouteHandlerTrait.php:35
#27 Flarum\Forum\ForumServiceProvider:Flarum\Http\{closure} in /workspace/FORUM/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:72
#26 Flarum\Http\Middleware\DispatchRoute:__invoke in <#unknown>:0
#25 call_user_func in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Dispatch.php:81
#24 Zend\Stratigility\Dispatch:__invoke in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Next.php:113
#23 Zend\Stratigility\Next:__invoke in /workspace/FORUM/vendor/flarum/core/src/Http/Middleware/SetLocale.php:50
#22 Flarum\Http\Middleware\SetLocale:__invoke in <#unknown>:0
#21 call_user_func in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Dispatch.php:81
#20 Zend\Stratigility\Dispatch:__invoke in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Next.php:113
#19 Zend\Stratigility\Next:__invoke in /workspace/FORUM/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php:33
#18 Flarum\Http\Middleware\AuthenticateWithSession:__invoke in <#unknown>:0
#17 call_user_func in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Dispatch.php:81
#16 Zend\Stratigility\Dispatch:__invoke in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Next.php:113
#15 Zend\Stratigility\Next:__invoke in /workspace/FORUM/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php:38
#14 Flarum\Http\Middleware\RememberFromCookie:__invoke in <#unknown>:0
#13 call_user_func in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Dispatch.php:81
#12 Zend\Stratigility\Dispatch:__invoke in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Next.php:113
#11 Zend\Stratigility\Next:__invoke in /workspace/FORUM/vendor/flarum/core/src/Http/Middleware/StartSession.php:33
#10 Flarum\Http\Middleware\StartSession:__invoke in <#unknown>:0
#9 call_user_func in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Dispatch.php:81
#8 Zend\Stratigility\Dispatch:__invoke in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Next.php:113
#7 Zend\Stratigility\Next:__invoke in /workspace/FORUM/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php:30
#6 Flarum\Http\Middleware\ParseJsonBody:__invoke in <#unknown>:0
#5 call_user_func in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Dispatch.php:81
#4 Zend\Stratigility\Dispatch:__invoke in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/Next.php:113
#3 Zend\Stratigility\Next:__invoke in /workspace/FORUM/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:75
#2 Zend\Stratigility\MiddlewarePipe:__invoke in /workspace/FORUM/vendor/zendframework/zend-diactoros/src/Server.php:166
#1 Zend\Diactoros\Server:listen in /workspace/FORUM/vendor/flarum/core/src/Http/AbstractServer.php:38
#0 Flarum\Http\AbstractServer:listen in /workspace/FORUM/index.php:16
```

**Comment by pescu25** [comment] 2016-01-18 13:14
when did the error throw?

**Comment by Luceos** [comment] 2016-01-19 12:11
Please elaborate the issue, an issue for php 7 compatibility already [exists](https://github.com/flarum/core/issues/685). So please explain the exact situation for this to happen, closing until you provide more information @EliBing

**Closed by Luceos** 2016-01-19 12:11 UTC

**Comment by fdelapena** [comment] 2016-06-11 19:27
Same issues here in this thread, both 5.6 and 7.0.x with 0.1.0-beta5: https://discuss.flarum.org/d/2872-big-problems/3

No idea what did this issue. Tweaked some admin preferences and customized a bit of css, adjusted some permissions and added other admin staff. All forum users are getting the csrf_token check failure, even after cleaning storage/cache, restarting httpd/php-fpm and cleaning all domain prefs/cookies in the browser. Logging out was working properly even after importing a phpbb forum, so seems unrelated with any data import.

**Comment by fdelapena** [comment] 2016-06-12 01:28
Update: I've checked php logs and php-fpm user was unable to write to `/var/lib/php/session`, so not a bug. After changing folder permissions the issue is gone. Affected people: check your php-fpm user/group and session directory to make sure it is writable.

**Comment by Luceos** [comment] 2016-06-20 17:33
@fdelapena thanks for delving deeper into this issue!

**Comment by EliBing** [comment] 2016-07-05 05:58
thanks,it's my fault
