### ISSUE TITLE
Unable to log in via KeePassX autotype

### ISSUE THREAD

**Issue by flabdablet** [flarum/core#467] opened 2015-09-12 08:51 UTC
There is something funky in the Flarum login form that stops it accepting auto-type from KeePassX.

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.2.0
OS: Debian Jessie
KeePassX: 0.4.3

To reproduce:

Create a KeePassX site entry for Flarum, with a valid Flarum username and password, and the URL http://discuss.flarum.org/

In KeePassX, double-click the URL of the Flarum entry and wait for the browser to open the Flarum main page.

Click Login. Verify that the insertion point is correctly positioned in an empty Username or Email box.

Bring the KeePassX window to the front again, and press Ctrl-V to make KeePassX auto-type username, Tab, password, Enter into the browser window.

Expected result: Login form appears to be filled in and Flarum logs on.

Actual result: White flicker at bottom of browser window, nothing appears in logon form text boxes, logon doesn't happen.

I have credentials for several hundred sites in my KeePassX database. Flarum is the only one that displays this behavior.

No repro on Chromium.

**Comment by franzliedke** [comment] 2015-09-12 10:45
Interesting, thanks for the report. We'll take a look... not the first issue with Firefox ;)

**Comment by flabdablet** [comment] 2015-09-13 19:31
No repro on Iceweasel 38.0.1

**Comment by Onyx47** [comment] 2015-09-13 20:38
Can repro on Opera 31.0 (running whatever is the version of WebKit running in Chrome 44) using the chromeIPass extension. Not sure if it's using the autotype mechanism as described by @flabdablet, but seems like a similar behaviour.

Do note that any values I enter into the fields seem to remain there after a failed login. Based on that it would seem like all input produced by autotype / chromeIPass gets ignored on submission.

Browser UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36 OPR/31.0.1889.174
OS: Debian Jessie
KeePass: 2.30
chromeIPass: 2.6.8
KeePassHttp: 1.8.4.0

**Comment by Mecvak** [comment] 2015-09-16 01:37
Hmm.. I cannot reproduce on Firefox 40.0.3 - Linux Mint (Ubuntu based) 17.2 keepassx 0.4.3

![](http://i.imgur.com/N8I4fpL.gif)

**Comment by tobscure** [comment] 2016-02-22 10:54
Most likely fixed in #811

**Closed by tobscure** 2016-02-22 10:54 UTC
Labels: Bug
