### ISSUE TITLE
Validation error on login

### ISSUE THREAD

**Issue by katosdev** [flarum/core#2190] opened 2020-06-05 21:23 UTC
## Bug Report

**Current Behavior**
When logging in with invalid characters for the username, the returned error is as follows:
```
"status": "401",
      "code": "not_authenticated"
```
This should instead be as follows:
```
"status": "422",
      "code": "validation_error",
      "detail": "The username may only contain letters, numbers, and dashes.",
      "source": {
        "pointer": "/data/attributes/username"
```

This issue is **only** present on **login** and not on **register**. 

**Steps to Reproduce**
1. Click to login
2. In the username field, enter: `" or ""="` and then debug the result.
3. Observe "not_authenticated"

**Expected Behavior**
This should be the same as the current registration functionality, and should return as follows:
```
"status": "422",
      "code": "validation_error",
      "detail": "The username may only contain letters, numbers, and dashes.",
      "source": {
        "pointer": "/data/attributes/username"
```

**Environment**
- Flarum version: 0.1.0-beta.13
- Website URL: http://creatorswave.com
- Webserver: Apache
- Hosting environment: Ubuntu vps
- PHP version: 7.4.6
- Browser: Chrome, also replicated on Microsoft Edge.

**Comment by katosdev** [comment] 2020-06-05 21:27
Screenshot of returned status on login:
https://i.imgur.com/EbKbCDE.png

Screenshot of returned status on register:
https://i.imgur.com/RxbnLQ3.png

**Comment by katosdev** [comment] 2020-06-05 21:37
It has also been noted in Discord that the login does not work for an account that contains "invalid characters" but that exist in the database.
For example, if a user such as `william's account` is imported, then this user tries to login, the "not_authenticated" error is thrown.

**Comment by askvortsov1** [comment] 2020-06-05 21:53
Personally I don't think a Validator should be run on login at all, not really sure what the benefit of that would be, if nothing is getting modified

**Comment by datitisev** [comment] 2020-06-05 23:14
The problem here is more of logging in to an account with invalid characters more than validation.  After discussing this internally, we agreed that the current validator behavior is fine (i.e. no validation of the fields like in register when logging in) - the problem is more of what is described in https://github.com/flarum/core/issues/2190#issuecomment-639835034.

**Comment by clarkwinkelmann** [comment] 2020-06-08 01:30
> @katosdev For example, if a user such as william's account is imported, then this user tries to login, the "not_authenticated" error is thrown.

Are you sure about that? I just tested locally with that exact username and it's working fine.

With the current implementation, anything that's not an email is directly compared against the `username` column of the database with `WHERE username = identification` https://github.com/flarum/core/blob/d492579638fb52dafbfe65f1f36a95eb6047f7f3/src/User/UserRepository.php#L49

So except possible encoding issue during the request, any username that fits in the database should be usable during login.

**Comment by clarkwinkelmann** [comment] 2020-07-11 18:57
I think we came to the agreement this was entirely intended behavior so I'm going to close this.

Anyone feel free to reopen if you think we need to discuss it further.

**Closed by clarkwinkelmann** 2020-07-11 18:57 UTC
