### ISSUE TITLE
Topics length is too long

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#212] opened 2015-08-03 15:25 UTC
Topics length should be reduced. Amount of tags per topic should also be reduced (maximum of three, perhaps)? [Relevant](http://discuss.flarum.org/d/447/the-title-of-this-post-will-be-as-long-as-allowed-by-the-system-to-see-how-far-i-can-go-with-it-so-far-i-see-it-scroll-out-of-my-typing-window-so-it-is-very-long-but-i-will-make-it-even-longer-ju/1).

**Comment by tobscure** [comment] 2015-08-07 04:56
Duplicate of #53

**Closed by tobscure** 2015-08-07 04:56 UTC
