### ISSUE TITLE
beta.5 new bug : Unconfirmed user gets a blank screen

### ISSUE THREAD

**Issue by Averell7** [flarum/core#914] opened 2016-04-04 11:09 UTC
Tested on two different installations :

A new user signs up. 
Internal process is OK and a mail is sent, but instead of the message indicating he will receive this mail, he gets a blank screen. And each time he will try to open Flarum, he will get blank screen until he confirms. Once he confirms, everything is normal again. 

How to verify the bug : 

The simplest way is : set is_activated to 0 in the database to a working user record, and then try to connect with this account : You get a blank screen. No message, just the header. 

This didn't happen in beta.4

**Comment by tobscure** [comment] 2016-04-04 11:31
Having trouble reproducing this. When you see the blank screen, are there any errors in the JavaScript console of your browser?

**Comment by Averell7** [comment] 2016-04-04 13:19
If you cannot reproduce, then the problem is on my side. I will investigate and keep you informed. Thanks.

**Comment by Averell7** [comment] 2016-04-04 14:51
Oh ! But it may be just that : the old bug coming back because the extension was uninstalled and reinstalled, but not from dev.  But I don't remember which extension it was. I disabled all my extensions and it didn't solve the problem.  Probably I should uninstall, but I don't have time today to investigate.

**Comment by Luceos** [comment] 2016-04-05 04:49
hyn/guardian is not updated for beta 6+. Please remove it from your Flarum installation.

**Comment by Averell7** [comment] 2016-04-05 09:06
I removed all extensions, deleted files in assets, views, cache. No result.

**Comment by datitisev** [comment] 2016-04-06 11:41
@Averell7 
You removed the files in views?
Those are the files for the markup, if not, Flarum renders 0 HTML, therefore nothing comes up on screen.
:|

(I think, sorry if I got this wrong)

**Comment by Averell7** [comment] 2016-04-06 12:11
I mean : storage/views. These files are generated, and when you delete them, the system builds them again. But thanks for your interest in this strange question.

**Comment by datitisev** [comment] 2016-04-06 12:15
I have actually gotten this issue when trying to use Flarum's Mithrill front-end in FlarumJS!!!
If I remember correctly, the problem was that there was data missing in the `System.boot()` function or so, where the second parameter is an object of info for the whole forum!
Something must be missing there.ll
Can you show us the script when your forum loads at the bottom of the page?
Thanks.

**Comment by Averell7** [comment] 2016-04-06 16:55
New test : 

* Brand new installation of Flarum. 
* I copy my config.php file to connect to the existing database. 
* I try to connect with the non yet activated test login
* And I get a blank screen (just the title). 

In addition : If I give this user the administation permissions, then when I connect, I get the normal screen, with the additional yellow banner : Resend confirmation email.

**Comment by Averell7** [comment] 2016-04-06 17:44
I found the reason of the bug. 
In permissions, set "View discussions" to "members" and the bug appears. 
Set it to "everyone" and the bug disappears. 
This was tested on a brand new installation of flarum, and on old installs as well. All had the same behaviour. 

Please @datitisev  could you try with "View discussions" to "members" ? 

Trying means only : create a new user, don't send the confirmation, and see what happens when you try to connect. Thanks.

**Comment by datitisev** [comment] 2016-04-06 17:56
@Averell7 Yep, just reproduced on http://devflarum.xyzz.work

And it only happens when you sign up and don't have confirmed email... weird!

**Comment by Averell7** [comment] 2016-04-06 18:37
Thanks @datitisev 

Hello @tobscure , the bug is now confirmed. 
What next ? I don't have the skills to fix it.

**Comment by Averell7** [comment] 2016-04-06 18:43
> @datitisev And I can't log out now, because there is only a blank screen :neutral_face:

Try to connect in a private window (in Firefox) or something equivalent, and connection will be possible.

**Comment by datitisev** [comment] 2016-04-06 18:47
> @Averell7 Try to connect in a private window (in Firefox) or something equivalent, and connection will be possible.

I know, but for the average user, it will not be a nice experience :wink:

**Comment by Averell7** [comment] 2016-04-06 19:06
@datitisev  Could you, please, help me to confirm another very strange bug (totally different). 

I am following your discussion : Emoji Extension

Could you just post a message there with the following content : 

    toto

This means : four spaces, and then the word toto
The four spaces are important. 
If you follow this discussion, I will do the same, and you will tell me what you receive. Thanks.

**Comment by datitisev** [comment] 2016-04-06 20:32
@Averell7 Ok, I did not post this on _Emoji Extension_ but on a Sandbox (https://discuss.flarum.org/d/2451-lol).
No problem appears for me, and it has four spaces.
Were are you running Flarum?
Does it work for you in [DevFlarum.XYZZ.work](http://devflarum.xyzz.work)?

**Comment by Averell7** [comment] 2016-04-07 01:00
I cannot test in DevFlarum.XYZZ.work because I don't receive any message from there. I tried to register, but the confirmation email does not arrive. Probably mail is not configured, and it may be intentional.

**Comment by Averell7** [comment] 2016-04-08 03:00
After investigation : (View discussions set to members, and user unconfirmed)

With my system configuration, app.preload has a length of 9. The last item is null. 

It comes from the Babelhelper line in the code source of the page :+1: 
`babelHelpers.extends(app, {"preload":{"data":[{"type":"forums", ...`
In short, first item is "forum", next 7 items are "groups" and the last item of the array is null. 

I don't know where this line is built and cannot investigate further. 

With View discussion set to "everyone", I have 11 items. The first 8 items as above, then "tags", "discussions" and "users".

**Comment by franzliedke** [comment] 2016-04-08 03:04
That reminds me of a PHP 7 bug we once had. Does `/api/users/1` return something useful?

**Comment by jordanjay29** [comment] 2016-04-10 10:00
I tried this on a fresh Beta 5 and caught the same problem. Unconfirmed user with View Discussions set to the Admin group.

**Comment by Averell7** [comment] 2016-04-10 16:54
@franzliedke , sorry if I am unable to answer your question. I am using the debugger of Firefox and I don't know how to get "api". I program in Python and I am unfamiliar with js.

**Comment by datitisev** [comment] 2016-04-10 16:55
@Averell7 he means to perform an HTTP request.
You could use a request handler (complicated) or just go to http://yourForum.com/api/users/1

**Comment by jordanjay29** [comment] 2016-04-10 20:27
@franzliedke 

http://testbed.legendofdevira.com/flarum/api/users/1 (Also [2](http://testbed.legendofdevira.com/flarum/api/users/2) and [3](http://testbed.legendofdevira.com/flarum/api/users/3))

**Comment by datitisev** [comment] 2016-04-10 21:24
@jordanjay29 is that supposed to return anything?
To me it downloads a file saying
```
{"errors":[{"status":"404","code":"resource_not_found"}]}
```

And http://testbed.legendofdevira.com returns `Hello World!`
:/

**Comment by datitisev** [comment] 2016-04-10 21:27
I get blank screen for both. As if not verified...
This is the console error:
```js
[Error] TypeError: null is not an object (evaluating 'data.type')
	pushObject (forum-f22aef4d.js:29543)
	pushObject
	map
	pushPayload (forum-f22aef4d.js:29531)
	preload (forum-f22aef4d.js:28632)
	(función anónima) (forum-f22aef4d.js:18427)
	forEach
	boot (forum-f22aef4d.js:18426)
	global code (flarum:101)
```

And also, those links for the api download me a file with the content
```json
{"errors":[{"status":"404","code":"resource_not_found"}]}
```

**Comment by jordanjay29** [comment] 2016-04-10 21:37
@datitisev You're probably using Firefox. Firefox doesn't handle JSON files natively as rendered content. You'll have to use an extension to view the API in the browser, or use Chrome. 

And yes, it looks like the View Discussions permission creates this error whether or not the user is confirmed.

**Comment by Averell7** [comment] 2016-04-11 01:05
@jordanjay29 if you protect the line which provokes the error (29543) by adding before :+1: 
if (data == null)  return
Then you get the expected screen (user not logged in) but WITHOUT the yellow banner. 
I am quite sure that the problem comes from the code which added this yellow banner (asking to confirm), since it is a new feature of beta5. You should ask to the guy who designed this feature, he should have the clue. 

Technically speaking : the null value which provokes the error  comes from the last item of the preload array. This array is defined by the long babelHelper command in the source code of the page (line 86). The content of this command comes from line 40 of app.blade.php : 
`babelHelpers.extends(app, {!! json_encode($app) !!});`

And here I can go no further because I don't know where this $app variable comes from.

**Comment by jordanjay29** [comment] 2016-04-11 01:21
> And here I can go no further because I don't know where this $app variable comes from. 

It comes from the line above that. 

```
var app = System.get('flarum/app').default;
```

I believe that's referring to [this class](https://github.com/flarum/core/blob/37d7f315d31047bae5936198679579538a9b305a/src/Foundation/Application.php), if I'm not mistaken. Either that or the [JS class version](https://github.com/flarum/core/blob/37d7f315d31047bae5936198679579538a9b305a/js/lib/App.js). I don't have time at the moment to dive deep enough to find out.

**Comment by Averell7** [comment] 2016-04-11 10:10
> It comes from the line above that. 
As you can see, I am really null in js. I checked the links you indicate, but I will not be able to find the problem. I don't think I can do more. I will be content with the partial fix mentioned above :  

    if (data == null) return

and wait until specialists can fix it.

**Comment by Prechan** [comment] 2016-05-18 10:27
Any news about fixing this bug (next release ?)

**Comment by datitisev** [comment] 2016-05-18 11:10
@Prechan you can look for the milestone in the right of the issue.This issue is hopefully to be solved in beta6

**Comment by datitisev** [comment] 2016-07-24 16:41
Is this still a problem? If I signup on latest dev-master, no blank screen comes up, and it still doesn't come up when I refresh.

I think this may have been fixed.

**Comment by tobscure** [comment] 2016-08-27 14:32
Yeah, I can't reproduce, and I can't remember but I think I might've fixed something to do with this a while ago. Closing now, but if it happens again after beta 6 is released, please open a new issue!

**Closed by tobscure** 2016-08-27 14:32 UTC
Labels: Bug
