### ISSUE TITLE
Color thief doesn't work with non local avatars

### ISSUE THREAD

**Issue by luceos** [flarum/core#1766] opened 2019-03-25 15:06 UTC
## Bug Report

**Current Behavior**

When using avatars not locally stored, the color thief plugin errors out.

```
color-thief.min.js:18 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at n.getImageData (http://flarum.test/assets/forum-a37d55d8.js:57:546)
    at i.getPalette (http://flarum.test/assets/forum-a37d55d8.js:66:191)
    at i.getColor (http://flarum.test/assets/forum-a37d55d8.js:66:54)
    at Image.t.onload (http://flarum.test/assets/forum-a37d55d8.js:1:24994)
```

**Steps to Reproduce**
1. Set avatar to Toby's GitHub avatar, or something else
2. Go to profile
3. Check console. And background remains grey.

**Expected Behavior**

Background should change according to remote avatar color.

**Screenshots**

![image](https://user-images.githubusercontent.com/504687/54930631-e36e2780-4f17-11e9-8848-545ddd523a97.png)

**Environment**
- Flarum version: master

**Comment by tobscure** [comment] 2019-03-25 20:46
Duplicate of #445

**Closed by tobscure** 2019-03-25 20:46 UTC
Labels: type/bug
