### ISSUE TITLE
Stickies don't go away until it is acctually read

### ISSUE THREAD

**Issue by dav-is** [flarum/core#1003] opened 2016-07-19 13:28 UTC
You can mark it as read but it still stays at the top. Then you manually read all of it and it goes away (with a refresh)

**Comment by franzliedke** [comment] 2016-07-19 15:05
I don't get the issue title... the problem is that the sticky should drop down to it's time-based position once it is read - but it only does so when the discussion list is reloaded from the server.

Correct? But that's not what the title says...

**Comment by dav-is** [comment] 2016-07-19 15:15
That's one bug. The second is by clicking the `readNumber` button on the index it doesn't reset the stickies.

**Comment by franzliedke** [comment] 2016-07-19 15:17
Ah gotcha, thanks for explaining!

**Comment by dav-is** [comment] 2016-07-19 15:19
Just to be clear: refreshing after clicking the read number button doesn't reset the position.

**Comment by manuel-di-iorio** [comment] 2017-01-24 10:41
+1

**Comment by tobscure** [comment] 2017-03-05 02:48
I can't reproduce this on discuss.flarum.org, unless I'm misunderstanding:

![untitled](https://cloud.githubusercontent.com/assets/128862/23584076/32658ebc-01a6-11e7-9ecb-82d02a90c160.gif)

**Comment by franzliedke** [comment] 2017-03-06 12:46
@tobscure I believe it's about the sticky not dropping down to its natural position in the list once marked as read that way.

@dav-is Is my interpretation correct?

**Comment by dav-is** [comment] 2017-03-06 13:32
That is correct. @franzliedke

**Comment by franzliedke** [comment] 2017-03-06 15:01
@tobscure So basically it's up to you whether this behavior (and the one I described in my first reply) is worth fixing...

**Comment by Kakifrucht** [comment] 2017-03-06 15:24
I remember that a while ago after clicking the read bubble the thread stayed up there until you actually entered the thread. When was this issue fixed?

**Comment by tobscure** [comment] 2017-03-06 19:10
@Kakifrucht you may be thinking of threads which have been marked as read by clicking "mark all as read". I think we have an issue for this elsewhere?

I don't consider the behaviour in my GIF a bug, the UX would be a bit erratic if a topic were to jump to a random position in the list (off of the first page?) immediately as you mark it as read, not to mention the technical challenge of doing so. The position updates correctly after a refresh.

**Closed by tobscure** 2017-03-06 19:10 UTC
Labels: Bug, UX

**Comment by Kakifrucht** [comment] 2017-03-06 20:06
I'm not that sure anymore, but I thought the issue was the same as outlined by @dav-is, doesn't matter anymore though as that bug is gone.
