### ISSUE TITLE
Formatting shortcuts trigger browser response in Firefox

### ISSUE THREAD

**Issue by uamv** [flarum/core#3000] opened 2021-08-03 19:22 UTC
## Bug Report

**Current Behavior**
Attempting to format text via shortcut will not only apply formatting to the markdown editor, but will also trigger the browser response to that shortcut.

For example, `⌘+B` not only applies bold formatting, but also opens bookmarks. and `⌘+I` not only applies italic, but also opens page info.

**Steps to Reproduce**
1. Visit site in Firefox.
2. Open editor via compose or reply.
3. Click `⌘+B`.

**Expected Behavior**
When composing in a textarea, formatting shortcuts should not trigger browser actions for that shortcut.

**Environment**
- Flarum version: v1.0.3
- Browser: firefox 90.0.2 (64-bit) _(tested w/ all extensions disabled)_
- Operating System: MacOS Big Sur v11.5

```
Flarum core 1.0.3
PHP version: 7.4.21
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, dom, enchant, FFI, filter, gmp, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, readline, xml, xmlreader, xmlwriter, bcmath, bz2, calendar, ctype, curl, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imap, intl, json, exif, memcache, memcached, msgpack, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, pspell, redis, shmop, SimpleXML, soap, sockets, sodium, sqlite3, swoole, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlrpc, xsl, zip, Zend OPcache
+---------------------------------+---------+--------+
| Flarum Extensions               |         |        |
+---------------------------------+---------+--------+
| ID                              | Version | Commit |
+---------------------------------+---------+--------+
| flarum-flags                    | v1.0.0  |        |
| flarum-tags                     | v1.0.3  |        |
| flarum-lock                     | v1.0.0  |        |
| flarum-approval                 | v1.0.0  |        |
| flarum-suspend                  | v1.0.0  |        |
| flarum-subscriptions            | v1.0.0  |        |
| flarum-likes                    | v1.0.0  |        |
| v17development-blog             | v0.4.0  |        |
| v17development-support          | v2.3.2  |        |
| fof-user-directory              | 1.0.2   |        |
| fof-share-social                | 1.0.0   |        |
| clarkwinkelmann-post-bookmarks  | 1.0.0   |        |
| askvortsov-discussion-templates | v0.8.0  |        |
| maicol07-sso                    | 1.10.1  |        |
| flarum-bbcode                   | v1.0.0  |        |
| flarum-emoji                    | v1.0.0  |        |
| flarum-lang-english             | v1.0.0  |        |
| flarum-markdown                 | v1.0.1  |        |
| flarum-mentions                 | v1.0.0  |        |
| flarum-pusher                   | v1.0.0  |        |
| flarum-statistics               | v1.0.0  |        |
| flarum-sticky                   | v1.0.0  |        |
| fof-best-answer                 | 1.0.1   |        |
| fof-follow-tags                 | 1.0.1   |        |
| fof-formatting                  | 1.0.0   |        |
| fof-links                       | 1.0.0   |        |
| fof-nightmode                   | 1.0.0   |        |
| fof-polls                       | 1.0.3   |        |
| fof-split                       | 1.0.0   |        |
| fof-user-bio                    | 1.0.0   |        |
| sycho-profile-cover             | v1.3.0  |        |
| fof-upload                      | 1.0.1   |        |
| michaelbelgium-discussion-views | v7.0.0  |        |
| ianm-gravatar                   | 0.1.2   |        |
| fof-drafts                      | 1.0.1   |        |
| v17development-seo              | v1.8.0  |        |
| extiverse-mercury               | 0.1.3   |        |
+---------------------------------+---------+--------+
```

**Comment by Ralkage** [comment] 2021-08-07 05:28
I can confirm that the same issue exists on Firefox (90.0.2) for Windows (64-bit) (e.g. Ctrl+B); this issue seems specific to FF as I can't reproduce on Chrome or any Chromium-based browser at that.

**Comment by datitisev** [comment] 2021-08-07 13:09
We should still probs add `e.preventDefault()` when handling keyboard shortcuts

**Comment by datitisev** [comment] 2021-08-21 13:04
Should this be addressed in flarum/markdown in `makeShortcut` method?

For non-breaking that seems like the obvious place, but in the future we'd probably want to move that to core & prevent default if the handler returns true or something? :shrug

**Closed** 2021-09-20 22:06 UTC
Labels: type/bug
