### ISSUE TITLE
Better managing of missed languages

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1887] opened 2019-09-18 13:14 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**

I use Flarum in the Italian language. I suppose, you, developers use it on the native English language so i will try to help to find a possible issue.

If Flarum is updated with a new component like... the new button for image in markdow and the community language is not English... the issue is that Flarum is not showing the button description in the native English language. See this screenshot: 

![Inked65147718-012bcd80-da1f-11e9-8d2e-9cf0cd1c8f2b_LI](https://user-images.githubusercontent.com/5006150/65151368-46073280-da26-11e9-9689-59716ce4d3d1.jpg)

This issue present for extensions when they did not support the language because Italian language is done by an extension.

**Describe the solution you'd like**

I think when the language selected in the Flarum is not avaiable the English string should be showed.

For show you some issues and screenshot you can see here:

1. https://github.com/ReFlar/twofactor/issues/9 Since the extension doesn't support Italian and implement it take some times is not nice visitor see a technical string and not the English language.

2. https://github.com/FriendsOfFlarum/links/issues/12

Will be possible show the English description when the language is not available? This is my suggestion.

**Comment by datitisev** [comment] 2019-09-18 19:44
I think this is basically https://github.com/flarum/core/issues/1774.

**Comment by clarkwinkelmann** [comment] 2019-09-20 10:59
Yes it's a duplicate of #1774

**Closed by clarkwinkelmann** 2019-09-20 10:59 UTC

**Comment by PeopleInside** [comment] 2019-09-20 11:23
OK, sorry and thank you! ;)

**Comment by clarkwinkelmann** [comment] 2019-09-20 11:51
@PeopleInside no worries :wink:
