### ISSUE TITLE
[Tags] Discussions broken when a discussion is moved from a privileged to an unprivileged one, for members without all original tag permissions

### ISSUE THREAD

**Issue by AmauryCarrade** [flarum/core#1908] opened 2019-10-11 16:15 UTC
## Bug Report

**Current Behavior**

When we create a discussion in a restricted tag, then move this discussion to an unrestricted tag, users without the permission to access the restricted tag experiences a totally broken UI and cannot see anything past the last message before the move.

**Steps to Reproduce**
1. Have at least two tags: one unrestricted and one restricted to some groups.
2. Create a discussion under a restricted tag. You can also add some messages, it fails the same with or without answers after the first post.
3. Move the discussion to an unrestricted tag. You can also add some messages from a privileged account.
4. Log in with a standard account (or look at the discussion logged out, if the tag is public). You will see that the page is broken, and the messages stop just before the _move_ meta message.

Bonus: if you delete the _move_ meta message, the page works again for everyone.

**Expected Behavior**

The forum should display normally for everyone, including the private tag. I don't think being able to see the tag exist is a problem? If so, the administrator can always delete the message

**Screenshots**

You can see an example [on this forum](https://forum.zcraft.fr/d/7285-sujet-de-test), seen by a staff:

![image](https://user-images.githubusercontent.com/1417570/66666482-fac0f800-ec50-11e9-8972-73bdd8c8474b.png)

And by a normal user (here logged out but it's the same with a logged-in user without the permission).

![image](https://user-images.githubusercontent.com/1417570/66666519-11ffe580-ec51-11e9-916f-dec3afd7393b.png)

**Environment**
- Flarum version: 0.1.0-beta.10
- Website URL: https://forum.zcraft.fr
- Webserver: nginx 1.16.1
- Hosting environment: dedicated server (FreeBSD)
- PHP version: 7.3.10
- Browser: Firefox 70, also experienced on Firefox 69 and “other browsers” (unspecified by the bug's victim, I suspect Chrome).

```
$ php flarum info
Flarum core 0.1.0-beta.10
PHP version: 7.3.10
Loaded extensions: Core, date, libxml, pcre, Reflection, SPL, hash, session, standard, ctype, curl, dom, mbstring, fileinfo, filter, gd, mysqlnd, iconv, intl, json, exif, mysqli, openssl, PDO, posix, SimpleXML, sqlite3, tokenizer, xml, xmlwriter, yaml, zip, zlib, pdo_mysql, pdo_sqlite, Phar, xmlreader, Zend OPcache
+-------------------------------+----------------+--------+
| Flarum Extensions             |                |        |
+-------------------------------+----------------+--------+
| ID                            | Version        | Commit |
+-------------------------------+----------------+--------+
| flarum-approval               | v0.1.0-beta.8  |        |
| flarum-bbcode                 | v0.1.0-beta.8  |        |
| flarum-emoji                  | v0.1.0-beta.10 |        |
| flarum-flags                  | v0.1.0-beta.9  |        |
| flarum-likes                  | v0.1.0-beta.9  |        |
| flarum-lock                   | v0.1.0-beta.9  |        |
| flarum-markdown               | v0.1.0-beta.10 |        |
| flarum-mentions               | v0.1.0-beta.10 |        |
| flarum-sticky                 | v0.1.0-beta.9  |        |
| flarum-subscriptions          | v0.1.0-beta.9  |        |
| flarum-suspend                | v0.1.0-beta.9  |        |
| flarum-tags                   | v0.1.0-beta.10 |        |
| flarum-lang-english           | v0.1.0-beta.10 |        |
| flarum-statistics             | v0.1.0-beta.9  |        |
| extiverse-bazaar              | 0.4.0          |        |
| fof-user-bio                  | 0.1.3          |        |
| milescellar-lang-french       | v1.4.1         |        |
| rooaaar-lang-french-extended  | v1.13.0        |        |
| fof-split                     | 0.4.3          |        |
| amaurycarrade-syndication     | v0.2.0         |        |
| fof-merge-discussions         | 0.3.3          |        |
| flagrow-upload                | 0.7.1          |        |
| fof-transliterator            | 0.2.0          |        |
| flagrow-direct-links          | 0.2.0          |        |
| fof-links                     | 0.2.1          |        |
| fof-formatting                | 0.1.2          |        |
| flagrow-sitemap               | 0.2.0          |        |
| fof-user-directory            | 0.3.3          |        |
| fof-spamblock                 | 0.2.1          |        |
| fof-socialprofile             | 0.1.1          |        |
| v17development-seo            | 1.0.2          |        |
| migratetoflarum-old-passwords | 0.4.0          |        |
| clarkwinkelmann-emojionearea  | 0.2.0          |        |
| zerosonesfun-bbbbcode         | 1.2            |        |
| fof-nightmode                 | 0.3.0          |        |
+-------------------------------+----------------+--------+
Base URL: https://forum.zcraft.fr
Installation path: /var/www/forum
Debug mode: off
```

**Possible Solution**

If we look at the developer console, we can see this is caused by the restricted tag failing to display on the _move_ status message due to an unknown tag for the user, or something like that.

```
TypeError: t is undefined in tagLabel.js:28:12
```

(You can test that by yourself, there's a link to a faulty discussion in the screenshots section above.)

**Additional notes**

This forum was migrated from an old FluxBB one (with 114k posts) but I don't think this can be related to this bug.

(Thanks a lot for the software btw, it is really appreciated!)

**Comment by datitisev** [comment] 2019-10-11 16:40
I made a PR to flarum/tags that fixes this, I think. On mobile rn so I can't link it.

Thanks for the detailed bug report though.

**Comment by matteocontrini** [comment] 2019-10-11 16:42
This one: https://github.com/flarum/tags/pull/66

**Comment by datitisev** [comment] 2019-10-11 20:12
Yeah, the error message is the same in both instances.

The tag data isn't passed if it doesn't exist or you don't have permission to view it, so it would show `[deleted]` in both instances.

Closing as my fix should solve this and kind of a duplicate of #1864.

**Closed by datitisev** 2019-10-11 20:12 UTC

**Comment by AmauryCarrade** [comment] 2019-10-11 23:18
Thanks you very much! I wasn't aware it was the same origin. Fixed even before I report the bug, what else can I ask?
