### ISSUE TITLE
Pusher extension only works partially

### ISSUE THREAD

**Issue by viruxe** [flarum/core#939] opened 2016-04-20 14:18 UTC
As per this discussion https://discuss.flarum.org/d/2558-need-help-in-using-pusher-with-flarum/40

Only the notifications under the bell are working.
Yellow bar doesn't show up and discussions aren't instantly updated with new posts if the user has a discussion tab open.

**Comment by The-F4m3** [comment] 2016-06-20 18:25
Problem detected in [ / src / Listener / PushNewPosts.php ](https://github.com/flarum/flarum-ext-pusher/blob/6c1bc2c3f0efa906e781efb91533a587a71d4d91/src/Listener/PushNewPosts.php)

`protected function getPusher()` does not return the Cluster so it just work with the Default (mt1(us-east-1) )

after adding `, ['cluster' => $this->settings->get('flarum-pusher.app_cluster')] ` it just works fine

**Comment by Kakifrucht** [comment] 2016-06-20 18:54
I can confirm that the problem is fixed with @The-F4m3's code.

**Comment by CDK2020** [comment] 2018-05-08 17:25
This is fixed in dev-master, can this issue be closed?

**Comment by luceos** [comment] 2018-05-08 17:31
@CDK2020 would you have linked to the commit I could do that faster 😇

**Comment by CDK2020** [comment] 2018-05-08 17:34
Oops

https://github.com/flarum/flarum-ext-pusher/commit/49dd13451aecb07983021b6c193ebdcc517760c5

**Comment by luceos** [comment] 2018-05-08 17:36
fixed in https://github.com/flarum/flarum-ext-pusher/commit/49dd13451aecb07983021b6c193ebdcc517760c5

thanks @CDK2020

**Closed by luceos** 2018-05-08 17:36 UTC
Labels: Bug, Core Extension

**Comment by NamVr** [comment] 2020-07-26 07:51
Is the app updated? Last night it didn't worked for me :(

**Comment by luceos** [comment] 2020-07-28 05:21
@NamVr that's not much to go on. Use the forums for initial support please.

**Comment by NamVr** [comment] 2020-07-28 05:42
I know. After reading all the chats, I am here.28.07.2020, 10:51, "Daniël Klabbers" <notifications@github.com>:
@NamVr that's not much to go on. Use the forums for initial support please.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
 --------------------------------------------------------------------------------- Let me know if we can help you further. We always try to provide customer superior service levels, quickly and accurate at the point. I hope I was able to address your query efficiently. NOTE: We are providing high-quality gaming servers for you at a discounted price during the lockdown. To avail the offer, please visit our website and compare plans. Regards,Naman VratiWordPress Freelancer and Cloud Management Engineer - Founder of Team ELITES Org.https://namanvrati.cf/

**Comment by askvortsov1** [comment] 2020-07-28 11:26
If you suspect that the issue is with pusher, please provide instructions to reproduce the issue, as well as verification of the issue happening if possible.

**Comment by NamVr** [comment] 2020-07-28 11:57
At the first time on testing, the forums were updating regularly.There was no issue. But after a month or so, pusher suddenly started not working and then, I just made a new beam in it and changed the credentials in flarum admin area.that worked but I wonder do I have to monthly change the credentials?28.07.2020, 16:57, "Alexander Skvortsov" <notifications@github.com>:
If you suspect that the issue is with pusher, please provide instructions to reproduce the issue, as well as verification of the issue happening if possible.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
 --------------------------------------------------------------------------------- Let me know if we can help you further. We always try to provide customer superior service levels, quickly and accurate at the point. I hope I was able to address your query efficiently. NOTE: We are providing high-quality gaming servers for you at a discounted price during the lockdown. To avail the offer, please visit our website and compare plans. Regards,Naman VratiWordPress Freelancer and Cloud Management Engineer - Founder of Team ELITES Org.https://namanvrati.cf/

**Comment by askvortsov1** [comment] 2020-07-28 12:01
That looks like an issue with pusher itself, not with this extension. I would recommend reaching out to them for support.

**Comment by NamVr** [comment] 2020-07-28 12:03
Okay :) I just changed the region from ap1 to ap2Nothing else let's see how long it will run good.28.07.2020, 17:32, "Alexander Skvortsov" <notifications@github.com>:
That looks like an issue with pusher itself, not with this extension. I would recommend reaching out to them for support.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
 --------------------------------------------------------------------------------- Let me know if we can help you further. We always try to provide customer superior service levels, quickly and accurate at the point. I hope I was able to address your query efficiently. NOTE: We are providing high-quality gaming servers for you at a discounted price during the lockdown. To avail the offer, please visit our website and compare plans. Regards,Naman VratiWordPress Freelancer and Cloud Management Engineer - Founder of Team ELITES Org.https://namanvrati.cf/
