### ISSUE TITLE
Scrollbar not showing accurate values

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1535] opened 2018-08-12 11:23 UTC
## Bug Report

**Current Behavior**
The scrollbar for scrolling through posts inside a discussion doesn't show accurate values if it's at top or bottom (while scrolling, after stopping, it will become normal, if you swipe up another time though)

**Steps to Reproduce**
1. Go to a discussion
2. Hold the scrollbar and scroll to the bottom or to the top
3. See error

**Expected Behavior**
The scrollbar should show accurate values (e.g. 96/96 instead of 94/96 as max)

**Screenshots**

![registrazione schermo 2018-08-12 alle 14 14 10](https://user-images.githubusercontent.com/17576065/44001444-01c26216-9e3b-11e8-87cc-6f9b47f923f3.gif) ![registrazione schermo 2018-08-12 alle 14 14 35](https://user-images.githubusercontent.com/17576065/44001446-02bf8e46-9e3b-11e8-8037-67b558954090.gif)

**Environment**
Flarum Community
https://discuss.flarum.org

**Comment by ardacebi** [comment] 2018-08-12 15:48
@datitisev But it's still here :)

**Comment by datitisev** [comment] 2018-08-12 15:53
@ardacebi I said related to, not duplicate of. I agree it's still an issue.

**Comment by CDK2020** [comment] 2018-11-12 07:38
Does 95f0edc fix this?

**Comment by franzliedke** [comment] 2018-11-12 08:57
It should.

**Comment by franzliedke** [comment] 2018-11-29 20:02
@ardacebi Can you describe the exact behavior you are experiencing?

**Comment by luceos** [comment] 2018-11-30 08:11
I cannot reproduce on discuss.

**Comment by ardacebi** [comment] 2018-11-30 14:02
From discuss:

![registrazione schermo 2018-11-30 alle 16 51 48](https://user-images.githubusercontent.com/17576065/49293589-a2ae5680-f4c1-11e8-9c65-14764d884c46.gif)

**Comment by ardacebi** [comment] 2018-11-30 14:03
It's working properly from the bottom though. Previously it also had an issue with the very bottom too. Now to issue only persists for the first posts. Compare old gifs with the latest.

**Comment by gurjyot** [comment] 2018-11-30 14:06
I can confirm this issue.

**Comment by ardacebi** [comment] 2020-03-14 11:14
I no longer can reproduce this issue on discuss.flarum.org, can someone confirm?

**Comment by askvortsov1** [comment] 2020-10-02 05:53
No longer an issue with the frontend rewrite, got fixed somewhere within #2160 #2255, or #2299

**Closed by askvortsov1** 2020-10-02 05:53 UTC
Labels: type/bug
