### ISSUE TITLE
Cannot Install using composer 

### ISSUE THREAD

**Issue by jamalabo1** [flarum/core#1299] opened 2017-11-30 17:36 UTC
> Issues on Github are meant for bug reporting. Please post feature requests on the [discussion forum](https://discuss.flarum.org/t/features).
---
> Try to complete the below form as far as you are able and are willing to share. Add a screenshot of the issue if you can.

## Explanation

I cant install flarum using composer, can I install using anything else?

## Technical details

- Version of Flarum: x
- Website URL where the bug is visible: http://community.tweakjs.com
- The webserver you are running: apache,
- PHP version: 7.x.x
- Hosted environment: dedicated server
- Hosting provider: Self Hosting, Cloudflare CDN

## Flarum info

```
NOT INSTALLED
```

## Log files

```
Fatal error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///opt/cpanel/composer/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 513
```

can I install without composer?

**Comment by luceos** [comment] 2017-12-01 08:01
@jamalabo1 you're missing the mbstring php extension.

**Comment by franzliedke** [comment] 2017-12-13 20:41
This is not a bug, so I am closing this issue.

As @luceos noted, you're missing a PHP extension that Flarum *requires* to work.

**Closed by franzliedke** 2017-12-13 20:41 UTC
