### ISSUE TITLE
Search results cannot be scrolled fully on small mobile screens

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2621] opened 2021-02-21 17:13 UTC
## Bug Report

**Current Behavior**

When using the global search feature, it might happen that results cannot be scrolled fully if the screen is not tall enough.

**Steps to Reproduce**
1. Go to https://forum.fibra.click
2. Open the Dev Tools, enable the responsive mode, set a resolution like 360x400
3. Type "matteo" in the search box
4. Notice that you cannot scroll to the end of the results

**Expected Behavior**

The search results dropdown should not go beyond the border of the screen.

**Screenshots**

Provided by a user of my forum with a 16:9 screen:

![image](https://user-images.githubusercontent.com/2164763/108632647-58359d80-7470-11eb-8c32-1b50e82249be.png)

**Environment**
- Flarum version: 0.1.0-beta.15
- Website URL: https://forum.fibra.click
- Browser: Chrome, Firefox

**Comment by askvortsov1** [comment] 2021-02-21 18:58
Ah, I've experienced this before, and it was extremely irritating, but I forgot to file an issue. Yeah this is one of the UI bugs that needs to go

**Comment by SychO9** [comment] 2021-02-21 19:40
This is better fixed with flarum/issue-archive#348 imho

**Comment by askvortsov1** [comment] 2021-02-21 19:45
Fair, but that one's a bit controversial, since we need to settle on a design. I know @KyrneDev had some concerns about it, plus the placement of the nav bar at the top or bottom wasn't too clearly agreed upon. Either way, good that we have this in the system!

**Comment by SychO9** [comment] 2021-02-21 19:51
Well, I haven't fully taken a look at the conversation there, but it dates back to 2015-2016, we'll take a second look at it when we get to it and see.

**Comment by askvortsov1** [comment] 2021-03-02 05:35
Did some more investigation, the issue seems to be caused by links pushing down search. Its max height is set to 70vh which works fine it it's positioned where it would be by default, but not if there's extra content above (such as with fof links). Opening a PR to set max height dynamically, until we switch to a better solution with flarum/issue-archive#348

**Closed** 2021-03-07 21:31 UTC
