### ISSUE TITLE
[Tags] Navigating from Tags page to a discussion list does not refresh it

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2502] opened 2020-12-20 22:44 UTC
For example,
1. Click Following
2. Click Tags
3. Click All Discussions

The discussions shown in the list will still be the Following discussions, the list won't refresh.

https://user-images.githubusercontent.com/6401250/102726232-0b580e00-42eb-11eb-806e-dc6d3dbdff39.mp4

This is most likely caused by the check we have for previous page being an instance of IndexPage. Haven't delved too deep into it though.

**Comment by askvortsov1** [comment] 2021-01-04 22:51
Closing as duplicate of https://github.com/flarum/core/issues/2516, since that is more detailed

**Closed by askvortsov1** 2021-01-04 22:51 UTC
