### ISSUE TITLE
The Oncreate title is no longer added after some updates

### ISSUE THREAD

**Issue by ramesh-dada** [flarum/core#2990] opened 2021-07-29 12:32 UTC
## Bug Report

**Current Behavior**
The Title on the pages added by 3rd Party extensions is no longer added after an update the update includes following contents
![image](https://user-images.githubusercontent.com/75124237/127491720-87685557-a9cc-43df-ae92-8bdfdfab098d.png)

**Steps to Reproduce**
1. Run `composer update` in flarum root directory
2. Go to any page added by any third party extension you will see your forum title at the place of of the page title.

**Expected Behavior**
The original title should be added to the page at the place of Forum IndexPage title

**Screenshots**
![image](https://user-images.githubusercontent.com/75124237/127491931-d409517a-7df2-4350-89e2-9e72f91b9809.png)

**Environment**
- Flarum version: v1.0.4
- Webserver: Apache
- PHP version: 8.0.1

**Possible Solution**
```
        if (app.current.get('routeName') === 'bookmarks') {
            app.setTitle(app.translator.trans('clarkwinkelmann-bookmarks.forum.page.title'));
        }
```
Extension Developers can use the above as an alternative.

**Comment by ramesh-dada** [comment] 2021-07-29 13:00
I seen this issue in every extension including FoF Page but it doesn't happens in clarkwinkelmann/flarum-ext-bookmarks because clark sir/brother is using

```
        if (app.current.get('routeName') === 'bookmarks') {
            app.setTitle(app.translator.trans('clarkwinkelmann-bookmarks.forum.page.title'));
        }
```

But in other extensions like FOF Pages, Justoverclock Keywords v17dev/Badges, etc they are using the below which doesn't seems to work.

```
  oncreate(vnode) {
    super.oncreate(vnode);
    app.setTitle(app.translator.trans('flarum-ext-keywords.forum.pagetitle'));
    app.setTitleCount(0);
  }

```

**Comment by SychO9** [comment] 2021-07-29 13:27
can you post screenshots of the actual problem ? of what you're seeing ?

**Comment by clarkwinkelmann** [comment] 2021-07-29 15:04
I'm not able to reproduce. I updated all dependencies on my test forum and FoF Pages titles still show up.

Can you share the output of your `php flarum info` ? Does disabling other extensions maybe solve the issue?

Does it happen on page load? And/or only on page change?

Is there an online forum where we can experience this?

I'm surprised there would be a difference between the Bookmarks extension and others, because behind the scenes it still runs in the `oncreate` hook, after the parent Component `oncreate`. Only difference in Bookmarks is that `IndexPage.setTitle` is extended, but that method is called from `IndexPage.oncreate` in the same way that other extensions do :thinking:

**Comment by ramesh-dada** [comment] 2021-07-29 17:16
@clarkwinkelmann I ran php flarum cache clear as well as php flarum migrate and this issue still exists this title works perfectly it doesn't happens in the page the title changes in page but you will have to go to html source by pressing Ctrl + U in order to see index title in that pages, test once again and let me know if it's true I tried in local forum as well I can confirm this exists the page title is changed by javascript but in search engines case they won't browse like a normal user does they simply read the meta tags

**Comment by luceos** [comment] 2021-07-30 08:16
```js
        if (app.current.get('routeName') === 'bookmarks') {
            app.setTitle(app.translator.trans('clarkwinkelmann-bookmarks.forum.page.title'));
        }
```

this works with bookmarks

```js
  oncreate(vnode) {
    super.oncreate(vnode);
    app.setTitle(app.translator.trans('flarum-ext-keywords.forum.pagetitle'));
    app.setTitleCount(0);
  }
```

you say this doesn't with other extensions.

On discuss byobu and tags both do work. So that makes me assume this is an issue with those extensions not so much with core? Byobu seems to override the `setTitle` method of the Page component:

https://github.com/FriendsOfFlarum/byobu/blob/324b07f25aa1fd4ceaff89c93dfb018de9ff8f43/js/src/forum/pages/PrivateDiscussionsPage.js#L26-L30

Testing `app.setTitle()` on discuss from the browser console has no influence on the browser title; so this does seem to be an issue.

**Comment by ramesh-dada** [comment] 2021-07-30 11:15
@clarkwinkelmann @SychO9 This video proves that this issue exists.
https://user-images.githubusercontent.com/75124237/127644800-ff8ab5b2-881a-4435-982d-5d1557c3c379.mp4

> @luceos On discuss byobu and tags both do work. So that makes me assume this is an issue with those extensions not so much with core? Byobu seems to override the `setTitle` method of the Page component:
>
>https://github.com/FriendsOfFlarum/byobu/blob/324b07f25aa1fd4ceaff89c93dfb018de9ff8f43/js/src/forum/pages/PrivateDiscussionsPage.js#L26-L30

Sir yes you are right tags work properly but byobu doesn't work properly go to html source and you will be able to see the title as **All Discussions**.
![image](https://user-images.githubusercontent.com/75124237/127645244-b43644d7-4ab1-4634-9fe8-300cdc2d463c.png)

**Comment by davwheat** [comment] 2021-07-30 11:19
> Sir yes you are right tags work properly but byobu doesn't work properly go to html source and you will be able to see the title as All Discussions.

That will be a bug in Byobu rather than core. It's only changing the title on the frontend while the HTML source is provided by the backend.

**Comment by SychO9** [comment] 2021-07-30 11:39
I don't see any issues in core here, only third party extension issues which should be reported in said extension repositories.

Byobu doesn't change the title from the backend, so the HTML document has the default title: https://github.com/FriendsOfFlarum/byobu/blob/master/src/Content/PrivateDiscussionsPage.php

> Testing app.setTitle() on discuss from the browser console has no influence on the browser title; so this does seem to be an issue.

That's intended behaviour for the homepage.
https://github.com/flarum/core/blob/ce824b0ccff6a6570e2254e207e0d17fbbdd1b1c/js/src/common/Application.js#L279-L284

I'm closing this issue as there isn't a problem with the core code, feel free to re-open if there is one.

**Closed by SychO9** 2021-07-30 11:39 UTC

**Comment by ramesh-dada** [comment] 2021-07-30 11:43
OK Thank you so much all for the support, But I seen before updating repositories that in the html raw also the title is modified I am sure but maybe after updating this doesn't seems to work.
