### ISSUE TITLE
Discard user registration when confirmation email fails to send

### ISSUE THREAD

**Issue by dragonares5** [flarum/core#2254] opened 2020-08-03 18:13 UTC
## Bug Report

**Current Behavior**
It displays a error message:
"Oops! Something went wrong. Please reload the page and try again."
If you try to register again (the message ask you to do that), it says email/user is already taken.

**Steps to Reproduce**
1. Setting mail configuration as "mail" in control panel of flarum with windows environment (normally, it doesn't have email binary to be used by php in windows env)
2. Try to register.
3. When errors shows, try to register again with the same data.

**Expected Behavior**
Rollback/discard user registration when a error occurs.

**Environment**
- Flarum version: beta-13
- Webserver: Apache
- Hosting environment: Windows Server
- PHP version: 7.2

**Possible Solution**

Rollback/discard user registration. 

1. When error occurs, the user expect that the account would fail to be created, but its not the case. Especially when the error message says "Reload the page and try again"!

Logs:
```
[2020-08-03 17:28:52] production.ERROR: Swift_TransportException: Process could not be started [The system cannot find the path specified.
] in C:\laragon\www\flarum\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:302
```

**Comment by askvortsov1** [comment] 2020-08-16 17:50
As of beta 13, a custom task queue solution is supported, so that email confirmations can be processed asynchronously. Furthermore, in beta 14, there will be a "send test email" feature in the admin dashboard. This has been discussed before, and the current consensus is that this is the intended behavior, so I'm going to close this. Thank you for the issue though!

**Closed by askvortsov1** 2020-08-16 17:50 UTC
