### ISSUE TITLE
Deleted topics still show up on recently posted topic area on the tags page on a tag

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1492] opened 2018-07-03 21:21 UTC
## Bug Report

**Current Behavior**
A post is shown on a tag on the tags page as recently posted even if it's deleted.

**Steps to Reproduce**
1. Go to homepage
2. Click on tags
3. Scroll down to off-topic (in my case it's off-topic, it may change over time)

**Expected Behavior**
A deleted post shouldn't be shown.

**Screenshots**

![screenshot_2018-07-04 flarum community](https://user-images.githubusercontent.com/17576065/42244990-d4287690-7f1f-11e8-8b23-bc6ae9e1aa13.png)

![467574567](https://user-images.githubusercontent.com/17576065/42245064-181efaa4-7f20-11e8-957f-47819f6e7e46.png)

![screenshot_2018-07-04 flarum community 1](https://user-images.githubusercontent.com/17576065/42244992-d5a83884-7f1f-11e8-8bc8-d89e7d38f183.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Comment by datitisev** [comment] 2018-07-04 13:09
Duplicate of #913

**Comment by TurboProgramming** [comment] 2018-07-04 13:18
@datitisev So should I close this or remain it opened to remind the developers of the issue?

**Comment by franzliedke** [comment] 2018-07-04 20:11
One issue is enough. :wink:

**Closed by franzliedke** 2018-07-04 20:11 UTC
