### ISSUE TITLE
Problem with post and discussion counters

### ISSUE THREAD

**Issue by manaszon** [flarum/core#1722] opened 2019-01-06 15:28 UTC
**Current Behavior**
If you create a discussion and then you delete it (permanently), the number of your posts and discussions will stay at 1 (if you had 0 at start) but you can't see the posts and discussion (of course). The post is not deleted from database neither.

**Steps to Reproduce**
1. Create a new discussion
2. Delete it permanently
3. Check your profile

**Screenshots**
At the start we have 0 posts and 0 discussions.
![](https://i.imgur.com/IgAj8CO.png)  

Then we create a discussion, so we have 1 post and 1 discussion. That's good.
![](https://i.imgur.com/FIZi0Rn.png)  

But after we delete the discussion, we still have 1 post and 1 discussion.
![](https://i.imgur.com/dpgD0mU.png)

**Environment**
- Flarum version: 0.1.0 Beta 8
- Webserver: Apache

**Comment by franzliedke** [comment] 2019-01-22 21:53
Do we consider this a bug or a feature? At FluxBB, we always only incremented these counters (though a manual reset by admins was possible).

**Comment by PeopleInside** [comment] 2019-01-23 22:10
Maybe admin should have a reset button under the user profile. I saw the same "issue" on my install ... for fix i need to edit the user database table... so maybe something for reset on user profile from admin should be implemented.

**Comment by franzliedke** [comment] 2019-03-06 22:18
Also closing this as duplicate of flarum/issue-archive#321.

**Closed by franzliedke** 2019-03-06 22:18 UTC
Labels: needs-discussion
