### ISSUE TITLE
hadling thousand of tag like discourse

### ISSUE THREAD

**Issue by satyamraz** [flarum/core#2189] opened 2020-05-31 20:14 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. eg. I have an issue when [...]

**Describe the solution you'd like**
A detailed description of your proposed solution. Include:
- How the feature would work/behave
- Any potential drawbacks
- Maybe a screenshot, design, or example code

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
Consider who this change will be useful to – most Flarum forums, or just a few?

**Describe alternatives you've considered**

**Comment by askvortsov1** [comment] 2020-05-31 20:29
I agree that the tags permission management system is a bit clunky (and I think we have an issue for that). But just out of curiosity, what's the use case for a forum with thousands of tags? Perhaps a thorough hashtags extension where users could create hashtags would be better?

**Comment by satyamraz** [comment] 2020-05-31 20:32
But I want to use flarum for stock exchange where where thousand of tag I
want to use but it makes ugly design

**Comment by askvortsov1** [comment] 2020-05-31 22:51
Thank you again for reporting, I'm going to close this as a duplicate of https://github.com/flarum/core/issues/1753. However, I think that your use case needs an extension separate from our bundled tags extension

**Closed by askvortsov1** 2020-05-31 22:51 UTC
