### ISSUE TITLE
[tags] error when no tags are available for discussion creation to the user

### ISSUE THREAD

**Issue by luceos** [flarum/core#2500] opened 2020-12-18 09:20 UTC
## Bug Report

**Current Behavior**

There's a js script error when no tags are available for a user to create a discussion in.

**Steps to Reproduce**
1. Create a few tags
2. Globally restrict discussion creation to admins
3. Register/log in with a regular member
4. Try to click create discussion

**Expected Behavior**
Button to create discussion should probably set to "can't create discussion"?

**Screenshots**

<img width="365" alt="image" src="https://user-images.githubusercontent.com/504687/102597237-a2ba3700-411a-11eb-9537-a7678331bea5.png">

**Environment**
- Flarum version: dev-master = close to beta 15

**Comment by matteocontrini** [comment] 2020-12-18 09:34
Duplicate of #2473

**Closed** 2020-12-18 09:46 UTC
Labels: type/bug
