### ISSUE TITLE
[Markdown/BBcode] Parenthesis immediately inside bbcode tags become markdown links

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#649] opened 2015-11-30 06:14 UTC
There seems to be a conflict when both BBCode and Markdown are activated (as they are on Flarum.org). When a properly formed bbcode expression is created with parenthesis immediately inside the tag contents, Markdown parses instead and turns it into a url. For example: 

`[b](this)[/b]` would turn into `<a href="this"></a>`
`[url=http://flarum.org](and this)[/url]` becomes `<a href="http://flarum.org/d/and">url=http://flarum.org[/url]</a>`

The link/tag code can be denatured by applying Markdown's escape character `\` before the expression, but I have yet to uncover a way to prevent the formation of the Markdown link by altering the contents of the tag (besides removing one or more parentheses) in order to finish the BBCode parsing.

**Comment by Luceos** [comment] 2015-11-30 07:04
So in fact both extensions parse the content and either one shouldn't if the body has already parsed by someone.. This is gonna be a challenge to fix!

**Comment by tobscure** [comment] 2015-11-30 08:38
cc @JoshyPHP

**Comment by JoshyPHP** [comment] 2015-11-30 10:36
Markdown-style links are given priority over BBCodes. This is intentional. If it was the other way around it would be impossible to create a link that looks like a BBCode, e.g. `[HR](https://en.wikipedia.org/wiki/HR)`

Special characters can generally be escaped with `\` to be interpreted as plain text, not markup. If you escape the left square bracket then it'll be displayed as plain text, not a BBCode. What you need to do is escape special characters that are *not* part of the markup. In your case:

    [b]\(this)[/b] [url=http://flarum.org]\(and this)[/url]

...will become:

    <b>(this)</b> <a href="http://flarum.org" target="_blank" rel="nofollow">(and this)</a>

**Comment by franzliedke** [comment] 2015-11-30 11:53
Did we talk about enabling only Markdown, and not BBCode, before? I'd love that.

**Comment by tobscure** [comment] 2015-11-30 21:50
@franzliedke do you mean on discuss.flarum, or by default on new Flarum installations?

**Comment by franzliedke** [comment] 2015-11-30 21:58
From my perspective, it could be disabled by default. Not sure how big the resistance to such a decision would be.

**Comment by dcsjapan** [comment] 2015-11-30 22:14
I think having only one of them turned on by default makes sense. As long as the other one is available, there shouldn't be too much of a brouhaha.

**Comment by tobscure** [comment] 2015-11-30 22:29
OK. I think we should wait until we have formatting buttons though.

**Comment by jordanjay29** [comment] 2015-12-01 19:17
In that case, I'd just turn Markdown on by default and leave BBCode off by default until you have buttons.

**Comment by dcsjapan** [comment] 2015-12-01 20:30
It would also be good if the documentation could mention somewhere that BBcode is disabled by default, and cautioned users that Markdown can interact with things like BBcode and [Emoji](https://github.com/flarum/core/issues/305) to produce unexpected results.

**Comment by tobscure** [comment] 2016-03-16 01:29
You know, I'm not sure if I'm in favour of disabling BBCode by default anymore. It is nice for people to just be able to use whatever formatting syntax they're familiar with, without having to think about it. The problem that this issue describes is only an edge case and can be worked around as per JoshyPHP's comment – or you could even just put a space between the `[b]` and the `(this)`.

**Comment by jordanjay29** [comment] 2016-03-16 01:35
>It is nice for people to just be able to use whatever formatting syntax they're familiar with, without having to think about it.

 I actually think that's the reason to fix this. A MD user probably understands why that is happening, but a BBC user does not. As you say, it's an edge case, which makes it a low priority, but if an intelligent parsing solution could be found I think it would be to Flarum's benefit.

**Comment by tobscure** [comment] 2016-03-16 01:49
@JoshyPHP could we make BBCode tags only register if there's an end tag too, and then give BBCode priority over Markdown? That way `[b](this)` would become a link, but `[b](this)[/b]` would be bold. I suppose `[hr](this)` still wouldn't work, but in our case that's not an issue as we don't even have that one enabled...

**Comment by JoshyPHP** [comment] 2016-03-16 03:02
Short answer: not really.
Long answer: kind of. You could add [a filter that tests whether a Markdown link is followed by something that looks like a closing BBCode](https://gist.github.com/JoshyPHP/4632277f3e5f2cbf3f6d). I don't know if that's the best way to solve this specific issue though.

**Comment by franzliedke** [comment] 2016-03-16 03:03
Probably not. Sounds like a workaround that's bound to create problems in the future.

**Comment by franzliedke** [comment] 2016-03-16 03:04
In any case, making more of the various parts configurable (enable/disable certain BBCodes, or all of Markdown) may be a goal for this extension anyway?

**Comment by tobscure** [comment] 2016-03-16 04:10
Yeah I think making BBCode configurable, with the ability to add custom BBCodes, is a good idea.

**Comment by dcsjapan** [comment] 2016-03-16 04:12
A settings panel for the BBcode extension? Cool!

**Comment by franzliedke** [comment] 2016-05-15 11:42
Is there anything left to do for this issue? I think it has been explained in detail that the "bug" is by design and can be circumvented by escaping the opening parenthesis.

**Comment by tobscure** [comment] 2016-05-18 02:10
I don't think so!

**Closed by tobscure** 2016-05-18 02:10 UTC
Labels: Cleanup, Needs Discussion
