### ISSUE TITLE
Bug after click to browser's back button or Flarum logo

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1483] opened 2018-07-03 19:46 UTC
## Bug Report

**Current Behavior**
After some attempts clicking the browser's back button or the Flarum logo while in an article, the back button will stay at the top left and the article title will stay as the tab title. 

Here is a video I captured:
https://youtu.be/VjUpZh6Sy60

**Steps to Reproduce**
1. Go to Flarum's home page
2. Click on a topic
3. Click on your browser's back button or the Flarum logo so fast (try a few times to reproduce the issue like I did on the video)
4. Repeat from step 2 to 3 until you see the error (approx. repeat time 2-3)

**Expected Behavior**
The back button should disappear immediately from top left after the click to the browser's back button or the Flarum logo and "Flarum Community" should replace the topic title on the tab title.

**Screenshots**
![screenshot_2018-07-03 issues with safari php - flarum community](https://user-images.githubusercontent.com/17576065/42241323-d626846c-7f12-11e8-901b-93e1476fb6db.png)

![87585678567856](https://user-images.githubusercontent.com/17576065/42241326-d7d77f6e-7f12-11e8-9a02-cc773381d4b1.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Comment by TurboProgramming** [comment] 2018-07-03 20:29
Edited post and title to include that the bug also happens after a click on the Flarum logo.

**Comment by tobscure** [comment] 2018-07-13 09:10
Thanks for the detailed report 👍 was able to reproduce the issue with your instructions.

I suspect the issue is that the AJAX request for loading the discussion is finishing after the index page is rendered, so the followup discussion page logic executes on the index page.

**Comment by franzliedke** [comment] 2018-07-14 20:19
GIF by @datitisev (originally posted in another issue):

![GIF of issue](https://user-images.githubusercontent.com/6401250/42189179-1f50d578-7e25-11e8-8179-7814b4cbebf7.gif)

**Comment by datitisev** [comment] 2018-07-14 20:43
As @tobscure pointed out, the issue is the AJAX request finishing after the user changes the page.

Here's another GIF showing the bug with Chrome imitating a Slow 3G connection with DevTools.

![2018-07-14 16-37-36](https://user-images.githubusercontent.com/6401250/42728269-e8382e38-8784-11e8-9455-c0c1c191b0e0.gif)

**Comment by franzliedke** [comment] 2018-07-14 20:55
Do we have a solution to this fundamental problem? 

It needs to be clearly defined, first. I guess, most asynchronous actions starting on one page should be canceled when navigating to other pages?

**Comment by iPurpl3x** [comment] 2021-06-14 14:22
I cannot reproduce this problem anymore with Flarum 1.0.
Could anyone confirm ? @datitisev ? @askvortsov1 ? @davwheat ?

**Comment by matteocontrini** [comment] 2021-06-14 21:45
I cannot reproduce it either.

**Comment by tankerkiller125** [comment] 2021-06-15 12:47
I also can not reproduce this anymore, I believe we actually fixed it a few betas ago during the re-write? Regardless though I'll close this issue since it can't be reproduced anymore.

**Closed by tankerkiller125** 2021-06-15 12:47 UTC
Labels: type/bug
