### ISSUE TITLE
"Error: Call to a member function" What's happening?!

### ISSUE THREAD

**Issue by inparsian1** [flarum/core#1194] opened 2017-06-10 00:02 UTC
Error report:
`Something went wrong: Error: Call to a member function execute() on boolean in file /storage/ssd4/907/1905907/public_html/vendor/illuminate/database/Connectors/MySqlConnector.php on line 57 Stack trace: 1. Error->() /storage/ssd4/907/1905907/public_html/vendor/illuminate/database/Connectors/MySqlConnector.php:57 2. Illuminate\Database\Connectors\MySqlConnector->connect() /storage/ssd4/907/1905907/public_html/vendor/illuminate/database/Connectors/ConnectionFactory.php:60 3. Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection() /storage/ssd4/907/1905907/public_html/vendor/illuminate/database/Connectors/ConnectionFactory.php:49 4. Illuminate\Database\Connectors\ConnectionFactory->make() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Database/DatabaseServiceProvider.php:29 5. Flarum\Database\DatabaseServiceProvider->Flarum\Database\{closure}() /storage/ssd4/907/1905907/public_html/vendor/illuminate/container/Container.php:738 6. Illuminate\Container\Container->build() /storage/ssd4/907/1905907/public_html/vendor/illuminate/container/Container.php:631 7. Illuminate\Container\Container->make() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Foundation/Application.php:513 8. Flarum\Foundation\Application->make() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Install/Console/InstallCommand.php:219 9. Flarum\Install\Console\InstallCommand->storeConfiguration() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Install/Console/InstallCommand.php:164 10. Flarum\Install\Console\InstallCommand->install() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Install/Console/InstallCommand.php:95 11. Flarum\Install\Console\InstallCommand->fire() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Console/Command/AbstractCommand.php:37 12. Flarum\Console\Command\AbstractCommand->execute() /storage/ssd4/907/1905907/public_html/vendor/symfony/console/Command/Command.php:266 13. Symfony\Component\Console\Command\Command->run() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Install/Controller/InstallController.php:84 14. Flarum\Install\Controller\InstallController->handle() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Http/Handler/ControllerRouteHandler.php:52 15. Flarum\Http\Handler\ControllerRouteHandler->__invoke() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:71 16. Flarum\Http\Middleware\DispatchRoute->__invoke() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php:224 17. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88 18. Zend\Stratigility\Dispatch->__invoke() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-stratigility/src/Next.php:160 19. Zend\Stratigility\Next->__invoke() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Http/Middleware/StartSession.php:33 20. Flarum\Http\Middleware\StartSession->__invoke() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php:224 21. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php:88 22. Zend\Stratigility\Dispatch->__invoke() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-stratigility/src/Next.php:160 23. Zend\Stratigility\Next->__invoke() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:103 24. Zend\Stratigility\MiddlewarePipe->__invoke() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Http/AbstractServer.php:53 25. Flarum\Http\AbstractServer->__invoke() /storage/ssd4/907/1905907/public_html/vendor/zendframework/zend-diactoros/src/Server.php:166 26. Zend\Diactoros\Server->listen() /storage/ssd4/907/1905907/public_html/vendor/flarum/core/src/Http/AbstractServer.php:34 27. Flarum\Http\AbstractServer->listen() /storage/ssd4/907/1905907/public_html/index.php:16`

**Comment by franzliedke** [comment] 2017-06-10 10:23
I am closing this ticket due to a lack of information.

When you open a ticket, please follow our [Contributing Guidelines](https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md). Most importantly, please provide as much information as possible so that we can together find out the root cause.

In particular, I would like to highlight this section of our guidelines:
> It is required that you clearly describe the steps necessary to reproduce the issue you are running into. Issues with no clear repro steps will not be triaged.

In this case, we would need more information about how and when you encountered this error.

Feel free to provide more information, then this ticket will be reopened.

**Closed by franzliedke** 2017-06-10 10:23 UTC

**Comment by datitisev** [comment] 2017-06-10 11:25
This looks like it happened during the installation process.
However, as Franz said, we need more information about your server’s specs and what you did to get this errro.
