### ISSUE TITLE
Tag Sidebar categorical issue

### ISSUE THREAD

**Issue by aswinehart** [flarum/core#567] opened 2015-10-02 14:59 UTC
Hi, I just noticed that the subcategories for main tags display out of order when the main Tag is clicked. For instance, in the image provided, the science subjects should all be under Science. Biology appears below Language Arts on click. Any way to update the list items display?
Thanks! 

<img width="240" alt="screen shot 2015-10-02 at 10 54 09 am" src="https://cloud.githubusercontent.com/assets/10821970/10249617/4ded0f12-68f4-11e5-8972-28ed67af82da.png">

**Comment by aswinehart** [comment] 2015-10-02 15:01
Here is the associated HTML: 

<li class="item-tag16">
<a class="TagLinkButton hasIcon child" href="/t/biology?sort=top" style="" title="">
<span class="icon TagIcon Button-icon" style="background-color: rgb(0, 153, 0);"></span>
Biology
</a>
</li>
<li class="item-tag13 active">
<a class="TagLinkButton hasIcon " href="/t/science?sort=top" style="color: rgb(140, 206, 142);" title="">
<span class="icon TagIcon Button-icon" style="background-color: rgb(140, 206, 142);"></span>
Science
</a>
</li>
<li class="item-tag17">
<a class="TagLinkButton hasIcon child" href="/t/chemistry?sort=top" style="" title="">
<span class="icon TagIcon Button-icon" style="background-color: rgb(159, 176, 84);"></span>
Chemistry
</a>
</li>

**Comment by Fastidious** [comment] 2015-10-05 14:35
Yes, this is an ongoing issue. I am not sure, but #325 might relate. It happens on any browser, not only in Chrome, as #325 asserts. I have looked at the database, and the tag/subtag relationship shows fine, it just doesn't show right on the browser.

**Comment by tobscure** [comment] 2015-10-05 23:20
Duplicate of #325

**Closed by tobscure** 2015-10-05 23:20 UTC
