### ISSUE TITLE
Signup stuck

### ISSUE THREAD

**Issue by tvb** [flarum/core#234] opened 2015-08-14 06:49 UTC
Got the mail but the page did not refresh itself:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (dTDTfCnid9SRAHa6Bjf56i3u5KQa7KkVQg6TvGpFjMlfKUwNqx8Q8Sltph9epgbYyg_Oot-MzOyPB0w=w1313-h1073, line 0)
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (cCJ_8B_kDa5WJUF1xTpeeG-Z6B18OkN27h1oumhmkQlb2INLbGK4Ci06r-ZnSlsvBaqhdmfdaQOMCsQ=w1366-h1173, line 0)
[Error] Failed to load resource: too many HTTP redirects (0By8E6gDEc05DNGVBTmR2a3RpX2s, line 0)
[Error] TypeError: undefined is not a function (evaluating 'e.isConfirmed()')
	onerror (forum-O5kndMR4yHhvzmyF.js, line 1)
	onerror (forum-O5kndMR4yHhvzmyF.js, line 1)
	onreadystatechange (forum-O5kndMR4yHhvzmyF.js, line 1)
```

**Comment by tvb** [comment] 2015-08-14 06:50
with that I am also unable to upload an avatar:

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

**Comment by tobscure** [comment] 2015-08-14 07:26
Duplicate of #231 and #230. Just haven't deployed yet :)

**Closed by tobscure** 2015-08-14 07:26 UTC

**Comment by tvb** [comment] 2015-08-14 07:27
Ha! Sorry about that.
