### ISSUE TITLE
Notifications are added infinitely

### ISSUE THREAD

**Issue by prestorondo** [flarum/core#1415] opened 2018-05-01 08:58 UTC
## Explanation

Problem to reproduce : 
(please make sure you have unread notifications + posts)
1. go to "all discussions"
2. click on "Mark all as read"
3. click cancel
4. click on notification icon in the toolbar
keep doing (4) and closing, you see that the notifications are duplicated.

## Technical details

- Version of Flarum: 0.1.0-beta-7.1
- web server apache, nginx reverse proxy
- PHP version: 7.1
- Hosted environment: shared or vps
#

**Comment by Ralkage** [comment] 2018-05-17 00:52
I cannot reproduce this.

@prestorondo can you please run this command in the root directory of your Flarum installation?

`php flarum info`

and post the output here please. We need to know more about the extensions you have installed if anything.

**Comment by prestorondo** [comment] 2018-05-17 21:38
Flarum core 0.1.0-beta.7
PHP 7.0.30-0ubuntu0.16.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT oe800-bbcode-cards 0.1.4
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
EXT prestorondo-flacoin dev-master
EXT wiwatsrt-best-answer v0.1.0-beta.11
EXT flarum-emoji v0.1.0-beta.6
EXT clarkwinkelmann-emojionearea 0.1.2
EXT flarum-english v0.1.0-beta.7
EXT flagrow-bazaar 0.2.4
EXT flagrow-mason 0.2.0
EXT flagrow-masquerade 0.2.0
EXT flagrow-split 0.2
EXT flagrow-upload 0.6.0
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT xengine-markdown-editor 1.3.1
EXT flarum-mentions v0.1.0-beta.7
EXT antoinefr-online 0.3.0 (a767e36333062e23a7b6d9603e5dc94b42663255)
EXT sijad-pages 0.1.0-beta.3
EXT sijad-persian dev-master (c46658c2036cb3c6f26b8c53218e5ff15f8b5f63)
EXT reflar-nightmode 0.1.1
EXT reflar-pretty-mail 0.1.0-beta.2
EXT reflar-reactions 1.0.0-beta.3
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
EXT avatar4eg-users-list 0.1.1
Base URL: http://mywebsite.domain
Installation path: /www/

**Comment by Ralkage** [comment] 2018-05-21 14:10
I see you have a lot of extensions installed other than the ones that are packaged with Flarum.

May I ask what `prestorondo-flacoin` does or it's functionality? We cannot help reproduce what we do not have access to.

**Comment by prestorondo** [comment] 2018-05-21 19:07
That is an extension I started writing. currently it is totally empty so it might answer your concerns. Before I post this issue I had a search through issues and found that some other users reported issues with "unread" notifications and that they do not become "read" even after clicking on them. 

I know this is very general and hard to reproduce but I thought mentioning it would be better than just leaving it out

**Comment by datitisev** [comment] 2018-05-21 21:30
@prestorondo I think a GIF or video would help us understand and solve the problem.

**Comment by luceos** [comment] 2018-05-22 08:40
Try removing the markdown editor by xengine, see https://github.com/XEngine/flarum-ext-markdown-editor/blob/master/composer.json

It's only compatible with beta 5, thus it's very likely to create issues.

---

I'm closing this one, feel free to re-open if you encounter this exact issue on a clean install.

**Closed by luceos** 2018-05-22 08:40 UTC
Labels: Needs Verification
