### ISSUE TITLE
wrong discussion filter when come from default tags page

### ISSUE THREAD

**Issue by majoskorec** [flarum/core#2802] opened 2021-04-21 16:33 UTC
## Bug Report

**Current Behavior**
if you have Tags as default home page and click on any tag, discussions will not be filtered correctly, there are discussions not only from that tag

**Steps to Reproduce**
1. set tags as default homepage (admin -> basic -> home page)
2. open homepage
3. click on any tag 
4. there will be discussions without that tag

**Environment**
- Flarum version: v0.1.0-beta.16
- Website URL: https://beta.flarum.site/

**Comment by askvortsov1** [comment] 2021-04-21 19:20
Hi, thanks for the report! This is a duplicate of https://github.com/flarum/core/issues/2752, and has been fixed for the next release.

**Closed by askvortsov1** 2021-04-21 19:20 UTC
