### ISSUE TITLE
Badges showed differently: front and back end

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1745] opened 2019-02-11 10:51 UTC
**Current Behavior**

- I uploaded a custom image for badges in the assets folder, format svg.
- Added the following CSS in the backend of Flarum under apparence:

```
.icon.icon-xxx {
  display: inline-block;
  background: url(/assets/logo-symbol.svg) center;
  width: 100%;
  height: 100%;
  background-size: 100%;
}
```
Than under permission in backend i edited the group admin by setting up as badge icon: `icon icon-xxx`

**Expected Behavior**
See the correct badges also in the backend. The badge is showed only on the community visitor side, not in the permission tab, admin group.

**Screenshots**

Please see: https://discuss.flarum.org/d/18196-custom-badges-how-to-have-a-not-standard-badge/10
as you can see the admin badge in the permission are not visible but if i open the community https://community.peopleinside.it/d/6-faq-regolamento-cookies the badge is correctly showed.

**Environment**
- Flarum version: 0.1.0-beta.8.1PHP 7.3.1
- Website URL: https://community.peopleinside.it
- Webserver: [e.g. apache, nginx] Apache
- Hosting environment: [e.g. shared, vps] VPS
- PHP version: 7.3.1
- Browser: Firefox last one

```
Output of "php flarum info", run this in terminal in your Flarum directory.


```
Loaded extensions: Core, date, libxml, pcre, dom, fileinfo, filter, hash, json, SPL, bz2, posix, Reflection, session, SimpleXML, standard, xml, xmlreader, xmlwriter, bcmath, openssl, calendar, ctype, curl, dba, mbstring, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, exif, zlib, pcntl, PDO, pdo_sqlite, shmop, soap, sockets, sqlite3, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlrpc, xsl, zip, Phar, mysqlnd, mysqli, pdo_mysql, ionCube Loader, Zend OPcache
+------------------------------+-----------------+--------+
| Flarum Extensions            |                 |        |
+------------------------------+-----------------+--------+
| ID                           | Version         | Commit |
+------------------------------+-----------------+--------+
| flarum-approval              | v0.1.0-beta.8   |        |
| flarum-bbcode                | v0.1.0-beta.8   |        |
| flarum-emoji                 | v0.1.0-beta.8   |        |
| flarum-flags                 | v0.1.0-beta.8.1 |        |
| flarum-likes                 | v0.1.0-beta.8.1 |        |
| flarum-lock                  | v0.1.0-beta.8   |        |
| flarum-mentions              | v0.1.0-beta.8.1 |        |
| flarum-sticky                | v0.1.0-beta.8   |        |
| flarum-subscriptions         | v0.1.0-beta.8   |        |
| flarum-suspend               | v0.1.0-beta.8   |        |
| flarum-tags                  | v0.1.0-beta.8.2 |        |
| flarum-lang-english          | v0.1.0-beta.8   |        |
| flarum-statistics            | v0.1.0-beta.8   |        |
| flarum-akismet               | v0.1.0-beta.8   |        |
| nearata-lang-italian         | v0.1.0-beta.8.2 |        |
| flarum-auth-facebook         | v0.1.0-beta.8   |        |
| flagrow-terms                | 0.3.1           |        |
| fof-links                    | 0.1.1           |        |
| flarum-auth-github           | v0.1.0-beta.8   |        |
| fof-user-bio                 | 0.1.1           |        |
| flarum-pusher                | v0.1.0-beta.8.1 |        |
| reflar-twofactor             | 0.1.0-beta.4.2  |        |
| flarum-auth-twitter          | v0.1.0-beta.8   |        |
| flagrow-upload               | 0.7.0           |        |
| flarum-markdown              | v0.1.0-beta.8   |        |
| fof-default-user-preferences | 0.1.0           |        |
+------------------------------+-----------------+--------+
Base URL: https://community.peopleinside.it
Debug mode: off
```
```
Possible Solution

If the badge hosted in my asset folder is correctly showed on front end side to visitors should be showed also correctly in the backend.

Additional Context

https://discuss.flarum.org/d/18196-custom-badges-how-to-have-a-not-standard-badge

Are you able to reproduce this? Be able to set a custom badges can be very useful and actually doesn't require an extensions so i am asking if something in the code can be just improved for show correctly self hosted badges as in the visitor side works. The code should show the same badge showed to the visitor also on the backside panel, should be not an issue but seems not working with self-hosted badge.

![00](https://user-images.githubusercontent.com/5006150/52559646-2c4d9f00-2df6-11e9-9f25-afce0a1eaa09.png)
![01](https://user-images.githubusercontent.com/5006150/52559647-2c4d9f00-2df6-11e9-8097-5f08ead3e1a3.png)
![02](https://user-images.githubusercontent.com/5006150/52559712-569f5c80-2df6-11e9-8c60-47817f2229f2.png)

**Comment by datitisev** [comment] 2019-02-11 21:26
The issue here is that custom CSS set from the Basics page is not applied to the admin side, only the forum itself.

**Comment by PeopleInside** [comment] 2019-02-11 21:34
Should be added maybe a CSS section also for the backend. Can be useful or maybe the one existent applied also in the backend.

**Comment by franzliedke** [comment] 2019-02-12 00:13
I'll close this for now, as this can be considered to be working as intended.

Feel free to open a feature request on the forums, if you want to gather more support / arguments for this feature. Personally, I am skeptical.

**Closed by franzliedke** 2019-02-12 00:13 UTC

**Comment by tobscure** [comment] 2019-03-24 02:13
Maybe we should add a "group badge custom CSS rules" field when adding/editing a group, where you can set CSS rules to be applied to the group's badge (on both the frontend and backend)?

**Comment by franzliedke** [comment] 2019-03-24 23:04
Not all that urgent, but maybe nice for an extension?

**Comment by tobscure** [comment] 2019-03-25 06:37
I would favour putting it in core but agree not urgent
