### ISSUE TITLE
Change password page need design

### ISSUE THREAD

**Issue by Jump3r99** [flarum/core#699] opened 2016-01-01 10:54 UTC
![reset](https://cloud.githubusercontent.com/assets/12465392/12070589/4f752c1c-b07e-11e5-8c10-f586a23eadf6.PNG)

I know it's low on TODO list, but please: just center 'em.

**Comment by Jump3r99** [comment] 2016-01-01 11:11
BTW how to add tags?

**Comment by tobscure** [comment] 2016-01-01 12:20
Duplicate of #252

**Closed by tobscure** 2016-01-01 12:20 UTC

**Comment by Luceos** [comment] 2016-01-01 17:56
@jump3r99 tagging is reserved for core team members.
