### ISSUE TITLE
Search bar has two buttons to close

### ISSUE THREAD

**Issue by Cadiducho** [flarum/core#3150] opened 2021-11-03 22:21 UTC
## Bug Report

**Current Behavior**
When you are writing something in the searchbox, the browser shows two differents "close" buttons. The right one is the one that closes the search box and delete your input, while the left one only erase your writing, but do not close the expanded searchbox

**Steps to Reproduce**
1. Go to any page on the Flarum forum
2. Click on the search box
3. Write something

**Expected Behavior**
You should only see one button, the one that also close the expanded searchbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/3594924/140201260-a05f4a46-831e-46b9-bd23-d68449d5f4ca.png)
The searchbox with the two buttons

![image](https://user-images.githubusercontent.com/3594924/140201282-5ae1b2e1-c112-4724-bb4a-7b2931e9bea7.png)
The search box after clicking left button
**Environment**
- Flarum version: 1.1.0
- Website URL: https://discuss.flarum.org
- Browser: Tested on chrome 95 and edge 95

**Additional Context**
The button that closes the searchbox is a [<button> tag with an icon inside ](https://github.com/flarum/core/blob/f260bd7efead0287add4d363114c7abcb0c4b2ab/js/src/forum/components/Search.tsx#L142)
The otherone is probably a button generated with the input tag, maybe with css or some accesibility feature. I couldn't find it

**Comment by SychO9** [comment] 2021-11-03 22:28
Hello! thank you for the report.

Duplicate of #3126 and has been fixed for the 1.2 release.

**Closed by SychO9** 2021-11-03 22:28 UTC
