### ISSUE TITLE
[Tags] Unable to open TagDiscussionModal with specific permissions setup

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#2374] opened 2020-10-07 22:31 UTC
## Bug Report

**Current Behavior**
In beta 14 (and also in beta 13),  when the "View discussions" permission is set to groups other than "Everyone" or "Members", the TagDiscussionModal won't open and instead, throws an error.

**Steps to Reproduce**
1. Go to the Admin area.
2. Click on "Permissions".
3. Set "View discussions" to any other group(s) other than "Everyone" or "Members". 
4. Open a private/incognito browser session.
5. Create a non-admin account (basic member).
6. Click on "Start a Discussion".
7. Click on "Choose Tags".

**Expected Behavior**
I believe this was more geared towards "Restrict by tag" and for those who only wished to give certain groups access to view all discussions on a forum.

Not sure how this was supposed to behave under these conditions since you wouldn't be able to view a discussion even if you set the minimum **Required Number of Primary Tags* and Required **Number of Secondary Tags** to 0. I assume some sort of toast notification would appear to tell you that you cannot view discussions or something? Again, I'm not sure how this was supposed to function than it throwing an error that it can't find any tags available for use even though they do exist.

**Screenshots**
<details>
<summary>Beta 13</summary>

![image](https://user-images.githubusercontent.com/2059356/95390765-e1827400-08c3-11eb-9524-96ea49406945.png)
![image](https://user-images.githubusercontent.com/2059356/95391435-0e835680-08c5-11eb-98d3-a7501bb7bd07.png)
</details>

<details>
<summary>Beta 14</summary>

![image](https://user-images.githubusercontent.com/2059356/95390585-9ff1c900-08c3-11eb-80ad-881cc8d85b96.png)
![image](https://user-images.githubusercontent.com/2059356/95391820-b731b600-08c5-11eb-90fe-cf44aa170a43.png)
</details>

**Environment**
- Flarum version: v0.1.0-beta.14 and  v0.1.0-beta.13
- Website URL: https://qa.flarum.site & https://beta.flarum.site/
- Webserver: Nginx
- Hosting environment: Unknown
- PHP version: 7.3.11
- Browser: Microsoft Edge Version 85.0.564.70 (Official build) (64-bit)

**Possible Solution**

N/A

**Additional Context**
This bug is present in both beta 13 and now 14 from the looks of it.

Additionally, I'm not sure if this is related to this specific issue. Under these same conditions, the Tags nav list also becomes hidden or gets removed entirely even as a guest:

<details>
![image](https://user-images.githubusercontent.com/2059356/95394735-18a85380-08cb-11eb-80fc-f1fc4ddc57bf.png)
</details>

**Comment by askvortsov1** [comment] 2020-10-08 23:54
As a folllowup fom the closed duplicate, this seems to happen when there are no tags visible to the user to select from. We need to add some kind of case for that (or even better, if we could get a solid solution to #2149)

**Comment by SychO9** [comment] 2021-01-10 08:39
This is the same as #2473 and will be fixed by flarum/tags#112

**Comment by askvortsov1** [comment] 2021-01-12 08:14
Closing as duplicate of https://github.com/flarum/core/issues/2473, since  that one has the assignment

**Closed by askvortsov1** 2021-01-12 08:14 UTC
