### ISSUE TITLE
Profile page shows "no posts" when the last 20 posts are hidden

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2000] opened 2020-02-13 21:50 UTC
## Bug Report

**Current Behavior**

When the last 20 posts for a user are hidden, users that don't have the permission to view hidden posts cannot see previous (visibile) posts on the profile page.

**Steps to Reproduce**

1. Take a user with at least 20 posts
2. Delete (hide) the last (most recent) 20 posts
3. Open the profile page for the user as a guest/regular user
4. See that the page says "no posts"

**Expected Behavior**

The profile page should show posts that are not deleted.

**Screenshots**

Screenshot with a guest user: 

![immagine](https://user-images.githubusercontent.com/2164763/74481140-73abb700-4eb2-11ea-8059-78a40cbf0d9c.png)

With an admin user (bottom of the page):

![immagine](https://user-images.githubusercontent.com/2164763/74481167-81613c80-4eb2-11ea-817b-807699ade2ce.png)

After pressing Load more:

![immagine](https://user-images.githubusercontent.com/2164763/74481174-8625f080-4eb2-11ea-9a9a-04a4487f0f27.png)

**Environment**
- Flarum version: 0.1.0-beta.11.1

I'm not posting the other information because the issue is reproducible on https://beta.flarum.site/

Possibly related to #1333.

EDIT: wow, this is issue 2000 🎉

**Comment by franzliedke** [comment] 2020-02-14 14:52
Yeah, seems to be a regression of #1333.

**Comment by datitisev** [comment] 2020-05-06 14:34
This is still an issue. Even if they aren't all private, it will only show the ones you can see from the latest 20 - completely disabling pagination & the ability to view all posts.

**Comment by askvortsov1** [comment] 2020-06-01 16:49
Duplicate of https://github.com/flarum/core/issues/2000

**Comment by askvortsov1** [comment] 2020-06-01 16:50
Duplicate of https://github.com/flarum/core/issues/1327, sorry

**Closed by askvortsov1** 2020-06-01 16:50 UTC
Labels: type/bug

**Comment by askvortsov1** [comment] 2020-10-02 06:03
Fixed in https://github.com/flarum/core/pull/2291
