### ISSUE TITLE
no default language setting in Basics of the admin ui

### ISSUE THREAD

**Issue by videni** [flarum/core#1234] opened 2017-08-31 09:38 UTC

**Comment by franzliedke** [comment] 2017-11-02 00:27
I am closing this ticket due to a lack of information.

When you open a ticket, please follow our [Contributing Guidelines](https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md). Most importantly, please provide as much information as possible so that we can together find out the root cause.

**Closed by franzliedke** 2017-11-02 00:27 UTC
