### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'type')

### ISSUE THREAD

**Issue by tagecode** [flarum/core#3221] opened 2021-12-23 11:07 UTC
Flarum I installed locally, as long as I log in as a **non-administrator**, it will report this error.

Flarum version: 1.1.1

Error Message: **Something went wrong while trying to load the full version of this site. Try hard-refreshing this page to fix the error.**

Chrome console error:
`Uncaught TypeError: Cannot read properties of null (reading 'type')
    at t.e.pushObject (Store.js:58)
    at Array.map (<anonymous>)
    at t.e.pushPayload (Store.js:38)
    at Proxy.e.boot (Application.js:173)
    at (index):136`
 
I tried:
`Ctrl + F5`
`php flarum cache:clear`
`php flarum assets:publish`

but, it's not work.

Did I make a mistake somewhere?

**Comment by davwheat** [comment] 2021-12-23 11:10
This usually indicates an error in one of your extensions.

Head to the admin dashboard and disable them one by one until the issue is gone, then you know that is the one causing the problem.

**Comment by tagecode** [comment] 2021-12-24 01:56
> This usually indicates an error in one of your extensions.
> 
> Head to the admin dashboard and disable them one by one until the issue is gone, then you know that is the one causing the problem.

Thank you, there seems to be no other way.

**Comment by askvortsov1** [comment] 2021-12-24 02:30
Closing as this isn't a core issue. Feel free to reopen if the issue persists on latest dev-master

**Closed by askvortsov1** 2021-12-24 02:30 UTC
