### ISSUE TITLE
SideNav: Icons and text are misaligned

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1484] opened 2018-07-03 19:52 UTC
## Bug Report

**Current Behavior**
The icons and the text ("All Discussions", "Categories" etc.) are not aligned well (see screenshots).

**Steps to Reproduce**
1. Go to the homepage
2. See bug.

**Expected Behavior**
Text should be aligned right to the center of the icons.

**Screenshots**

![5785678578](https://user-images.githubusercontent.com/17576065/42241556-aa6bac52-7f13-11e8-8877-72e21d071513.png) 

![213412341234](https://user-images.githubusercontent.com/17576065/42241558-ab9b533e-7f13-11e8-9015-10e27132bb05.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Comment by franzliedke** [comment] 2018-07-05 20:38
Nice catch! Definitely an issue.

**Comment by TurboProgramming** [comment] 2018-07-05 20:57
This issue is also applicable for others. Look at the screenshots below.

![456742567](https://user-images.githubusercontent.com/17576065/42347613-1603fe8c-80af-11e8-9a3b-9d4bc72ba7ee.png)

![12341234](https://user-images.githubusercontent.com/17576065/42347621-17a48cde-80af-11e8-9556-4388e33e338f.png)

Probably something related with the icons, or they use the same style and there is the error creating the same style for every vertical list with icons.

**Comment by TurboProgramming** [comment] 2018-07-07 18:59
So, we marked this as an issue but, what are we going to do about it? Any possible solutions in someones mind?

**Comment by franzliedke** [comment] 2018-07-08 22:54
@TurboProgramming I am very thankful for your detailed bug reports. They do help in making Flarum better.

However, please stop double posting and bumping your issues. To us, they are *not* more important (or urgent) than the 300 already created ones. The first items on our list of priorities are all related to [this milestone for the next release](https://github.com/flarum/core/milestone/6), which consists of very foundational changes to our extension infrastructure. This is at the top of our minds; and anything else reduces the limited time we have to spend on these.

Again, thanks for your contributions! You are more than welcome to start debugging these issues (or team up with other people from the community) and send pull requests once you find a fix. We will do our best to review as many of them as possible before the next release. But please respect our limited time and priorities that might be different from yours. This is a volunteer effort, constrained by family, work, and all the other fun things life brings along.

**Comment by TurboProgramming** [comment] 2018-07-09 20:04
@franzliedke I'm aware that I opened so many issues, but none of these issues are opened to be fixed **immediately** by **you**.  These issues are only to stay there and fixed by PRs, and to be fixed by you just if you have time or it's easy.

Not telling you but seeing these issues wouldn't help you in any ways, so I decided to send you every issue I find in Flarum, just send you a detailed report. Instead of just waiting in silence, I just wanted to contribute to have the stable release ASAP for everyone.

...and a suggestion of mine, after the stable release, many people will show interest to Flarum and will want to switch from other forum software to Flarum and we will need to work a lot more to improve this open source software to make it the best.

Still seeing lot's of community extensions, resources are generated at our community and happy to see these extensions.

You probably get what I've been doing the past days, and please just mark these as bugs in the issue tracker, maybe someone will come and fix them in the future :)

Hope you understand.

**Comment by luceos** [comment] 2018-07-09 20:18
@TurboProgramming although we fully understand your eagerness to contribute and we do appreciate the effort and time invested. Please also understand our standpoint, not all reported issues will be valid once we've finished overhauling the extension api, database structure, asset compilation and moved to webpack to name just a few imminent impacting changes. Many of the reported bugs will have to be triaged again to see whether they still affect the current __nightly__ (yes sorry that version), because in the end that is the version we're working on to release ASAP - given the time constraints previously given by Franz.

To be more factual; so far your reports have been of amazing quality; even though some were duplicates - heck that happens to me often enough. The thing that seemed to be a little too much was asking for action on the spot and bumping issues. In fact I've hidden a few of them while reading through my 45 GitHub notifications 😊 just to reduce the noise for the next (core) dev reading these issues.

So my advice here is; please have a little patience, we're doing our best to push forward. Doing some PRs by yourself will also bring you up to speed about we handle things and can empower you to work alongside us to the best of interest of Flarum as a project.

PS: glad to have you join in, some activity never hurt anyone 👍

**Comment by TurboProgramming** [comment] 2018-07-09 20:46
@luceos I'm glad and thankful that you understand the situation here.

I'll keep on reporting all other bugs I find but before reporting them:
- I will search all other issues with different phrases to be sure that no one hasn't reported them,
- I will show more attention to major bugs compared to minor ones as we have so many major ones.

I'll also try fixing my submitted issues with PRs (and maybe others too) so these issues were just the beginning of what I will do in the future.

I'm glad I joined in too, proud to help to open source software 💪

---

PS: Already started discussions with many software developers to switch over Flarum from Discourse for the stable release, after that, we will have at least 3 big software companies switching over. Just wanted to mention (I'm aware it's off topic 😆)

**Comment by TurboProgramming** [comment] 2018-07-22 12:56
I found a solution for this, but it's not working for all icons. I was only able to reproduce this fix with the tags icon and text at the sidebar.

So the fix is to insert `line-height: inherit;` as a style to the icon itself. 

Before:
![screenshot_2018-07-22 flarum community 1](https://user-images.githubusercontent.com/17576065/43045747-3a03a182-8dc7-11e8-9cdd-282475a0c43f.png)

After:
![screenshot_2018-07-22 flarum community](https://user-images.githubusercontent.com/17576065/43045746-38c0b260-8dc7-11e8-99be-98e2b2281a2d.png)

I would've opened a PR for this, but as it's not working for all, I wanted to also ask if you guys know any alternatives like this? Look at the screenshot below while I was applying the same fix to the following icon:

![screenshot_2018-07-22 flarum community 2](https://user-images.githubusercontent.com/17576065/43045783-9f1df068-8dc7-11e8-87cc-69990503f725.png)

**Closed** 2018-09-22 12:05 UTC
Labels: Good first issue, type/cleanup
