### ISSUE TITLE
Last user who replied not showed correctly on post list

### ISSUE THREAD

**Issue by Zeokat** [flarum/core#1187] opened 2017-05-17 22:37 UTC
## Bug report
- Version of Flarum: v0.1.0-beta.6 and development
- Website URL where the bug is visible: http://www.openconquer.com/beta/t/servidores-privados-de-conquista-2-0
**Checking the last reply author showed on post titled "ConquerItemPriceEditor", shows as author "dante0329" while the real one is "dranytico".**
- The webserver you are running: apache, nginx or something else
- PHP version: 7
- Hosted environment: shared or vps
- Hosting provider: N/A

## Flarum info

```
zeokat@ubuntu:/var/www/html/flarum$ php flarum info
Flarum core 0.1.0-beta.6
PHP 7.0.15-0ubuntu0.16.04.4
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
EXT flarum-approval v0.1.0-beta.6
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.6
EXT flarum-flags v0.1.0-beta.6
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
Base URL: http://192.168.247.128/flarum
Installation path: /var/www/html/flarum
```

## Additional comments
Check this post for more info about the bug: https://discuss.flarum.org/d/5797-help-verifying-one-bug-with-post-metadata

## Log files

```
N/A
```

**Comment by datitisev** [comment] 2017-05-17 22:42
In the example you gave of the "Flarum pronounciation" discussion, Flarum actually shows the person that started the discussion, and states it.

![img](https://i.imgur.com/T5uec4T.png)

Now, in the examples on the discussion, that is not the case. Just wanted to let you know :)

**Comment by Zeokat** [comment] 2017-05-17 22:53
Yep, @datitisev check new example. I made a mistake showing the example or check directly this post https://discuss.flarum.org/d/5797-help-verifying-one-bug-with-post-metadata

**Comment by Zeokat** [comment] 2017-05-18 12:47
Adding another example forum where happens exactly the same.
URl: https://huddleberry.com/t/interests
Into the discussion titled _"Let me show you how to preserve tomatoes for a year!"_ , the real user who added last reply is named _"Mariam"_. When you check the discussion list metadata, the user who added the last reply is _"Ajayi"_, wich is obviusly wrong.

**Comment by franzliedke** [comment] 2017-07-19 22:02
Has anybody found the root of this issue?

**Comment by franzliedke** [comment] 2017-07-19 22:04
And, more importantly, can this be reproduced on a fresh install of Flarum?

**Comment by Zeokat** [comment] 2017-07-19 22:14
@franzliedke I suffered this bug on a fresh version that i installed some time ago. Then i decided to check at another communities built with Flarum and found that the bug is present in most of forums out there.

Honestly i don' t know how to reproduce the bug, seems that happens randomly.

**Comment by franzliedke** [comment] 2017-07-19 22:15
Smells like something that only happens when updating a discussion's metadata (last poster ID etc.) fails, but post creation doesn't.

**Comment by pflstr** [comment] 2017-08-24 23:28
As far as I remember, I once noticed that approving a post, which was also the last post in a discussion, didn't update the information about the last poster in that discussion.

This however was in Beta 6 and I can't reproduce it anymore on the DevFlarum Sandbox Server. So maybe the issue has been adressed with the core of Beta 7 or the latest version of the flarum-approval extension.

Not sure, whether that helps.

**Comment by tobscure** [comment] 2017-08-25 00:14
@pflstr that [may indeed be the case](https://github.com/flarum/flarum-ext-approval/commit/a2813c7215c20c7871ede3b24a292fc3eef8efd1). Closing this, we can reopen if anyone manages to reproduce.

**Closed by tobscure** 2017-08-25 00:14 UTC
Labels: Bug
