### ISSUE TITLE
re-enable extensions in dual-column view

### ISSUE THREAD

**Issue by raafirivero** [flarum/core#2153] opened 2020-05-08 17:50 UTC
## Bug Report

**Current Behavior**
Not able to re-enable extensions within admin if it is in the Right column during dual-column view.

**Steps to Reproduce**
- go to Admin screen / Extensions page
- if extensions listed are in dual-column view, turn an extension off in the right column
- it will be greyed out and the check box to turn it back on will disappear.

- resize browser window so that extension list is a single column. all extensions are able to be enabled in this view.
**Expected Behavior**

- all extensions should be able to turn on and off in both views.

**Screenshots**

**Environment**
- Flarum version: 0.1.0-beta.13
- Website URL: [localhost testing]
- Webserver: apache
- Hosting environment: localhost
- PHP version: 7.3.16
- Browser: safari 13.1

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```
![column-disble](https://user-images.githubusercontent.com/6245124/81433571-c48a1f00-9132-11ea-8bc3-08d4a75f6d13.png)

**Comment by datitisev** [comment] 2020-05-08 18:15
I can't reproduce this. Can you check if there are any styles applied that hide the elements? Because they are still taking up the space.

**Comment by raafirivero** [comment] 2020-05-08 19:27
Just checked in Safari, Chrome, and Firefox. Can only reproduce the problem in Safari. (Re-checked Safari with all browser extensions turned off and it still reproduces the problem). Only thing I can see is that toggling the opacity declaration under this rule, it is visible when turned off. If opacity is set to less than 1 then it is completely invisible again in the right column (left column was always ok): 
```.ExtensionListItem.disabled .ExtensionListItem-title{
opacity: 0.5;
color: #996679;
}```

**Comment by datitisev** [comment] 2020-05-08 19:29
What's the selector for that CSS rule? @raafirivero. Also, I assume Safari on macOS?

**Comment by raafirivero** [comment] 2020-05-08 19:35
sorry, thought I pasted it above. selector is:
`.ExtensionListItem.disabled .ExtensionListItem-title {`

**Comment by datitisev** [comment] 2020-05-08 19:35
Is this possibly a Safari issue then?

**Comment by raafirivero** [comment] 2020-05-08 20:14
sounds like it - I hadn't checked all browsers when I first reported

**Comment by datitisev** [comment] 2020-05-08 20:15
Not sure if we want to close this - many people have had this issue and we might want a fix for it.

**Comment by raafirivero** [comment] 2020-05-08 20:17
OK - didn't want to clutter actual dev work with browser bugs --

**Comment by datitisev** [comment] 2020-05-08 20:19
No problem. Best to find a root cause before closing.

**Comment by askvortsov1** [comment] 2020-08-16 17:44
Still want this

**Comment by Ralkage** [comment] 2020-08-30 21:50
I would like to note that this is reproducible in the latest version of Chrome for Windows as well (Version 85.0.4183.83 (Official Build) (64-bit)).

With Firefox, it does it a bit different where it pushes the last item to the second column whereas in Chrome it just pushes the drop down menu of the last item onto the second column instead.

Below is me reproducing the same error on the latest version of Firefox Developer Edition (81.0b3 (64-bit) at the time of this comment) in the beta 13 demo site.

![2020-08-30_16-01-05](https://i.imgur.com/dSbmwrk.gif)

**Comment by askvortsov1** [comment] 2020-11-26 07:02
No longer applicable as of #2409

**Closed by askvortsov1** 2020-11-26 07:02 UTC
