### ISSUE TITLE
User Management is needed

### ISSUE THREAD

**Issue by humbletyrant** [flarum/core#1752] opened 2019-02-17 22:46 UTC
There is no way to view a list of user accounts within flarum.

This is desperately needed for moderation and community management purposes.

**Comment by datitisev** [comment] 2019-02-18 01:00
@humbletyrant As has been mentioned multiple times in the past, we don't want to include everything in core.

Adding those features that are widely requested in the community would decrease the time for the developers to update and improve Flarum, because they'd have to remember to maintain those features. Flarum is powered by its community of extension developers.

As [Toby mentioned in July 2015](https://discuss.flarum.org/d/415-media-upload-capabilities-in-core/7),
> When we consider what to add to core, popularity doesn't really come in to it at all. Core is about providing a solid _foundation_ on which extensions can build, rather than a default set of _features_.

Now, there are some user list and moderation extensions available for beta 7 that haven't been updated for beta 8 yet. I guess in that regard you'll just have to wait for someone to update them. And believe me, you won't be the only one waiting.

**Comment by jordanjay29** [comment] 2019-02-18 08:20
Although @datitisev's remarks apply here, I'm closing this as a duplicate of https://github.com/flarum/core/issues/283

**Closed by jordanjay29** 2019-02-18 08:20 UTC
