### ISSUE TITLE
Tags and Sticky: unable to hide from all discussions

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2522] opened 2021-01-04 23:34 UTC
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**

trying to do what suggested by the moderator Pollux https://discuss.flarum.org/d/133-super-sticky/79 never work.

1. You have a tag called sticky used for find sticky post. You have a tag called news for news post and you create a tag called hidden because you want some sticky post to be hidden in all discussions. You check the relative box to hide from all discussion in the tag called hidden.
2. A sticky post is sticky and assigned to the three tags.

**Expected Behavior**
Sticky post should be not listed in all discussions because one tag assigned has the option to hide from all discussion that should take priority on others tag.

**Environment**
- Flarum version: Beta 15
- Webserver: [e.g. apache] Apache
- Hosting environment: [e.g. shared, vps] VPS
- PHP version: 7.4
- Browser: [e.g. chrome 67, safari 11] Firefox 84.0.1

**Possible Solution**

Give priority to tags that has the hidden from all discussion checkbox.

**Additional Context**
https://discuss.flarum.org/d/133-super-sticky/78
https://discuss.flarum.org/d/133-super-sticky/80
https://discuss.flarum.org/d/133-super-sticky/81

**Comment by askvortsov1** [comment] 2021-01-05 06:42
Duplicate of https://github.com/flarum/core/issues/1833

**Closed by askvortsov1** 2021-01-05 06:42 UTC
Labels: needs-verification
