### ISSUE TITLE
404 Error Issue page that Displays

### ISSUE THREAD

**Issue by kenygamer** [flarum/core#1079] opened 2016-12-06 22:47 UTC
## Bug report
- Version of Flarum: 0.1.0-beta2.0
- Website URL where the bug is visible: https://community.survivaltimep.pe.com
- Apache/2.4
- PHP version: 5.5
- Hosted environment: Shared
- Hosting provider: https://www.hostinger.es

So When A 404 error hapenns you can see the following: community.survivaltimepe.com/Test So how to fix that and show the directory /error/404.html instead of it. thanks
``

**Comment by Luceos** [comment] 2016-12-08 14:45
Hello @kenygamer , as this is an older version any comment made my rely on a version that you have not installed. Nevertheless, custom error pages has been a feature request for a while, see:

- https://discuss.flarum.org/d/3544-please-help-me-configurate-custom-error-pages
- https://github.com/flarum/core/issues/596

With Flarum in development, it's only a matter of time that the feature will be made available. Patience and peace out :grin:

**Comment by jordanjay29** [comment] 2016-12-08 14:47
Duplicate of #596.

**Closed by jordanjay29** 2016-12-08 14:47 UTC

**Comment by franzliedke** [comment] 2016-12-28 22:22
@kenygamer You should be able to edit the files in the "errors" directory and see those changes without having to fiddle with .htaccess files. Does this work for you?

Besides that, as others have mentioned, we will make the default error pages look nice soon.
