### ISSUE TITLE
Tags bug: Nested tags jumping

### ISSUE THREAD

**Issue by maxyc** [flarum/core#371] opened 2015-08-30 17:46 UTC
Trouble!
If you do a lot of nested tags, they will start jumping from one tag to another.
Here for example https://spytajsie.com/t/dom-i-ogrod and http://novour.ru/t/computers-and-internet

![](http://cs625231.vk.me/v625231404/47a1f/1oc1GWN4tTA.jpg)

**Comment by modInfo** [comment] 2015-08-30 18:16
hopefully, it will quickly fixed, as well "like" buttons

**Comment by tobscure** [comment] 2015-08-30 23:16
This is a duplicate of #325, which we couldn't reproduce on the latest Chrome, but I think there must be more to it than that. I'm going to reopen that ticket.

**Closed by tobscure** 2015-08-30 23:16 UTC
