### ISSUE TITLE
Deleted topic notifications stay at the notification center

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1533] opened 2018-08-11 13:04 UTC
## Bug Report

**Current Behavior**
Deleted topic notifications are not deleted from the notification center.

**Steps to Reproduce**
1. Go to a topic
2. Post and get some notifications
3. Delete that topic
4. Open notification center and see error.

**Expected Behavior**
The notifications related to that topic should be deleted with the topic.

**Screenshots**

![screenshot_2018-08-11 flarum community](https://user-images.githubusercontent.com/17576065/43992002-2e639954-9d80-11e8-91f2-bc2697ad283d.png)

**Environment**
Flarum Community
https://discuss.flarum.org

---

Related: https://github.com/flarum/core/issues/913 (I'm not sure about them but https://github.com/flarum/core/pull/1027 and https://github.com/flarum/core/pull/1026 can be related too.)

**Comment by datitisev** [comment] 2018-08-11 13:52
Duplicate of https://github.com/flarum/core/issues/1380.

**Closed** 2018-08-11 14:32 UTC
