### ISSUE TITLE
Flarum leaks password when it can't connect to the database

### ISSUE THREAD

**Issue by Cadiducho** [flarum/core#1421] opened 2018-05-05 15:49 UTC
## Explanation

When the forum can't connect to the database (for example, mysql server is down), the exception leaks all the config related to mysql, including username and **password**
_PDO->__construct('mysql:host=127....', 'fakeUsername', 'fakePassword', Array)_ is shown at least three times

## Technical details

- Version of Flarum:  0.1.0-beta.7
- Website URL where the bug is visible: https://edoras.es/foro (not now that the db is back online)
- The webserver you are running: [caddy](https://caddyserver.com/)
- PHP version: 7.1.17
- Hosted environment: vps
- Hosting provider: http://ovh.com

## Flarum info

```

Flarum core 0.1.0-beta.6
PHP 7.1.17
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, mcrypt, mysqlnd, odbc, PDO, Phar, posix, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, PDO_ODBC, pdo_sqlite, wddx, xmlreader, xmlrpc, Zend OPcache
EXT flagrow-analytics 0.5.0
EXT flarum-approval v0.1.0-beta.6
EXT flarum-bbcode v0.1.0-beta.5
EXT sijad-details 0.1.2
EXT flarum-emoji v0.1.0-beta.6
EXT clarkwinkelmann-emojionearea 0.1.2
EXT flarum-flags v0.1.0-beta.6
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT xengine-markdown-editor 1.3.1
EXT flarum-mentions v0.1.0-beta.7
EXT sijad-pages 0.1.0-beta.3
EXT davis-securehttps 0.1.0-beta5
EXT avatar4eg-share-social 0.2.3
EXT davis-socialprofile 0.2.3
EXT flarumes-spanish v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
EXT avatar4eg-users-list 0.1.1
Base URL: https://edoras.es/foro
Installation path: /var/www/edoras/foro
```

## Log files

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'fakeUsername'@'localhost' (using password: YES) in /var/www/edoras/foro/vendor/illuminate/database/Connectors/Connector.php:55 Stack trace: #0 /var/www/edoras/foro/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=127....', 'fakeUsername', 'fakePassword', Array) #1 /var/www/edoras/foro/vendor/illuminate/database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array) #2 /var/www/edoras/foro/vendor/illuminate/database/Connectors/ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #3 /var/www/edoras/foro/vendor/illuminate/database/Connectors/ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array) #4 /var/www/edoras/foro/vendor/flarum/core/src/Database/DatabaseServiceProvider.php(29): Illuminate\Database\Connectors\ConnectionFactory->make(Array) #5 in /var/www/edoras/foro/vendor/illuminate/database/Connectors/Connector.php on line 55
05/May/2018:17:45:17 +0200 [ERROR 0 /foro/] PHP message: PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'fakeUsername'@'localhost' (using password: YES) in /var/www/edoras/foro/vendor/illuminate/database/Connectors/Connector.php:55 Stack trace: #0 /var/www/edoras/foro/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=127....', 'fakeUsername', 'fakePassword', Array) #1 /var/www/edoras/foro/vendor/illuminate/database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array) #2 /var/www/edoras/foro/vendor/illuminate/database/Connectors/ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #3 /var/www/edoras/foro/vendor/illuminate/database/Connectors/ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array) #4 /var/www/edoras/foro/vendor/flarum/core/src/Database/DatabaseServiceProvider.php(29): Illuminate\Database\Connectors...
```
This is shown at the web browser to all the clients that connects to the forum when it can't connect
Yes, the username and password are changed to recreate the bug

**Comment by franzliedke** [comment] 2018-05-05 16:31
Debug mode should not be enabled on production systems, for exactly this reason. (It can also expose other sensitive information.) If that is the case here, this is a non-issue.

We might be able to make this more clear, both in config.php (comments), the installer and the documentation. Feel free to send PRs to improve this.

**Comment by franzliedke** [comment] 2018-05-05 16:32
We can also make this clearer in the output of `php flarum info` (which, in latest dev-master, already shows whether debug mode is enabled or not).

**Comment by Cadiducho** [comment] 2018-05-05 19:05
Well, it seems like debug mode was enabled but I disabled it in the config and the sensitive info is still shown :(

**Comment by luceos** [comment] 2018-05-05 20:03
Are you sure your page isn't cached, eg via CloudFlare?

**Comment by franzliedke** [comment] 2018-05-05 20:38
How exactly is the error displayed? If it is a Whoops error page, then that should only be visible in debug mode.

**Comment by datitisev** [comment] 2018-05-07 00:46
@ItzZuga If it looks like the following image, then it's a Whoops error page, which means it's in debug mode.
[![demo](https://filp.github.io/whoops/screen.png)](http://filp.github.io/whoops/demo/)

**Comment by Cadiducho** [comment] 2018-05-07 09:44
No, it's not that debug page. It's a blank page with an PDOException
Exactly like this 
![foro](https://user-images.githubusercontent.com/3594924/39695768-fa57d984-51eb-11e8-9782-914026291662.png)

**Comment by luceos** [comment] 2018-05-07 09:58
I just tested this locally with master, phpunit, php 7.1. And the password is not shown, all other information is though. Catching that exception and making it more generic makes sense.

**Comment by franzliedke** [comment] 2018-05-07 14:47
I think in that case we don't need special treatment for this particular exception, but rather find out (and fix) why our usual exception treatment does not kick in here. Probably too early in the request life cycle?

**Comment by luceos** [comment] 2018-05-07 18:45
An ErrorHandler is enabled through the ApiServerProvider, but I haven't seen anything enabled for Http or globally.

**Comment by sijad** [comment] 2018-06-07 13:43
I can't reproduce it in master version, although a page called `Update Flarum` shows up, and asks for database password to perform update, after entering the password an error appears.

![image](https://user-images.githubusercontent.com/7693001/41103462-76651208-6a7e-11e8-9c2a-2313855bac78.png)


I guess in cases of failure connection an error page should appears instead?

**Comment by tobscure** [comment] 2018-07-20 01:40
Can confirm @sijad's findings. This is happening because the first place we try to hit the database in a request is in `Application::isUpToDate`, where we call `$settings->get('version')`; however, this is wrapped in a `try` block so the connection error is suppressed and the request proceeds as though Flarum is not up-to-date.

I think this issue should be addressed as part of #1416, or we should wait for it to be merged before working out a solution.

**Comment by franzliedke** [comment] 2018-07-21 20:44
Yep, indeed. There might be a more straight-forward fix when the sites refactoring is done.

**Comment by franzliedke** [comment] 2018-08-30 18:20
Can anybody still reproduce the original issue with the latest dev-master branch?

**Comment by gooof** [comment] 2018-08-30 20:00
Still exists, you only have to change the db password.
![error](https://i.imgur.com/WaKTD6G.jpg)

**Comment by datitisev** [comment] 2018-08-30 20:16
Can confirm @gooof's findings. Only way to fix would be to make the error handler handle this exception, and maybe hide the stacktrace on this specific instance, just in acse.

**Comment by luceos** [comment] 2018-08-31 18:57
The only place the password will be shown is during this connection call. We could easily catch this PDOException and throw a different one `IncorrectDatabaseCredentialsException` or something.

**Comment by franzliedke** [comment] 2018-09-03 21:58
I'm on it.

The problem here is the difference between the two phases of booting Flarum: booting and request handling. We only set up exception handling for the latter, while the exception here happens during the former. Technically speaking, every time we boot Flarum we handle a request (except for setups with things like PPM, where one app instance could handle multiple requests, so I do not want to make that assumption yet). So I need to wrap the boot process for web requests (it doesn't matter when running the CLI via `php flarum`) in a `try`/`catch`, but I am trying to find a better way to do that than doing it directly in `public/index.php`.

**Comment by gooof** [comment] 2018-09-04 05:11
That sound complicated. Setting own error handling before doing anything else prevents this error. 
```php
function flarum_exception_handler($exception) {
  echo "Flarum Fatal Error: " , $exception->getMessage(), "\n";
  exit;
}
set_exception_handler('flarum_exception_handler');
```

**Comment by franzliedke** [comment] 2018-09-21 21:36
Done. Please note that you need to update the skeleton (flarum/flarum) as well.

**Closed** 2018-09-21 21:36 UTC
