### ISSUE TITLE
If it's sticked, it must be on top , why it's sorted 

### ISSUE THREAD

**Issue by thuanpq** [flarum/core#928] opened 2016-04-13 01:32 UTC
<img width="939" alt="screen shot 2016-04-13 at 8 31 20 am" src="https://cloud.githubusercontent.com/assets/6512225/14480350/35d9264e-0152-11e6-80db-7e7cb9ac0f6c.png">

**Comment by datitisev** [comment] 2016-04-13 01:33
@thuanpq When it is stacked and you are NOT logged in, they will be at the top.
If you are logged,p in, and have read the entire discussion, then they will get sorted, because there is nothing for you to read there anymore.
Would you like to scroll 5 sticky discussions on mobile when you have read them? No

It is better for UX

**Comment by thuanpq** [comment] 2016-04-13 02:52
oh, it does not make sense, once it's sticked, it's important then it must be always on top for me and everyone always see it. It look like when you want to note something to remind you everytime you access forum.

**Comment by franzliedke** [comment] 2016-04-13 03:00
@thuanpq I'm closing this. This works just like intended - check out the discussion [here](https://discuss.flarum.org/d/133-super-sticky).

For the future, if you create issues, please provide proper descriptions so that we know what the issue is about. And before that, please search both the issues and our support forums to see whether something like this has already been discussed.

**Closed by franzliedke** 2016-04-13 03:00 UTC
