### ISSUE TITLE
[nicknames] User\Content not able to load user based on %20 nickname

### ISSUE THREAD

**Issue by luceos** [flarum/core#2518] opened 2020-12-29 08:14 UTC
## Bug Report

**Current Behavior**

When allowing spaces in nicknames, user profiles no longer load if you hit the backend for it (Content). From the SPA it does work, but refreshing any profile fails.

**Steps to Reproduce**
1. Enable nicknames, don't use any regex
2. Go to your profile/settings, change your nickname to "John Doe"
3. Go to your profile, it works
4. Refresh

**Expected Behavior**

Profile should be shown. Instead a 404 happens.

**Environment**
- Flarum version: v0.1.0-beta.15

**Possible Solution**

Probably User\Content needs to urldecode or something.

**Additional Context**

**Comment by SychO9** [comment] 2020-12-29 08:55
I can't reproduce, are you just refreshing the page or are you modifying the URL ? the URL still uses the username.

**Comment by luceos** [comment] 2020-12-29 09:01
I cannot reproduce anymore either 🙈

**Comment by luceos** [comment] 2020-12-30 09:37
Here's an example:

- ERROR: https://buzztalk.buzzlync.com/u/Jordan%20Danton
- WORKS: https://buzztalk.buzzlync.com/d/92, click OP

**Comment by SychO9** [comment] 2020-12-30 10:11
Oh, the nickname extension was never made to load profiles from the nickname, it makes no change to the url of profiles.

So the issue here is that the frontend is creating wrong user URLs. It should by default still use usernames.

**Comment by luceos** [comment] 2020-12-30 12:45
@SychO9 reproduce:

- visit https://buzztalk.buzzlync.com/d/92
- click Jordan (display name)
- you are now on https://buzztalk.buzzlync.com/u/Jordan%20Danton
- refresh the page, 404

**Comment by SychO9** [comment] 2020-12-30 12:51
Sorry I meant locally, I can see the issue on the forum you're linking to, I just can't seem to reproduce it locally.

**Comment by tankerkiller125** [comment] 2020-12-30 14:25
I'll admit I never tested it with spaces, but it would be correct that the URLs linked should still be the username itself and not the nicknames (which I did verify during testing) I wonder if a different extension some how is causing issues?

**Comment by askvortsov1** [comment] 2021-01-05 00:21
Can't reproduce either on a controlled environment, but all link generation in core seems to use username(), not displayName().

**Comment by askvortsov1** [comment] 2021-01-27 05:27
Closing as this seems to be a rogue extension. If someone can reproduce this, please feel free to say so / reopen

**Closed by askvortsov1** 2021-01-27 05:27 UTC
Labels: type/bug
