### ISSUE TITLE
Not scrolling up when a new tag list page is loaded from mobile dropdown

### ISSUE THREAD

**Issue by nitaaikumar** [flarum/core#1951] opened 2019-12-07 06:45 UTC
There seems to be quite an important bug in mobiles (both android and ios). I don't know if it has been introduced in Beta 11 or if it was there in Beta 10 also.

If we are scroll down in the All Discussions list index page and then change the tag from the top dropdown on mobile devices then it does not jump to the top of the tag page as it should and it stays at the bottom scrolled position.

This may be quite confusing for the mobile user who may not know what has happened if he/she does not try to scroll up again when the tag page loads, especially if that tag has less number of posts than the All Discussions index page, then all one could see is the footer when the tag is changed in the dropdown.

**Comment by franzliedke** [comment] 2020-01-03 14:29
I cannot reproduce this with Firefox on Android.

Do you see this issue at https://discuss.flarum.org/ or https://beta.flarum.site/?

**Comment by askvortsov1** [comment] 2020-07-29 02:57
I can confirm this on discuss.flarum.org with Chrome on Android.

**Comment by tankerkiller125** [comment] 2020-07-29 12:26
@askvortsov1 how far down did you scroll, I'm on Android 10 with latest Chrome and Chrome Dev and I was unable to replicate the issue scrolling down to hit "load more" twice.

**Comment by askvortsov1** [comment] 2020-07-29 12:30
When testing yesterday, I scrolled all the way down but didn't hit load more at all. That being said, when I went to test again now, it worked as expected, except for one time. So it's one of _these_ bugs...

**Comment by askvortsov1** [comment] 2020-10-17 17:51
Closed in https://github.com/flarum/core/commit/1936b9117ded44be291cb002c734081497933e13

**Closed by askvortsov1** 2020-10-17 17:51 UTC
Labels: type/bug
