### ISSUE TITLE
Post time/date issue

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1534] opened 2018-08-11 22:35 UTC
## Bug Report

**Current Behavior**
Sometimes (after an edit, refresh not sure) the time/date becomes 2 in a row for some reason.

**Steps to Reproduce**
1. Go to a topic
2. Reply and edit a post
3. Do some stuff that I'm not sure about it
4. See error (If you can't reproduce it, just wait a few mins, play around with the screen and it will eventually happen once, I was able to reproduce it 4 times till now)

**Expected Behavior**
The time/date should be only one.

**Screenshots**

![screenshot_2018-08-12 levels ranks by reflar - flarum community](https://user-images.githubusercontent.com/17576065/43996655-f0c228ae-9dcf-11e8-844f-202db8584cb4.png)

![screenshot_2018-08-12 levels ranks by reflar - flarum community 1](https://user-images.githubusercontent.com/17576065/43996657-f20272be-9dcf-11e8-82d1-d0f16defb8be.png)

I took these hard, they disappear after a few seconds.

**Environment**
Flarum Community
https://discuss.flarum.org

**Comment by tobscure** [comment] 2018-08-12 03:48
Duplicate of #1087

**Closed by tobscure** 2018-08-12 03:48 UTC
