### ISSUE TITLE
"Crash" on topic read

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#210] opened 2015-08-02 14:09 UTC
See screenshot. Got it when clicking  on post under user profile.

![screen shot 2015-08-02 at 10 06 39](https://cloud.githubusercontent.com/assets/8352292/9026474/7dcefda6-38fe-11e5-9d6a-f6887e61fec7.png)

Go to Toby's [profile discussions](http://discuss.flarum.org/u/Toby/discussions) list, then click on first one.

**Comment by tobscure** [comment] 2015-08-02 23:32
Duplicate of #208

**Closed by tobscure** 2015-08-02 23:32 UTC
