### ISSUE TITLE
MySQL 8.x Cause Crashes

### ISSUE THREAD

**Issue by digitalam025** [flarum/core#2930] opened 2021-06-21 07:09 UTC
## Bug Report

**Current Behavior**
Only the header is present after loading for a long while.

**Steps to Reproduce**
1. Install MySQL 8.0.21 and local server (Wamp for me)
2. Make a request to the server (Visiting the site, logging in, logging out etc.)

**Expected Behavior**
The forum to load, with data displayed.

**Environment**
- Flarum version: 1.0.2
- Website URL: http://forum.dev
- Webserver: Apache
- PHP version: 7.4.9
- Browser: Chrome 91

```
Flarum core 1.0.2
PHP version: 7.4.12
Loaded extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, xmlreader, xmlwriter, curl, fileinfo, gd, mbstring, Phar, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, sqlite3
+----------------------+---------+--------+
| Flarum Extensions    |         |        |
+----------------------+---------+--------+
| ID                   | Version | Commit |
+----------------------+---------+--------+
| flarum-flags         | v1.0.0  |        |
| fof-passport         | 1.0.0   |        |
| flarum-tags          | v1.0.3  |        |
| flarum-suspend       | v1.0.0  |        |
| flarum-subscriptions | v1.0.0  |        |
| flarum-sticky        | v1.0.0  |        |
| flarum-statistics    | v1.0.0  |        |
| flarum-mentions      | v1.0.0  |        |
| flarum-markdown      | v1.0.1  |        |
| flarum-lock          | v1.0.0  |        |
| flarum-likes         | v1.0.0  |        |
| flarum-lang-english  | v1.0.0  |        |
| flarum-emoji         | v1.0.0  |        |
| flarum-bbcode        | v1.0.0  |        |
| flarum-approval      | v1.0.0  |        |
+----------------------+---------+--------+
Base URL: http://flarum
Installation path: E:\wamp64\www\flarum
Debug mode: ON
Don't forget to turn off debug mode! It should never be turned on in a production system.
```

**Possible Solution**
By downgrading MySQL version to 5.7.34 from 8.0.21.

**Additional Context**
Console output: 
```TypeError: can't access property "type", t is undefined```

Flarum.log: 
```Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.``` (Because MySQL had already crashed)

**Comment by matteocontrini** [comment] 2021-06-21 21:32
Duplicate of #2921, which should probably get some attention.

**Comment by davwheat** [comment] 2021-06-21 21:41
Closing as duplicate of #2921.

**Closed by davwheat** 2021-06-21 21:41 UTC
