### ISSUE TITLE
[Tags] Include Primary when creating new discussion under Secondary tag

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#424] opened 2015-09-04 03:58 UTC
Apologies if there's already an issue for this. I searched but didn't find anything that seemed 

Let's say you're viewing "Dev > l18n" when you decide to create a new discussion.

Click! ... The "l18n" tag is automatically applied to the new discussion, but the "Dev" tag is not. (But if you click the "l18n" tag to edit the tag settings, the "Dev" tag is automatically added at that point.) It would be nice if the Primary tag and Secondary tag were both applied off the bat.

PS: I really like how the tag selection/editing works now!

**Comment by tobscure** [comment] 2015-09-04 03:59
Duplicate of #323... but yours has a much better description, so I'm going to close that one in favour of this one :)

**Comment by DCSJAPAN** [comment] 2015-09-04 04:40
Sorry again about the duplication!

... How strange, that #424 should be a duplicate of #323!

**Closed** 2015-12-11 20:14 UTC
Labels: Bug
