### ISSUE TITLE
Number of unread posts counts the deleted posts

### ISSUE THREAD

**Issue by ghost** [flarum/core#1968] opened 2020-01-16 08:07 UTC
## Bug Report

**Current Behavior**
As of now, if a discussion has say 25 posts with 5 of them deleted, the number of unread posts in total should be 20. But the number of unread posts still show 25.

**Steps to Reproduce**
1. Go to 'https://beta.flarum.site'
2. Create an account and add a discussion.
3. Add a couple of replies and delete a few of those replies them.
4. Register a new user and note the number of unread posts before opening the discussion.

**Expected Behavior**
I expect the number of unread discussions to be excluding the deleted posts.

**Screenshots**

The image bellow shows that I created a few posts and deleted 2 of them. A total of 8 posts (including the deleted):

![Screenshot from 2020-01-16 13-22-09](https://user-images.githubusercontent.com/53521400/72504783-85bf1900-3864-11ea-8e9e-51cc16478e56.png)

This image shows the number of unread posts for a new user *Test Discussion*:

![Screenshot from 2020-01-16 13-23-37](https://user-images.githubusercontent.com/53521400/72504864-b56e2100-3864-11ea-9626-3dc344c0302f.png)

This image shows the total number of actual posts when the new user clicks the discussion:

![Screenshot from 2020-01-16 13-23-50](https://user-images.githubusercontent.com/53521400/72504925-d9c9fd80-3864-11ea-906e-06964dbcbc84.png)

**Comment by askvortsov1** [comment] 2021-01-27 05:30
Duplicate of https://github.com/flarum/core/issues/2240

**Closed by askvortsov1** 2021-01-27 05:30 UTC
