### ISSUE TITLE
Crash with 2 accounts in 2 tabs

### ISSUE THREAD

**Issue by Jump3r99** [flarum/core#700] opened 2016-01-01 13:46 UTC
log in to accout with lower permissions
go to topic (I didn't try it on closed)
log in to mod account (editing, removing posts)
go to same topic
log out account with lower perm
![l](https://cloud.githubusercontent.com/assets/12465392/12071022/f9bb3eb6-b095-11e5-885a-d54cba6f4098.png)

**Comment by tobscure** [comment] 2016-01-01 23:06
Is this running beta 4 or dev-master?

**Comment by Jump3r99** [comment] 2016-01-02 08:24
Beta4

**Comment by Averell7** [comment] 2016-01-05 21:25
I got the same problem, and additionally it make the forum inaccessible to the lower perm account. When trying to log this account, blank page with only the title. I deleted all cookies to no avail. I have not yet found the exact source of the problem. 
Tested with IE and Firefox with the same result

**Comment by tobscure** [comment] 2016-01-07 02:11
I believe this has been fixed in dev-master.

**Closed by tobscure** 2016-01-07 02:11 UTC
Labels: Backend, Bug

**Comment by Averell7** [comment] 2016-01-08 12:35
The problem itself, maybe. The consequence I encounter : probably not. The error is the following : 
When I access Flarum, only the title appears, the rest of the page is blank. 

Reason :
TypeError: data is null
forum-12bf8025.js:30960:17
Code is : 
          key: 'pushObject',
          value: function pushObject(data) {
            if (!this.models[data.type]) return null;

This code appears 3 times : 
in core/js/admin/dist/apps.js
    core/js/forum/dist/apps.js
   core/js/lib/Store.js

I understand it comes from an error in the database, corrupted by the error above. But wouldn't it be prudent to protect a little bit more this line with something like : 
      if ((this.models[data] == null) or  ((!this.models[data.type])) return null;
(Sorry I am a Python programmer, I don't know anything about js, but you will get the idea)

N.B. : This is not a problem for me, I am on an experimental platform. I can correct this for me, but I wanted to know the reason of the problem. You do what you want with it. 
Best Regards

**Comment by tobscure** [comment] 2016-01-10 21:57
Are you using PHP 7? There's a separate issue for that: #685

**Comment by Averell7** [comment] 2016-01-11 01:52
No we are in PHP 5.5
But I cannot give any help now that the problem has disappeared because I had to move to another host, and several other changes. I am no longer able to reproduce the problem neither to understand why it has disappeared. Sorry. 
So on my side the question should be considered as closed. If it happens again, I will tell you. Thanks
