### ISSUE TITLE
flarum.settings doesn't exist

### ISSUE THREAD

**Issue by Nobabs27** [flarum/core#1260] opened 2017-10-22 04:50 UTC
## Explanation

On install it (flarum) generates this SQL error:
```
Something went wrong: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.settings' doesn't exist (SQL: select exists(select * from `settings` where `key` = version) as `exists`)
```

If the install button is clicked again, it generates this error:
```
Something went wrong: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migrations' already exists (SQL: create table `migrations` (`migration` varchar(255) not null, `extension` varchar(255) null) default character set utf8mb4 collate utf8mb4_unicode_ci)
```

## Technical details

- Version of Flarum:  v0.1.0-beta.7
- The webserver you are running: nginx
- PHP version: 7.1.10
- Hosted environment: a virtual machine

## Flarum info

```
 php flarum info
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_bz2.dll' - Error loading shared library /usr/lib/php7/modules/php_bz2.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_curl.dll' - Error loading shared library /usr/lib/php7/modules/php_curl.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_fileinfo.dll' - Error loading shared library /usr/lib/php7/modules/php_fileinfo.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_ftp.dll' - Error loading shared library /usr/lib/php7/modules/php_ftp.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_gd2.dll' - Error loading shared library /usr/lib/php7/modules/php_gd2.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_gettext.dll' - Error loading shared library /usr/lib/php7/modules/php_gettext.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_gmp.dll' - Error loading shared library /usr/lib/php7/modules/php_gmp.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_intl.dll' - Error loading shared library /usr/lib/php7/modules/php_intl.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_imap.dll' - Error loading shared library /usr/lib/php7/modules/php_imap.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_interbase.dll' - Error loading shared library /usr/lib/php7/modules/php_interbase.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_ldap.dll' - Error loading shared library /usr/lib/php7/modules/php_ldap.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_mbstring.dll' - Error loading shared library /usr/lib/php7/modules/php_mbstring.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_exif.dll' - Error loading shared library /usr/lib/php7/modules/php_exif.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_mysqli.dll' - Error loading shared library /usr/lib/php7/modules/php_mysqli.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_oci8_12c.dll' - Error loading shared library /usr/lib/php7/modules/php_oci8_12c.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_openssl.dll' - Error loading shared library /usr/lib/php7/modules/php_openssl.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_pdo_firebird.dll' - Error loading shared library /usr/lib/php7/modules/php_pdo_firebird.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_pdo_mysql.dll' - Error loading shared library /usr/lib/php7/modules/php_pdo_mysql.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_pdo_oci.dll' - Error loading shared library /usr/lib/php7/modules/php_pdo_oci.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_pdo_odbc.dll' - Error loading shared library /usr/lib/php7/modules/php_pdo_odbc.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_pdo_pgsql.dll' - Error loading shared library /usr/lib/php7/modules/php_pdo_pgsql.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_pdo_sqlite.dll' - Error loading shared library /usr/lib/php7/modules/php_pdo_sqlite.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_pgsql.dll' - Error loading shared library /usr/lib/php7/modules/php_pgsql.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_shmop.dll' - Error loading shared library /usr/lib/php7/modules/php_shmop.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_soap.dll' - Error loading shared library /usr/lib/php7/modules/php_soap.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_sockets.dll' - Error loading shared library /usr/lib/php7/modules/php_sockets.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_sqlite3.dll' - Error loading shared library /usr/lib/php7/modules/php_sqlite3.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_tidy.dll' - Error loading shared library /usr/lib/php7/modules/php_tidy.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_xmlrpc.dll' - Error loading shared library /usr/lib/php7/modules/php_xmlrpc.dll: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/php_xsl.dll' - Error loading shared library /usr/lib/php7/modules/php_xsl.dll: No such file or directory in Unknown on line 0

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "info" is not defined.                                  
                                                                 
```

**Comment by IMsCrystal** [comment] 2017-10-22 04:58
Exactly what he said! I would appreciate if you could fix this issue or help us out! :D

**Comment by sanjibnarzary** [comment] 2017-10-25 02:18
Install the required libraries php-curl, php-intl,php-pdo, etc as mentioned in the installation docs

**Comment by gwillem** [comment] 2017-12-15 19:59
This issue should be closed as the cause is not with flarum.

**Closed** 2017-12-15 20:13 UTC

**Comment by Nobabs27** [comment] 2017-12-17 02:55
I believe the issue was that Flarum does not support MariaDB?

**Comment by dav-is** [comment] 2017-12-17 06:12
@Nobabs27 Theres no reason Flarum shouldn’t work with MariaDB and I can confirm I’ve used it with MariaDB in the past. Check your configuration.

**Comment by luceos** [comment] 2017-12-18 07:10
Just to make the reason for closing an @gwillem 's comment more obvious.

If you look at the output of `php flarum info` you will see a trace of errors starting with `PHP Warning:  PHP Startup: Unable to load dynamic library`. Although these are mere warnings, they point to a misconfiguration of php. Flarum requires several php extensions of which `php_pdo_mysql` is just one, allowing PHP to connect to a MySQL database.

The fix lies in properly configuring PHP.
