### ISSUE TITLE
Blank screen if no mentions are available on the mentions tab (profile)

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1489] opened 2018-07-03 20:59 UTC
## Bug Report

**Current Behavior**
If nobody mentioned you so far, the mentions tab page will be shown blank instead of a information text that warns the user that he/she hasn't been mentioned so far like the "no discussions on this category" warning.

**Steps to Reproduce**
1. Go to your profile
2. Click on mentions (nobody should mention you)
3. See error

**Expected Behavior**
The user should be presented with an information text like below.

![screenshot_2018-07-03 splash community 1](https://user-images.githubusercontent.com/17576065/42244246-f0f89bae-7f1c-11e8-8e1d-98b438e7daf5.png)

---

**Screenshots**

![screenshot_2018-07-03 turboprogramming - flarum community](https://user-images.githubusercontent.com/17576065/42244276-104c2426-7f1d-11e8-8b4d-80110bed47ee.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Add an information message warning the user that he or she hasn't mentioned anywhere around the community.

**Comment by franzliedke** [comment] 2018-07-05 20:17
Closing this as duplicate of #596

**Closed by franzliedke** 2018-07-05 20:17 UTC
