### ISSUE TITLE
Restricted permission to start a new discussion is flawed

### ISSUE THREAD

**Issue by pflstr** [flarum/core#1233] opened 2017-08-31 09:00 UTC
## Bug report
- Version of Flarum: 0.1.0-beta.7
- Website URL where the bug is visible: https://devflarum.xyzz.work

## Additional comments
I set the permissions, so that globally all members are allowed to start new discussions, but only e.g. mods are allowed to do so in a specific tag. If a non priviledged user enters said tag, the button ``Start a discussion`` looks as if one where allowed to do so (I would expect ``Can't start discussion``). If the user then tries to submit such a discussion, he can't do that being noticed ``You do not have permission to do that.``

If the same settings apply to reply to discussions, everything is fine (``Can't reply``).

**Comment by askvortsov1** [comment] 2020-10-02 06:10
Duplicate of https://github.com/flarum/core/issues/1696 and https://github.com/flarum/core/issues/2149

**Closed by askvortsov1** 2020-10-02 06:10 UTC
Labels: type/bug
