### ISSUE TITLE
Side nav does not collapse early enough on tags page

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1486] opened 2018-07-03 20:01 UTC
## Bug Report

**Current Behavior**
"All Discussions", "Tags" etc. buttons don't collapse and use a lot of unnecessary space while viewing only the tags.

**Steps to Reproduce**
1. Go to homepage
2. Click on tags
3. See error

**Expected Behavior**
The buttons should horizontally align to save space for sub-tags hiding at the bottom.

**Screenshots**
![screenshot_2018-07-03 flarum community 7](https://user-images.githubusercontent.com/17576065/42241923-ecb9fd88-7f14-11e8-988e-2d34c007a3df.png)

![screenshot_2018-07-03 flarum community 8](https://user-images.githubusercontent.com/17576065/42241928-eeb79000-7f14-11e8-8458-6b05bce6234f.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Align the "All Discussions", "Tags" etc. buttons horizontally to save space.

**Comment by franzliedke** [comment] 2018-07-05 09:44
I am *thinking* the problem is that these media queries do not match up:

- https://github.com/flarum/flarum-ext-tags/blob/03613432cb5e944c6387f1a652942dbbe5713370/less/forum.less#L33
- https://github.com/flarum/flarum-ext-tags/blob/03613432cb5e944c6387f1a652942dbbe5713370/less/forum.less#L57
- https://github.com/flarum/core/blob/00bc8fc0bc63643ec850f5d5eec78701225b7f7b/less/common/sideNav.less#L91

Again, let's wait for input from Toby.

**Comment by TurboProgramming** [comment] 2018-07-05 09:49
@tobscure

**Comment by TurboProgramming** [comment] 2018-07-05 09:50
@franzliedke What about this: https://github.com/flarum/core/issues/1487?
This seems to be a related issue with that.

**Comment by franzliedke** [comment] 2018-07-05 10:01
@TurboProgramming No need to tag us, we get notifications for all these issues anyway. Toby is currently away, he will respond in due time.

**Comment by TurboProgramming** [comment] 2018-07-05 16:03
I tested this with Flarum Beta 7 and it works well:

![screenshot_2018-07-05 appybuilder community](https://user-images.githubusercontent.com/17576065/42334489-03e9221e-8086-11e8-8c1a-29cb949dd9bb.png)

This is a bug introduced now and only applies for the dev channel. Did you apply any changes regarding this area that might produce this kind of bug?

**Comment by TurboProgramming** [comment] 2018-07-05 16:09
I tested this with Flarum Beta 7 and this bug does not exist.

![screenshot_2018-07-05 appybuilder community](https://user-images.githubusercontent.com/17576065/42334793-f1b9f9c8-8086-11e8-9e41-e99a8799b32f.png)


This is a bug introduced now and only applies for the dev channel. Did you apply any changes regarding this area that might produce this kind of bug?

**Comment by franzliedke** [comment] 2018-07-05 19:09
It's very likely due to this commit:
https://github.com/flarum/core/commit/2754a8c8671a404a3d69bc80cf45d7e99559052c#diff-93b414f6d55b496ad059b915e608df03

**Comment by TurboProgramming** [comment] 2018-07-05 19:44
So what should we do to bring this back?

**Comment by franzliedke** [comment] 2018-07-05 20:06
You can

- either wait for some input from Toby, or
- investigate the changes, try them out and see which part of the change caused the bug.

**Comment by TurboProgramming** [comment] 2018-07-05 21:03
Let's wait @tobscure.

**Comment by tobscure** [comment] 2018-07-13 08:55
Slating this for beta 8 as it's a regression.

**Comment by tobscure** [comment] 2018-07-20 02:16
Fixed in https://github.com/flarum/core/commit/7b802a76ba0f5c61b8720a839a37580cfe4e71d5

**Closed by tobscure** 2018-07-20 02:16 UTC
Labels: Bug, Frontend
