### ISSUE TITLE
Login/Signup Error

### ISSUE THREAD

**Issue by ExZiByte** [flarum/core#1386] opened 2018-03-12 06:42 UTC
I was told to create this issue on GitHub by @luceos 

## Explanation

Can't Login or Sign up on my forum

## Technical details

- Version of Flarum: 0.1.0 Beta 7
- Website URL where the bug is visible: https://trigonmc.com/forums
- Apache
- PHP version: 7.1.15
- Hosted environment: VPS
- Hosting provider: DigitalOcean

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 7.1.15-1+ubuntu17.10.1+deb.sury.org+2
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: https://trigonmc.com/forums
Installation path: /var/www/html/forums
```

## Log files
When I attempt to login to admin account or any account
```
POST https://trigonmc.com/forums/login

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<h1>403 Forbidden</h1>
<p>You do not have permissions to access this page.</p>

</body>
</html>
```

When you attempt to signup.
```
POST https://trigonmc.com/forums/register

Illuminate\Contracts\Validation\ValidationException:  in file /var/www/html/forums/vendor/flarum/core/src/Core/Validator/AbstractValidator.php on line 64
Stack trace:
  1. Illuminate\Contracts\Validation\ValidationException->() /var/www/html/forums/vendor/flarum/core/src/Core/Validator/AbstractValidator.php:64
  2. Flarum\Core\Validator\AbstractValidator->assertValid() /var/www/html/forums/vendor/flarum/core/src/Core/Command/RegisterUserHandler.php:135
  3. Flarum\Core\Command\RegisterUserHandler->handle() /var/www/html/forums/vendor/illuminate/bus/Dispatcher.php:202
  4. call_user_func() /var/www/html/forums/vendor/illuminate/bus/Dispatcher.php:202
  5. Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() /var/www/html/forums/vendor/illuminate/pipeline/Pipeline.php:139
  6. call_user_func() /var/www/html/forums/vendor/illuminate/pipeline/Pipeline.php:139
  7. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /var/www/html/forums/vendor/illuminate/pipeline/Pipeline.php:102
  8. call_user_func() /var/www/html/forums/vendor/illuminate/pipeline/Pipeline.php:102
  9. Illuminate\Pipeline\Pipeline->then() /var/www/html/forums/vendor/illuminate/bus/Dispatcher.php:204
 10. Illuminate\Bus\Dispatcher->dispatchNow() /var/www/html/forums/vendor/illuminate/bus/Dispatcher.php:177
 11. Illuminate\Bus\Dispatcher->dispatch() /var/www/html/forums/vendor/flarum/core/src/Api/Controller/CreateUserController.php:45
 12. Flarum\Api\Controller\CreateUserController->data() /var/www/html/forums/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php:97
 13. Flarum\Api\Controller\AbstractSerializeController->handle() /var/www/html/forums/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php:23
 14. Flarum\Api\Controller\AbstractCreateController->handle() /var/www/html/forums/vendor/flarum/core/src/Api/Client.php:69
 15. Flarum\Api\Client->send() /var/www/html/forums/vendor/flarum/core/src/Forum/Controller/RegisterController.php:60
 16. Flarum\Forum\Controller\RegisterController->handle() /var/www/html/forums/vendor/flarum/core/src/Http/Handler/ControllerRouteHandler.php:53
 17. Flarum\Http\Handler\ControllerRouteHandler->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:69
 18. Flarum\Http\Middleware\DispatchRoute->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 19. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 20. Zend\Stratigility\Dispatch->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Next.php:160
 21. Zend\Stratigility\Next->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/Middleware/SetLocale.php:51
 22. Flarum\Http\Middleware\SetLocale->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 23. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 24. Zend\Stratigility\Dispatch->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Next.php:160
 25. Zend\Stratigility\Next->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php:36
 26. Flarum\Http\Middleware\AuthenticateWithSession->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 27. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 28. Zend\Stratigility\Dispatch->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Next.php:160
 29. Zend\Stratigility\Next->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php:39
 30. Flarum\Http\Middleware\RememberFromCookie->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 31. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 32. Zend\Stratigility\Dispatch->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Next.php:160
 33. Zend\Stratigility\Next->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/Middleware/StartSession.php:48
 34. Flarum\Http\Middleware\StartSession->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 35. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 36. Zend\Stratigility\Dispatch->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Next.php:160
 37. Zend\Stratigility\Next->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php:31
 38. Flarum\Http\Middleware\ParseJsonBody->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 39. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 40. Zend\Stratigility\Dispatch->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Next.php:160
 41. Zend\Stratigility\Next->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/Middleware/HandleErrors.php:61
 42. Flarum\Http\Middleware\HandleErrors->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:212
 43. Zend\Stratigility\Dispatch->dispatchCallableMiddleware() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Dispatch.php:88
 44. Zend\Stratigility\Dispatch->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/Next.php:160
 45. Zend\Stratigility\Next->__invoke() /var/www/html/forums/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:111
 46. Zend\Stratigility\MiddlewarePipe->__invoke() /var/www/html/forums/vendor/flarum/core/src/Http/AbstractServer.php:55
 47. Flarum\Http\AbstractServer->__invoke() /var/www/html/forums/vendor/zendframework/zend-diactoros/src/Server.php:157
 48. Zend\Diactoros\Server->listen() /var/www/html/forums/vendor/flarum/core/src/Http/AbstractServer.php:36
 49. Flarum\Http\AbstractServer->listen() /var/www/html/forums/index.php:16
```

**Comment by franzliedke** [comment] 2018-03-17 11:36
I can't reproduce this, I was able to register successfully (with a fake email). Did you fill out the forms completely?

**Comment by luceos** [comment] 2018-03-19 05:59
Perhaps related:

- https://discuss.flarum.org/d/6491-500-internal-server-error-when-registering-with-an-invalid-password
- https://discuss.flarum.org/d/6645-500-error-on-sign-up

**Comment by franzliedke** [comment] 2018-03-19 22:29
You might indeed be running into the same issue as described in [this forum post](https://discuss.flarum.org/d/6491-500-internal-server-error-when-registering-with-an-invalid-password/6). @ExZiByte Can you please let us know whether your Flarum is running in debug mode (i.e. what is the value of `debug` in your config.php)?

IMO, it does not make sense for pretty error messages to go away when in debug mode. Do we have a ticket for this?

**Comment by ExZiByte** [comment] 2018-03-20 11:01
In the time between me making this post and @franzliedke replying I had reinstalled the forum. It wasn't running in debug mode after other than for grabbing the debug information. And I believe it was due to the email settings cause it started happening right after setting them up. They were the exact same email settings that I had used before without issue.

**Comment by franzliedke** [comment] 2018-03-20 19:41
Hmm, why did login cause a problem then?

If we don't find a reproducable scenario here, I'm afraid we'll need to close this...

**Comment by Ralkage** [comment] 2018-05-15 21:18
@franzliedke I cannot reproduce this as well.

**Comment by luceos** [comment] 2018-05-16 07:06
Closed until someone reports a way to reproduce.

**Comment by luceos** [comment] 2018-05-17 13:15
I think the API controllers should never throw any whoops pages. They should simply return a more extensive JSON error object including the raw trace.

This might indeed not be the case right now.

**Comment by franzliedke** [comment] 2018-12-20 12:52
Closing as stale. Also, #1641 and #1648 should cover this.

**Closed by franzliedke** 2018-12-20 12:52 UTC
Labels: needs-verification

**Comment by muhammetyasarakkaya** [comment] 2020-06-13 14:54
asdsad
