### ISSUE TITLE
Add webApi to check the login status.

### ISSUE THREAD

**Issue by xkeyC** [flarum/core#2601] opened 2021-02-16 15:41 UTC
## Feature Request
If login with 'api/token', the third-party client cannot check the login information.

No webApi can return the logged in user information and token expiration time according to the 'token', which makes the third-party client designed for flarum unable to correctly process the logged in user information.

**Describe the solution you'd like**
Here's an example of my idea:
```
HTTP GET `api/loggedinfo`  // with Authorization HEAD

{
	"data": {
		"type": "loggedinfo",
		"id": "[UserID]",
		"attributes": {
			"username": "[username]", 
			"displayName": "[displayName]", 
			"avatarUrl": "[avatarUrl]",
			"slug": "[slug]",
			"token_expiration_time": [token_expiration_time],
                        ...
		}
	}
}

HTTP GET `api/loggedinfo`  // with invalid Authorization HEAD

{
/// show error
}

```

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**

I think this can help the development of third-party clients.

**Describe alternatives you've considered**

The logged in user information can only be obtained through the `userid` returned by the `API / token'` The third-party client needs to save the `token` and `userid` at the same time, and can't judge whether the `token` is invalid or whether the login status is lost. The processing of user status can only depend on guessing (for example, guessing through the `api/notifications`).

**Comment by askvortsov1** [comment] 2021-02-17 06:42
I like this, but I'm closing it as a duplicate of https://github.com/flarum/core/issues/930, which is on the 0.2 milestone.

**Closed by askvortsov1** 2021-02-17 06:42 UTC
