### ISSUE TITLE
Admin panel menu in mobile view stuck on Dashboard 

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1621] opened 2018-10-30 01:02 UTC
Dev-master/beta 8:

Using mobile view (tried in Mobile Chrome/Mobile Firefox, Android 8.0, and desktop Firefox resized to mobile resolution), it is not possible to access the admin menu to move between admin pages/tabs from the Dashboard page. The menu will not open. 

The menu opens and successfully navigates to other pages from a non-Dashboard page. 

This bug is not present on tablet or desktop modes.

**Comment by franzliedke** [comment] 2018-10-30 06:50
Same if you disable all extensions?

**Comment by jordanjay29** [comment] 2018-10-31 16:43
This is on discuss, I haven't made a test site with dev-master to try.

**Comment by franzliedke** [comment] 2018-10-31 17:07
I just disabled the statistics extension and cannot reproduce - can you?

**Comment by jordanjay29** [comment] 2018-10-31 17:19
I'll try once I'm sure Cloudflare has dumped its cache.

**Comment by jordanjay29** [comment] 2018-10-31 18:05
Correct, with Stats disabled it is not present.

**Comment by tobscure** [comment] 2018-10-31 19:48
We can close this, then, since it will be resolved when we fix the statistics extension (which we already have a PR for).

**Closed by tobscure** 2018-10-31 19:48 UTC
Labels: type/bug
