### ISSUE TITLE
Admin change setting to not allow member to view anything then will see this error

### ISSUE THREAD

**Issue by thuanpq** [flarum/core#924] opened 2016-04-11 02:56 UTC
Notice: Undefined property: stdClass::$data in /vendor/flarum/core/src/Http/Controller/ClientView.php on line 332

**Comment by dcsjapan** [comment] 2016-04-11 03:43
I wasn't able to confirm this on Kulga's test site. @thuanpq Is this the setting you mean?

![screenshot](https://cloud.githubusercontent.com/assets/13129997/14416245/ab8d0dc2-ffe2-11e5-83dd-914e9fd311a0.png)

With this setting I am able to see the forum UI but no content, whether logged in as a member or just browsing the site as a visitor. I'm not seeing any error messages.

Please explain the steps to reproduce the error in more detail.

**Comment by thuanpq** [comment] 2016-04-11 07:46
yes, it's

**Comment by thuanpq** [comment] 2016-04-11 07:48
<img width="386" alt="screen shot 2016-04-11 at 2 47 51 pm" src="https://cloud.githubusercontent.com/assets/6512225/14420132/69085012-fff4-11e5-9d9c-823f2839dcbe.png">
<img width="1080" alt="screen shot 2016-04-11 at 2 48 27 pm" src="https://cloud.githubusercontent.com/assets/6512225/14420142/718706de-fff4-11e5-96d1-4db6b14ba643.png">

**Comment by thuanpq** [comment] 2016-04-11 07:49
can't see anything but that error

**Comment by thuanpq** [comment] 2016-04-11 07:54
Oh, I know what is the reason, user has just registered for account, not activated
<img width="96" alt="screen shot 2016-04-11 at 2 53 00 pm" src="https://cloud.githubusercontent.com/assets/6512225/14420245/2c87c810-fff5-11e5-8f84-ac83bcd7f31b.png">

I have to go to database and update it to 1

**Comment by dcsjapan** [comment] 2016-04-11 09:14
Sounds like it might be related to https://github.com/flarum/core/issues/914

**Comment by datitisev** [comment] 2016-04-11 11:35
@dcsjapan I think it might actually be a duplicate of #914, it seemed to me from that issue we got some different errors every time :disappointed: 

I'm probably wrong, though :wink:

**Comment by franzliedke** [comment] 2016-04-13 14:15
Yep, closing as duplicate of #914.

**Closed by franzliedke** 2016-04-13 14:15 UTC
Labels: Bug
