### ISSUE TITLE
Scroll to top and menu disappears

### ISSUE THREAD

**Issue by zerosonesfun** [flarum/core#1959] opened 2019-12-28 01:44 UTC
## Bug Report

**Current Behavior**
On my mobile device when scrolling to the top quickly, sometimes the menu disappears. This happens at the Flarum discuss forum and a forum I have installed as well. Here is a screenshot. The arrow is pointing to a sliver of the new post icon that you can still see. This is to show that the menu text/icons scroll out of view or perhaps don’t get painted back in the right spot in time. 

<img src="https://i.ibb.co/34GrdrS/AF2-D8827-C5-BE-4-FA7-B480-41007-D30-D0-BE.jpg" alt="AF2-D8827-C5-BE-4-FA7-B480-41007-D30-D0-BE" border="0">

**Steps to Reproduce**
1. Ideally use an iPhone and the Chrome iOS browser
2. Scroll down
3. Quickly swipe up to the top
4. Repeat several times until the menu disappears 

**Expected Behavior**
Menu text/icons should not suddenly disappear even if it is rare.

**Environment**
- Flarum version: Beta 11.1
- Website URL: https://discuss.flarum.org
- Webserver: ?
- Hosting environment: ?
- PHP version: ?
- Browser: For sure iOS Chrome. Could be other mobile browsers. 

**Possible Solution**
This fixed it at my forum and I have not seen any new issues created by doing this. I cancelled out this CSS rule:

`transform: translate3d(0,0,0)`

Which I believe is located here: https://github.com/flarum/core/blob/master/less/common/mixins/header-background.less

Why does this fix it? I don’t know for sure but I’ve read that many people add this transform rule to fix paint issues (issues similar to this one where elements are disappearing). However, instead of being the fix, it seems this rule is causing the issue. 

Is this one rule necessary especially if it is periodically making the main nav bar disappear on certain devices?

**Comment by franzliedke** [comment] 2020-01-03 14:38
Thanks for the report! :raised_hands: 

Has anybody else seen this problem, and - most importantly - on other OS / browser combinations?

@zerosonesfun Could you provide a link to where you read about the problems with this transform rule? Thanks for your research!

**Comment by Ralkage** [comment] 2020-01-04 08:26
@franzliedke I tried to reproduce this in the latest versions of Chrome and Firefox for iOS and Android as well as Safari on iOS and Samsung's browser for Android. Unfortunately, I was unable to reproduce this issue even with the steps to reproduce provided in this issue.

**Comment by zerosonesfun** [comment] 2020-01-04 11:55
> @franzliedke I tried to reproduce this in the latest versions of Chrome and Firefox for iOS and Android as well as Safari on iOS and Samsung's browser for Android. Unfortunately, I was unable to reproduce this issue even with the steps to reproduce provided in this issue.

Yes, sometimes it’s very hard to reproduce. Other times I get it to happen several times in a row. Here is a gif so that you can fully see what I mean. This shows the demo site, and then the discuss.flarum site as well. This is Chrome iOS, latest version.

<img src="https://i.ibb.co/BtBW6Q3/F9-C19-D82-CCE2-47-C4-800-D-085-D6855883-E.gif" alt="F9-C19-D82-CCE2-47-C4-800-D-085-D6855883-E" border="0">

@franzliedke - I read about the transform rule here: https://stackoverflow.com/a/10170170 ...notice the first comment under this answer. It seems this rule can fix these types of issue, but also can cause them. 

Here are some other people talking about it. Although these say to add this rule, not remove it, all of these types of posts led me to the idea of removing the nav bar’s transform rule. Since I removed the rule, I can no longer reproduce this at my site. 

https://stackoverflow.com/q/50105780

https://stackoverflow.com/a/18764086

https://stackoverflow.com/a/25923988

I will admit though that this is a very small bug and it may be a while until someone out there can reproduce it to help verify.

I think asking, “Why does the header nav bar have this rule in the first place?”, could be another way to look at this. Even putting this issue aside... is that rule truly doing anything? Or, I should say... Is it doing anything noticeable?

**Comment by franzliedke** [comment] 2020-01-06 22:42
> I wonder if this transform rule has always been there or if it was added to fix a different bug? So far, I don’t see anything negative happening as a result of me removing this rule at my forum.

I can only assume here, and would guess it was added to speed up the CSS transition animations: https://github.com/flarum/core/blob/d7a5a6ad14c351d402442daa93eb8cc871f110ef/less/common/mixins/header-background.less#L10

**Comment by franzliedke** [comment] 2020-01-06 22:42
@tobyzerner Sorry to bother, do you remember what problems line 9 solves?

https://github.com/flarum/core/blob/d7a5a6ad14c351d402442daa93eb8cc871f110ef/less/common/mixins/header-background.less#L9

**Comment by tobyzerner** [comment] 2020-01-07 00:52
@franzliedke I think it was something to do with Chrome and transparency. Confirmed on digging: https://github.com/flarum/core/blob/3925e5892c7e9fe9671f99c84cdafe56e4a83480/less/lib/layout.less#L25 Might not be necessary anymore.

**Comment by zerosonesfun** [comment] 2020-12-17 14:35
Confirming this is still an issue even going into beta 15. But, on top of the top nav bar disappearing, there is also an issue with the tag selector drawer menu on mobile. For my beta 14 installations, for reasons I personally do not fully understand, the following fixes it. 

`.App:before {
    -webkit-transform: initial;
    transform: initial;
} `

For beta 15 and higher, maybe (not tested yet) the following could work:

`.App-header {
    transform: initial !important;
} `

**Comment by zerosonesfun** [comment] 2020-12-19 02:08
Solved. Is this the permanent fix? Maybe not. Maybe transform needs to be completely removed or adjusted some other way. But, here’s a fix. It is now app-navigation that is the culprit. 

`.App-navigation { transform: initial;}`

Here’s video evidence. I bought an iOS browser that comes with a dev console. Most/all free browsers for iOS don’t have that. It’s worth it though. It was only $6.99 and now I can troubleshoot small issues like this on the couch, or in bed on my phone. 😌 Anyway, this video will show me recreating the two jumping issues on my phone. Then it will show me editing the CSS, and then it shows me unable to reproduce the issue since `transform:initial` fixes it. 

https://vimeo.com/492702913

**Comment by SychO9** [comment] 2020-12-19 10:26
I did some digging and I believe the bug that the transform rule tries to fix which was added nearly 5years ago, has been long fixed in newer browsers.

I think it's safe to remove it now.

Two spots where we we need to remove it:

https://github.com/flarum/core/blob/859f0145396082558e00138214e572dd5d7d3ba5/less/common/mixins/header-background.less#L9

https://github.com/flarum/core/blob/859f0145396082558e00138214e572dd5d7d3ba5/less/forum/Composer.less#L222

**Comment by dartrax** [comment] 2020-12-26 20:01
> Has anybody else seen this problem, and - most importantly - on other OS / browser combinations?

I confirm this issue, noticed it today and searched for a bug report - tadaaa...
It also appears on nightly.flarum.site
I'm using mobile Safari on iOS 14.1

**Comment by askvortsov1** [comment] 2021-01-05 00:06
@SychO9 Does removing those lines fix the issue locally? I don't have an iphone so I can't test, but if this fixes the issue, it makes sense to me.

**Comment by SychO9** [comment] 2021-01-05 20:06
I don't have an iphone either, so I cannot test, but @zerosonesfun who has been able to reproduce the issue multiple times has confirmed removing the transform rule fixes the issue.

**Comment by dartrax** [comment] 2021-01-05 20:48
@askvortsov1 I'm happy to report that removing the lines fixes this for me, too.
I use a custom header html code. Using that, the problem did not occur on my .beta15-forum at all, so I first temporary removed the custom header, checked that the issue was there (it was), then applied the fix, and the issue is gone.
I did not noticed any negative side-effects yet.

**Closed** 2021-01-06 00:40 UTC
Labels: type/bug
