### ISSUE TITLE
Issue with CSS that is load only on main discussion list

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2904] opened 2021-06-06 19:33 UTC
## Bug Report

**Current Behavior**

Adding CSS in Flarum admin side to have Author label near the Author post profile works only if a discussion is loaded from the main Flarum discussion list. If a discussion page is refresh or opened in new tab the CSS will not work.

CSS:

```
div.PostStream div.PostStream-item:not(:first-child) article.CommentPost.Post.Post--by-start-user .Post-header h3:after {
content: "Author";
background: #F05D1D;
border-radius: 4px;
padding-left: 10px;
padding-right: 10px;
color: #fff;
margin-left: 14px;
}
```

You can find more info about this issue confirmed from a dev here:
https://discuss.flarum.org/d/26007-adding-author-label-to-posts/44

> Looks like this probably happens because the "user" object is compared (see https://github.com/flarum/core/blob/d4e3254395fa03a0653218a543e23ad9de76ae77/js/src/forum/components/Post.js#L135-L137) and may differ between the session user & the discussion user. The solution would probably be to compare their IDs or specific data instead of the entire object.

> I can confirm this is a Flarum core bug.

**Comment by justoverclockl** [comment] 2021-06-06 19:37
duplicate of mine i suppose
https://github.com/flarum/core/issues/2750

**Comment by datitisev** [comment] 2021-06-06 19:46
Yep, closing as duplicate of #2750.

**Closed by datitisev** 2021-06-06 19:46 UTC
