### ISSUE TITLE
Improve (or avoid) the nojs experience

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#881] opened 2016-03-20 04:46 UTC
Inspired by this thread, following an update of discuss.flarum.org:

https://discuss.flarum.org/d/2303-locked-out-via-nojs

The message displayed on the basic HTML site could suggest that users try clearing their browser cache and reloading the page to see if that fixes the problem.

**Comment by tobscure** [comment] 2016-03-20 04:50
:+1: we should also remove the redirection to nojs=1 so that they can hit refresh and it will attempt to boot the JS app again, rather than just displaying the nojs version

**Comment by JoshyPHP** [comment] 2016-03-20 14:33
Or maybe add a link to the JS-enabled page in the alert banner.

**Comment by franzliedke** [comment] 2016-03-21 15:20
Getting this nojs stuff right is tricky indeed. I think I suggested automatically redirecting back to the JS version with JavaScript. This takes care of those people that have JS disabled. But it can also cause infinite back-and-forth redirects if there is some JS error on the site.

How would this work without a redirect, @tobscure ?

I like the solution by @JoshyPHP best.

**Comment by tobscure** [comment] 2016-03-22 03:02
Maybe if we catch a JS error, we show an error message (using JavaScript) which says "please try reloading the page, or click here to view the HTML-only version"

**Comment by datitisev** [comment] 2016-03-22 11:42
Couldn't we use something with the history APi to replace state to '/' but while they are in the noJs page?

**Comment by tobscure** [comment] 2016-03-23 06:19
@datitisev That's a very clever idea :)

**Comment by franzliedke** [comment] 2016-03-23 10:08
But it doesn't solve the problem for those people with JS disabled, once they enable JS and refresh the page, they will still see that error message. (Only then the history API will kick in.)

**Comment by tobscure** [comment] 2016-03-23 10:29
People with JS disabled won't be redirected to nojs=1 in the first place – they'll just see the `<noscript>` content, and when they enable JS and refresh, it will work

**Comment by franzliedke** [comment] 2016-03-23 10:47
Ah, I totally missed that part. ;)

**Comment by datitisev** [comment] 2016-03-23 11:10
Glad I was able to help :)

Too bad I get my ideas in my sleep though.
I had to wait for morning and hope I would remember. ;)

**Comment by webeindustry** [comment] 2016-04-05 01:37
It seems there is a fix for this, I found here:

[https://laracasts.com/discuss/channels/laravel/how-to-force-browser-to-update-js-and-css-files-cache-after-deploy?page=1](url)

It requires creating a versioning system for javascript. So when an update is applied, the client will be forced to clear the cache from the older version.

**Comment by dcsjapan** [comment] 2016-04-05 01:46
:+1: for ways to avoid the nojs experience altogether.

Troubleshooting suggestions and redirects would still be good, if all else fails.

**Comment by franzliedke** [comment] 2016-04-05 02:10
@webeindustry We already add a version number to the JS files (or really, a hash). The problem in this case is probably that the HTML containing the references to old JS versions was cached by the browser -  *that* should not happen, and it probably means we need to update our server configuration documentation.

**Comment by gwillem** [comment] 2017-12-02 10:25
@franzliedke are you sure it's a hash? See these files with same hashes, that are not the same:

https://greenmeteor.freeflarum.com/assets-nojs/admin-46889923.js
https://greenmeteor.freeflarum.com/assets-yesjs/admin-46889923.js

(`php flarum cache:clear` inbetween)

See also https://discuss.flarum.org/d/2303-locked-out-via-nojs/5

**Comment by sijad** [comment] 2017-12-02 10:47
@gwillem I guess it's related to https://github.com/flarum/core/issues/837#issuecomment-288233553

please try to remove `rev-manifest.json`

**Comment by tobscure** [comment] 2017-12-02 21:53
From my experience there is a bug in the asset compiler where the hash is only generated based on the modification timestamp of source *files*, but source *strings* are not taken into account.

So for example, if you alter custom LESS in the admin panel, the hash won't change and you'll need to clear your browser cache to force a reload.

**Comment by gwillem** [comment] 2017-12-15 11:30
@tobscure that could be an issue, however I have a reproducible test case which looks like it has a distinct cause. Reproduce:

1. Base install B7
1. `composer require flagrow/masquerade`
1. SQL: ```update settings set `value` = '["flarum-english"]' where `key` = 'extensions_enabled';```
1. `php flarum cache:clear`
1. Browse to /admin, enable extension. Poof, nojs=1. According to dev tools, the same JS files are requested which are then loaded from mem cache by Chrome, although the content has changed (a.o. `vendor/flagrow/masquerade/js/admin/dist/extension.js` was added).
1. `php flarum cache:clear; rm assets/rev-manifest.json`
1. Reload /admin and check /assets: new JS files with a new hash have been generated. 

Conclusion: the revision hash is not updated when new assets are included. 

Then I have added ` @unlink($this->getDestination() . '/rev-manifest.json');` after `$this->flushCss();` in WebAppAssets.flush() and retried.

Result: no nojs error. However, the translations are broken: 
![image](https://user-images.githubusercontent.com/1145479/34040329-795d6c5e-e193-11e7-92b6-78d44f3577ed.png)
A force reload works. So perhaps, this is the error that you were referring to (hashes not based on strings). 
Also, when enabling a few extensions, it appears that old asset files aren't removed.

**Comment by gwillem** [comment] 2017-12-15 11:31
Also, I want to note that nearly every user of FreeFlarum encounters this nojs issue. So it is quite a showstopper for new Flarum users.

**Comment by gwillem** [comment] 2017-12-15 13:09
I've tested https://github.com/flarum/core/commit/15b573bd93f4e2fc70d26b4f15f50a99177fe7ca (also hash strings) and remove rev-manifest.json between cache clears, but the updated locale JS file is still saved under the same hash:
```
before:
{"admin.css":"9853bbe2","admin.js":"efc28d58","admin-en.js":"deb59aba"}
install extension, cache:clear (inc removal of rev-manifest.json), admin reload:
{"admin.css":"7a96f471","admin.js":"7d10f74f","admin-en.js":"deb59aba"}
```

**Comment by gwillem** [comment] 2017-12-15 16:02
Also, note that wiping `rev-manifest.json` in `WebAppAssets.flush()` as proposed by @tobscure (https://github.com/flarum/core/pull/1160#discussion_r112367171) will have bad side effects, as the flush is called multiple times (for `forum` and `admin`). That would delete the revision before the second flush could unlink its files.

**Comment by gwillem** [comment] 2017-12-15 16:20
Also, the generated hash for locale files is the same (`deb59aba`) for every Flarum install, as it is based on an empty string --> https://publicwww.com/websites/%22deb59aba%22/

**Comment by franzliedke** [comment] 2017-12-15 20:15
> the same (deb59aba) for every Flarum install
Ouch. :grin:

**Closed** 2018-06-30 03:01 UTC
Labels: Needs Discussion
