### ISSUE TITLE
[Feature Request] Postgress Support

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [flarum/core#1857] opened 2019-08-24 17:07 UTC
## Feature Request: PostgreSQL support
PostgreSQL, also known as Postgres, is a free and open-source relational database management system (RDBMS) emphasizing extensibility and technical standards compliance. It is designed to handle a range of workloads, from single machines to data warehouses or Web services with many concurrent users. It is the default database for macOS Server,[10][11][12] and is also available for Linux, FreeBSD, OpenBSD, and Windows.

PostgreSQL features transactions with Atomicity, Consistency, Isolation, Durability (ACID) properties, automatically updatable views, materialized views, triggers, foreign keys, and stored procedures.[13] PostgreSQL is developed by the PostgreSQL Global Development Group, a diverse group of many companies and individual contributors.[14] 

**Describe the solution you'd like**
Added Support, I saw in the past there were pull request for it but as far as I can tell it's not supported by the team

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
This will be useful for many people as PostgreSQL is a very popular database and many people are already running it for other applications

**Comment by franzliedke** [comment] 2019-08-24 21:42
Duplicate of flarum/issue-archive#411.

**Closed by franzliedke** 2019-08-24 21:42 UTC
