### ISSUE TITLE
Able to delete user but browser does not go back to previous page/route

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#1777] opened 2019-04-21 02:42 UTC
## Bug Report

**Current Behavior**
When I attempt to delete a dummy user I created, the user gets deleted but the browser does not go back to the last page/route I went to before going to the user's profile and performing the deletion.

**Steps to Reproduce**
1. Create a dummy user.
2. Go to the dummy user profile as yourself as an Administrator.
3. Attempt to delete the dummy user.
4. Page does not redirect and error is thrown in the dev console.

**Expected Behavior**
I should be redirected to the last page/route I went to before I went to the dummy user's profile and deleted it.

**Screenshots**
![image](https://user-images.githubusercontent.com/2059356/56464639-e7c51d80-63bb-11e9-86aa-7c154fd483cc.png)

![image](https://user-images.githubusercontent.com/2059356/56464671-49858780-63bc-11e9-92ad-9bd2a80b70c5.png)

![image](https://user-images.githubusercontent.com/2059356/56464651-05928280-63bc-11e9-9cc4-2805fe67647f.png)
![image](https://user-images.githubusercontent.com/2059356/56464666-37a3e480-63bc-11e9-8a16-805d0a88b14d.png)

**Environment**
- Flarum version: 0.1.0-beta.8.1
- Website URL: localhost
- Webserver: Apache
- Hosting environment: Local
- PHP version: 7.2.14
- Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)

```
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.14
Loaded extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, openssl, curl, fileinfo, gd, get
text, gmp, intl, imap, ldap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, xmlrpc, xsl
+----------------------+-----------------+--------+
| Flarum Extensions    |                 |        |
+----------------------+-----------------+--------+
| ID                   | Version         | Commit |
+----------------------+-----------------+--------+
| flarum-approval      | v0.1.0-beta.8   |        |
| flarum-bbcode        | v0.1.0-beta.8   |        |
| flarum-emoji         | v0.1.0-beta.8   |        |
| flarum-lang-english  | v0.1.0-beta.8   |        |
| flarum-flags         | v0.1.0-beta.8.1 |        |
| flarum-likes         | v0.1.0-beta.8.1 |        |
| flarum-lock          | v0.1.0-beta.8   |        |
| flarum-markdown      | v0.1.0-beta.8   |        |
| flarum-mentions      | v0.1.0-beta.8.1 |        |
| flarum-statistics    | v0.1.0-beta.8   |        |
| flarum-sticky        | v0.1.0-beta.8   |        |
| flarum-subscriptions | v0.1.0-beta.8   |        |
| flarum-suspend       | v0.1.0-beta.8   |        |
| flarum-tags          | v0.1.0-beta.8.2 |        |
+----------------------+-----------------+--------+
Base URL: http://b81.test
Installation path: C:\wamp64\www\b81.test
Debug mode: off
```

**Possible Solution**

N/A

**Additional Context**
I have all 3rd party extensions disabled and the bundled Flarum ones enabled so I have already done the typically debugging steps.

Debug mode disabled or enabled also doesn't make a difference in replicating this _possible_ bug.

**Comment by matteocontrini** [comment] 2019-04-21 08:38
I'd say it might be a duplicate of #1750

**Closed** 2019-06-27 19:17 UTC
