### ISSUE TITLE
Browsing without cookies enabled displays no JS version

### ISSUE THREAD

**Issue by samdha** [flarum/core#474] opened 2015-09-15 00:44 UTC
When I browse the thread at http://discuss.flarum.org/d/952-question-for-the-devs without cookies enabled, I am redirected to the paged version of the thread for browsers without JavaScript. Enabling cookies for the site and visiting the URL again results in the full "normal" version of the page. Enabling cookies and reloading is not sufficient, as the browser has been redirected to the URL with "?nojs=1" appended.

Using Firefox 40.0.3 on Windows with the Cookie Controller add-on.

**Comment by franzliedke** [comment] 2016-07-07 16:05
We should definitely add a link with an inviting text to the JS version of the page from the no-JS version. That should improve the situation - I will do that soon.

**Comment by franzliedke** [comment] 2020-01-08 23:35
Closing as a duplicate of flarum/issue-archive#234.

**Closed by franzliedke** 2020-01-08 23:35 UTC
Labels: type/bug
