### ISSUE TITLE
[UI] Irregularities on the scroller while in comment list

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#435] opened 2015-09-05 14:50 UTC
See screenshot:

![screen shot 2015-09-05 at 10 49 36](https://cloud.githubusercontent.com/assets/8352292/9699761/ed71e416-53bb-11e5-91b5-f677210e6b2f.png)

Yosemite, Safari.

**Comment by askvortsov1** [comment] 2020-10-02 06:31
Duplicate of https://github.com/flarum/core/issues/907

**Closed by askvortsov1** 2020-10-02 06:31 UTC
Labels: type/bug
