### ISSUE TITLE
FIX: TagTile-children a

### ISSUE THREAD

**Issue by KitsuneSolar** [flarum/core#695] opened 2015-12-29 08:50 UTC
Page "/tags":

![2015-12-29 11-44-01](https://cloud.githubusercontent.com/assets/12877339/12031819/2f0b9d34-ae22-11e5-854c-790cfbd64ceb.png)

FIX:

```
.TagTile-children a {
  display: inline-block;
}
```

![2015-12-29 11-45-28](https://cloud.githubusercontent.com/assets/12877339/12031820/2f0e0cb8-ae22-11e5-8410-284ebd151671.png)

**Comment by franzliedke** [comment] 2015-12-29 11:02
I'll close this as a duplicate of #653. It's ot *exactly* the same issue, but the two are close enough that they can be fixed together.

Thanks for reporting. :)

**Closed by franzliedke** 2015-12-29 11:02 UTC
