### ISSUE TITLE
Improve SEO for discussion lists

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2734] opened 2021-03-24 13:38 UTC
## Bug Report

**Current Behavior**
Google doesn't index discussion lists after the first 20 items, because of the load more button.

We should reverse the `?page=x` query param to work from oldest to newest, then we can provide links to the next and previous page using `<link rel=next>` and back.

This will allow Google to detect the pagination.

This is the recommended technique by Google for infinite scrolling (and presumably for other dynamically loaded content).

We need to reverse this because `?page=x`'s content will continuously change as new discussions are created and Google state that page content should be fundamentally the same at the same URL in 2 weeks time as it is now.

Google blog about infinite scroll: https://developers.google.com/search/blog/2014/02/infinite-scroll-search-friendly

**Comment by askvortsov1** [comment] 2021-03-24 13:41
Possible duplicate of https://github.com/flarum/core/issues/2397?

**Comment by davwheat** [comment] 2021-03-24 13:44
It's similar, but I don't actually think that one is an issue. I don't see any issue with it -- search engines should use query params instead of the `/100` or `/35` syntax to prevent page duplication.

**Comment by askvortsov1** [comment] 2021-03-24 13:46
The technique recommended there is use of a `page` param for canonical URL (which is the one used by SEO, right?) as opposed to the actual post URLs.

**Comment by davwheat** [comment] 2021-03-24 13:49
This is about discussion lists rather than discussions themselves.

**Comment by askvortsov1** [comment] 2021-03-24 13:51
Ah, my bad, misread the title.

In that case, maybe this should fall under flarum/issue-archive#162?

**Comment by davwheat** [comment] 2021-03-24 13:56
Yeah it could be included as part of that, if you'd prefer

**Closed** 2021-03-24 14:03 UTC
