### ISSUE TITLE
'All Discussions' section doesn't show multi-tag posts in a single tag restricted forum.

### ISSUE THREAD

**Issue by Venima** [flarum/core#1293] opened 2017-11-21 13:09 UTC
## Explanation

My forum only allows 1 tag per post, but there is one exception: the Forum Rules post. This post I gave every tag, so that it features in every sub-forum, and this works but it doesn't show up under 'All Discussions'. This is the only place it is absent.

Expectation: Posts with multiple tags should appear under All Discussions, regardless of the forum's current tag restriction.

## Technical details

- Version of Flarum: 0.1.0-beta.7
- Website URL where the bug is visible: http://forum.nyskogames.com
- PHP version: 7.0.22-0ubuntu0.16.04.1
- Hosted environment: vps

## To observe the problem:

- Go to http://forum.nyskogames.com, and ensure All Discussions is selected. Note that 'Forum Rules' post is not present. 
- Click on Introductions and note that 'Forum Rules' is present and pinned. 
- Return to All Discussions, and note the single-tagged pinned posts from subforums. 

Thus the only differentiating factor is that it is a multi-tagged post, with more tags than the forum's current tag restriction. To reiterate, I would expect this post to still be present under All Discussions, in-spite of the restriction.

## To reproduce the problem:

- Create a forum with 3 tags. 
- Set forum's tag limit to 3. 
- Create post 'Rules' with all 3 tags selected, and post 'Test' with 1 tag selected. 
- Change forum's tag limit to 1 and observe results.

**Comment by franzliedke** [comment] 2017-12-13 20:59
Thank you for the awesome and precise bug report!

**Comment by askvortsov1** [comment] 2020-02-29 06:41
I am unable to reproduce this under beta 12, I'm assuming the logic causing it got fixed as part of some other issue, but this issue was never closed.

**Comment by askvortsov1** [comment] 2020-06-27 18:21
Hi! We're unable to replicate this on our demo site (https://beta.flarum.site/) on beta 13, so I'm going to close this. If someone is able to reproduce this on the latest beta, please feel free to reopen!

**Closed by askvortsov1** 2020-06-27 18:21 UTC
Labels: type/bug
