### ISSUE TITLE
Problems with the Admin option/Basics/Default Language

### ISSUE THREAD

**Issue by lcarlos-fokus** [flarum/core#429] opened 2015-09-04 10:45 UTC
There are the following problems:
..When changed the option does not enable the Save Changes button
..After Refresh the page always comes back to the option English (en) even after being selected another Language

**Comment by Petrouchka** [comment] 2015-09-16 16:38
+1

**Comment by Luceos** [comment] 2016-01-04 15:42
Do you have other options in the dropdown? What language did you install additionally? This question is for both of you (@lcarlos-fokus and @petrouchka)

**Comment by franzliedke** [comment] 2016-01-20 19:36
I cannot reproduce this, either.

Closing this until further information is provided. @lcarlos-fokus @Petrouchka 
(What browser are you using? Any error messages in the browser console?)

**Closed by franzliedke** 2016-01-20 19:36 UTC
Labels: Bug
