### ISSUE TITLE
Reply popover hidden below header

### ISSUE THREAD

**Issue by lightonflux** [flarum/core#517] opened 2015-09-18 20:42 UTC
When your read a comment on top the viewport, and you hover the reply button, the popover showing the post is below the header of the side. 

Video: https://imgrush.com/kcf2klhauIeu

Solutions:

 * Draw popover under mouse if neccesarry
 * automatically scroll up to show popover and scroll back when the popover disappears

**Comment by tobscure** [comment] 2016-03-16 02:25
Duplicate of #316 I think (video is no longer accessible)

**Closed by tobscure** 2016-03-16 02:25 UTC
Labels: Bug, Design
