### ISSUE TITLE
Issue about bad visual if you have many tags permissions

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2810] opened 2021-04-25 14:58 UTC
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Go to admin#/permissions
2. Here I have 8 long label tag that goes out of the screen
3. For be able to set permission and to see latest tab you need scroll down all the page than horizontal scrollbar is showed but is again hidden if you scroll app.

Is almost impossible set permission in this way because you cannot read the row: the left column has the text cut out impossible to read.

**Expected Behavior**

Read the left column and have a way to don't see the horizontal scrollbar and avoid seeing the horizontal bar disappear, if necessary. Maybe you just have to fix the fact description on the left are cut out of the screen for the right tag if you have many tags that need the horizontal scroll bar.

**Screenshots**

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/115998353-21eada80-a5e7-11eb-8902-717692a8760f.jpg)

Hard to understand permission in this way, maybe impossible!

**Environment**
- Flarum version: Beta 16
- Website URL: https://community.peopleinside.it/
- Webserver: [e.g. apache, nginx] -> Apache
- Hosting environment: [e.g. shared, vps] VPS
- PHP version:  7.4
- Browser: [e.g. chrome 67, safari 11] Firefox 89

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

Flarum core 0.1.0-beta.16
PHP version: 7.4.xx
Loaded extensions: Core, date, libxml, pcre, dom, fileinfo, filter, hash, json, SPL, bz2, posix, Reflection, session, SimpleXML, standard, xml, xmlreader, xmlwriter, bcmath, openssl, calendar, ctype, curl, dba, mbstring, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, mailparse, exif, memcached, zlib, pcntl, PDO, pdo_sqlite, shmop, soap, sockets, sqlite3, sysvsem, sysvshm, tidy, tokenizer, xmlrpc, xsl, zip, Phar, mysqlnd, mysqli, pdo_mysql, ionCube Loader, Zend OPcache
+-------------------------------------+------------------+--------+
| Flarum Extensions                   |                  |        |
+-------------------------------------+------------------+--------+
| ID                                  | Version          | Commit |
+-------------------------------------+------------------+--------+
| flarum-flags                        | v0.1.0-beta.16   |        |
| flarum-markdown                     | v0.1.0-beta.16.1 |        |
| flarum-approval                     | v0.1.0-beta.16   |        |
| flarum-subscriptions                | v0.1.0-beta.16   |        |
| flarum-tags                         | v0.1.0-beta.16   |        |
| askvortsov-rich-text                | v1.1.1           |        |
| fof-linguist                        | 0.6.0            |        |
| fof-terms                           | 0.6.2            |        |
| fof-merge-discussions               | 0.5.1            |        |
| clarkwinkelmann-first-post-approval | 0.1.4            |        |
| fof-follow-tags                     | 0.7.2            |        |
| fof-username-request                | 0.5.0            |        |
| fof-split                           | 0.7.0            |        |
| fof-cookie-consent                  | 0.5.0            |        |
| fof-disposable-emails               | 0.3.0            |        |
| clarkwinkelmann-emojionearea        | 0.3.1            |        |
| fof-nightmode                       | 0.8.0            |        |
| fof-stopforumspam                   | 0.5.0            |        |
| fof-spamblock                       | 0.5.0            |        |
| fof-oauth                           | 0.3.0            |        |
| flarum-emoji                        | v0.1.0-beta.16   |        |
| fof-user-directory                  | 0.6.1            |        |
| flarum-pusher                       | v0.1.0-beta.16   |        |
| flarum-suspend                      | v0.1.0-beta.16   |        |
| fof-user-bio                        | 0.5.0            |        |
| fof-default-user-preferences        | 0.4.0            |        |
| nearata-lang-italian                | v0.1.0-beta.16   |        |
| flarum-akismet                      | v0.1.0-beta.16   |        |
| flarum-statistics                   | v0.1.0-beta.16   |        |
| flarum-lang-english                 | v0.1.0-beta.16   |        |
| flarum-sticky                       | v0.1.0-beta.16   |        |
| flarum-mentions                     | v0.1.0-beta.16   |        |
| flarum-lock                         | v0.1.0-beta.16   |        |
| flarum-likes                        | v0.1.0-beta.16   |        |
| flarum-bbcode                       | v0.1.0-beta.16   |        |
| noriods-auto-more                   | 0.3.1            |        |
| fof-links                           | 0.6.0            |        |
| fof-moderator-notes                 | 0.5.0            |        |
| fof-recaptcha                       | 0.3.2            |        |
| ianm-synopsis                       | 0.2.0            |        |
+-------------------------------------+------------------+--------+
Base URL: https://community.peopleinside.it

**Possible Solution**

Fix the left column text to be always visible or change the design

**Additional Context**

**Comment by ornanovitch** [comment] 2021-05-12 10:23
> Fix the left column text to be always visible

100% agree that this would be a very important temporary fix, I have almost 20 permission lists and it becomes super difficult to handle those...

> or change the design

I agree, note that this is already discussed in flarum/issue-archive#253 and planned for [0.3](https://github.com/flarum/core/milestone/9)

So this is a duplicate of flarum/issue-archive#253 but a temporary fix by the left column would be very appreciated

**Closed** 2021-08-14 23:21 UTC
