### ISSUE TITLE
Tooltip bug with italian language

### ISSUE THREAD

**Issue by justoverclockl** [flarum/core#2894] opened 2021-05-31 17:46 UTC
Version: 1.0

Tooltip bug with italian language

![Immagine](https://user-images.githubusercontent.com/79002016/120227088-d57b6600-c248-11eb-90e1-6171765e7246.png)

**Comment by PeopleInside** [comment] 2021-06-04 18:44
https://github.com/flarum/core/issues/2636

Thank you for reporting this

**Comment by SychO9** [comment] 2021-06-05 10:37
Duplicate of flarum/issue-archive#144

**Closed by SychO9** 2021-06-05 10:37 UTC

**Comment by justoverclockl** [comment] 2021-06-05 11:36
but is also closed with no resolution, just to know u about that ;)

**Comment by PeopleInside** [comment] 2021-06-05 12:42
> 
> 
> but is also closed with no resolution, just to know u about that ;)

Issue https://github.com/flarum/core/issues/2636 is not closed, is opened without yet a solution merged.

**Comment by davwheat** [comment] 2021-06-05 14:31
A solution was possible with CSS tooltips, but we've decided to hold off on that for a while. I plan to replace Bootstrap tooltips with another library in the future, and that should fix this issue.
