### ISSUE TITLE
Search returns no result

### ISSUE THREAD

**Issue by barisbulut** [flarum/core#530] opened 2015-09-21 15:59 UTC
We installed 0.1 beta 2 and added sample discussions but when we try to search some words from the discussion topics search returns "Looks like there are no discussions here. Why don't you create a new one?".

Edit: Made clarification about the problem

**Comment by franzliedke** [comment] 2015-09-21 20:50
Please tell us why it shouldn't.

**Comment by tobscure** [comment] 2015-09-22 00:13
Presuming duplicate of #257

**Closed by tobscure** 2015-09-22 00:13 UTC
